// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: /home/herson/Repositorios Git/Proyecto1_Compi1/Proyecto1_Compi1/app/src/main/Flex/Lexer.flex

package com.example.proyecto1_compi1.Analizadores;
//imports
import com.example.proyecto1_compi1.models.Token;
import com.example.proyecto1_compi1.models.ErrorLexico;
import java.util.ArrayList;
import java.util.List;


@SuppressWarnings("fallthrough")
public class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\0\1\14\1\15"+
    "\1\16\1\12\1\17\1\20\1\21\1\22\3\23\1\24"+
    "\6\23\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\60\1\61\1\62\1\63"+
    "\1\64\1\65\1\66\1\67\1\70\1\71\1\72\1\0"+
    "\1\73\1\74\1\75\1\76\1\77\1\100\1\101\1\102"+
    "\1\103\1\45\1\104\1\105\1\106\1\107\1\110\1\111"+
    "\1\45\1\112\1\113\1\114\1\115\1\45\1\116\1\117"+
    "\1\120\1\121\1\26\1\122\1\26\1\123\6\0\1\3"+
    "\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\3\1\1\3\1\4\1\1\1\5"+
    "\1\6\2\7\1\4\1\10\1\11\1\7\1\11\1\12"+
    "\1\1\41\13\1\1\1\14\1\11\1\0\1\15\7\0"+
    "\2\13\1\16\5\13\1\16\37\13\4\0\1\10\4\0"+
    "\16\13\1\17\34\13\3\0\1\20\12\0\7\13\1\21"+
    "\31\13\5\0\1\22\1\23\7\0\1\24\1\25\16\13"+
    "\1\0\1\13\1\26\6\13\1\0\1\13\13\0\10\13"+
    "\1\0\3\13\1\0\1\13\1\27\1\30\2\0\1\31"+
    "\1\32\5\0\6\13\1\0\1\13\1\0\1\13\7\0"+
    "\3\13\1\0\1\13\1\0\1\13\3\0\1\33\1\13"+
    "\1\0\1\13\1\21\1\13\1\0\1\13\1\0\2\13"+
    "\2\0\1\13\1\0\1\13\1\0\1\13\1\0\1\13"+
    "\1\0\3\13";

  private static int [] zzUnpackAction() {
    int [] result = new int[332];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\124\0\250\0\374\0\u0150\0\u01a4\0\u01f8\0\124"+
    "\0\u024c\0\u02a0\0\124\0\124\0\u02f4\0\u0348\0\u039c\0\u03f0"+
    "\0\u0444\0\u0444\0\124\0\u0498\0\u04ec\0\u0540\0\u0594\0\u05e8"+
    "\0\u063c\0\u0690\0\u06e4\0\u0738\0\u078c\0\u07e0\0\u0834\0\u0888"+
    "\0\u08dc\0\u0930\0\u0984\0\u09d8\0\u0a2c\0\u0a80\0\u0ad4\0\u0b28"+
    "\0\u0b7c\0\u0bd0\0\u0c24\0\u0c78\0\u0ccc\0\u0d20\0\u0d74\0\u0dc8"+
    "\0\u0e1c\0\u0e70\0\u0ec4\0\u0f18\0\u0f6c\0\u0fc0\0\124\0\124"+
    "\0\u0150\0\124\0\u1014\0\u1068\0\u10bc\0\u1110\0\u1164\0\u11b8"+
    "\0\u120c\0\u1260\0\u12b4\0\u1308\0\u135c\0\u13b0\0\u1404\0\u1458"+
    "\0\u14ac\0\u04ec\0\u1500\0\u1554\0\u15a8\0\u15fc\0\u1650\0\u16a4"+
    "\0\u16f8\0\u174c\0\u17a0\0\u17f4\0\u1848\0\u189c\0\u18f0\0\u1944"+
    "\0\u1998\0\u19ec\0\u1a40\0\u1a94\0\u1ae8\0\u1b3c\0\u1b90\0\u1be4"+
    "\0\u1c38\0\u1c8c\0\u1ce0\0\u1d34\0\u1d88\0\u1ddc\0\u1e30\0\u1e84"+
    "\0\u1ed8\0\u1f2c\0\u1f80\0\u1fd4\0\u2028\0\u1164\0\u207c\0\u20d0"+
    "\0\u2124\0\u2178\0\u21cc\0\u2220\0\u2274\0\u22c8\0\u231c\0\u2370"+
    "\0\u23c4\0\u2418\0\u246c\0\u24c0\0\u2514\0\u2568\0\u25bc\0\u2610"+
    "\0\u04ec\0\u2664\0\u26b8\0\u270c\0\u2760\0\u27b4\0\u2808\0\u285c"+
    "\0\u28b0\0\u2904\0\u2958\0\u29ac\0\u2a00\0\u2a54\0\u2aa8\0\u2afc"+
    "\0\u2b50\0\u2ba4\0\u2bf8\0\u2c4c\0\u2ca0\0\u2cf4\0\u2d48\0\u2d9c"+
    "\0\u2df0\0\u2e44\0\u2e98\0\u2eec\0\u2f40\0\u2f94\0\u2fe8\0\u303c"+
    "\0\124\0\u3090\0\u30e4\0\u3138\0\u318c\0\u31e0\0\u3234\0\u3288"+
    "\0\u32dc\0\u3330\0\u3384\0\u33d8\0\u342c\0\u3480\0\u34d4\0\u3528"+
    "\0\u357c\0\u35d0\0\u04ec\0\u3624\0\u3678\0\u36cc\0\u3720\0\u3774"+
    "\0\u37c8\0\u381c\0\u3870\0\u38c4\0\u3918\0\u396c\0\u39c0\0\u3a14"+
    "\0\u3a68\0\u3abc\0\u3b10\0\u3b64\0\u3bb8\0\u3c0c\0\u3c60\0\u3cb4"+
    "\0\u3d08\0\u3d5c\0\u3db0\0\u3e04\0\u3e58\0\u3eac\0\u3f00\0\u3f54"+
    "\0\u3fa8\0\124\0\124\0\u3ffc\0\u4050\0\u40a4\0\u40f8\0\u414c"+
    "\0\u41a0\0\u41f4\0\124\0\124\0\u4248\0\u429c\0\u42f0\0\u4344"+
    "\0\u4398\0\u43ec\0\u4440\0\u4494\0\u44e8\0\u453c\0\u4590\0\u45e4"+
    "\0\u4638\0\u468c\0\u46e0\0\u4734\0\u04ec\0\u4788\0\u47dc\0\u4830"+
    "\0\u4884\0\u48d8\0\u492c\0\u4980\0\u49d4\0\u4a28\0\u4a7c\0\u4ad0"+
    "\0\u4b24\0\u4b78\0\u4bcc\0\u4c20\0\u4c74\0\u4cc8\0\u4d1c\0\u4d70"+
    "\0\u4dc4\0\u4e18\0\u4e6c\0\u4ec0\0\u4f14\0\u4f68\0\u4fbc\0\u5010"+
    "\0\u5064\0\u50b8\0\u510c\0\u5160\0\u51b4\0\u5208\0\124\0\124"+
    "\0\u525c\0\u52b0\0\124\0\124\0\u5304\0\u5358\0\u53ac\0\u5400"+
    "\0\u5454\0\u54a8\0\u54fc\0\u5550\0\u55a4\0\u55f8\0\u564c\0\u56a0"+
    "\0\u56f4\0\u5748\0\u579c\0\u57f0\0\u5844\0\u5898\0\u58ec\0\u5940"+
    "\0\u5994\0\u59e8\0\u5a3c\0\u5a90\0\u5ae4\0\u5b38\0\u5b8c\0\u5be0"+
    "\0\u5c34\0\u5c88\0\u5cdc\0\u5d30\0\124\0\u5d84\0\u5dd8\0\u5e2c"+
    "\0\124\0\u5e80\0\u5ed4\0\u5f28\0\u5f7c\0\u5fd0\0\u6024\0\u6078"+
    "\0\u60cc\0\u6120\0\u6174\0\u61c8\0\u621c\0\u6270\0\u62c4\0\u6318"+
    "\0\u636c\0\u63c0\0\u6414\0\u6468";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[332];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\2\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\10\1\14\1\10\1\15"+
    "\1\16\2\17\2\14\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\2\25\1\36\1\37\1\25\1\40\1\41\1\25"+
    "\1\42\1\43\1\44\1\25\1\45\1\46\1\25\1\47"+
    "\1\25\1\14\1\2\1\14\1\10\2\25\1\50\1\51"+
    "\1\52\1\53\1\54\1\25\1\55\1\56\1\25\1\57"+
    "\1\25\1\60\1\61\1\62\1\25\1\63\1\64\1\25"+
    "\1\65\3\25\1\66\1\67\125\0\2\3\1\0\2\3"+
    "\124\0\1\70\115\0\7\71\1\72\57\71\1\73\34\71"+
    "\23\0\2\74\7\0\6\74\31\0\6\74\23\0\2\7"+
    "\1\0\121\7\13\0\1\67\133\0\2\75\120\0\1\14"+
    "\120\0\1\76\126\0\1\77\1\0\2\17\122\0\2\100"+
    "\3\0\1\70\123\0\1\70\161\0\1\101\60\0\2\25"+
    "\7\0\32\25\4\0\30\25\25\0\2\25\7\0\13\25"+
    "\1\102\16\25\4\0\30\25\25\0\2\25\7\0\24\25"+
    "\1\103\5\25\4\0\30\25\25\0\2\25\7\0\16\25"+
    "\1\104\2\25\1\105\10\25\4\0\30\25\25\0\2\25"+
    "\7\0\13\25\1\106\16\25\4\0\30\25\25\0\2\25"+
    "\7\0\16\25\1\107\13\25\4\0\30\25\25\0\2\25"+
    "\7\0\21\25\1\110\10\25\4\0\30\25\25\0\2\25"+
    "\7\0\16\25\1\111\13\25\4\0\30\25\25\0\2\25"+
    "\7\0\5\25\1\112\24\25\4\0\30\25\25\0\2\25"+
    "\7\0\10\25\1\113\21\25\4\0\30\25\25\0\2\25"+
    "\7\0\16\25\1\114\5\25\1\115\5\25\4\0\30\25"+
    "\25\0\2\25\7\0\17\25\1\116\12\25\4\0\30\25"+
    "\25\0\2\25\7\0\24\25\1\117\5\25\4\0\30\25"+
    "\25\0\2\25\7\0\4\25\1\120\25\25\4\0\30\25"+
    "\25\0\2\25\7\0\1\121\3\25\1\122\5\25\1\123"+
    "\17\25\4\0\30\25\25\0\2\25\7\0\1\124\3\25"+
    "\1\125\25\25\4\0\30\25\25\0\2\25\7\0\4\25"+
    "\1\126\25\25\4\0\30\25\25\0\2\25\7\0\7\25"+
    "\1\127\22\25\4\0\30\25\25\0\2\25\7\0\4\25"+
    "\1\130\25\25\4\0\30\25\25\0\2\25\7\0\32\25"+
    "\4\0\1\25\1\131\14\25\1\132\11\25\25\0\2\25"+
    "\7\0\32\25\4\0\16\25\1\133\11\25\25\0\2\25"+
    "\7\0\32\25\4\0\20\25\1\134\7\25\25\0\2\25"+
    "\7\0\32\25\4\0\13\25\1\135\14\25\25\0\2\25"+
    "\7\0\32\25\4\0\16\25\1\136\11\25\25\0\2\25"+
    "\7\0\32\25\4\0\5\25\1\137\22\25\25\0\2\25"+
    "\7\0\32\25\4\0\15\25\1\112\12\25\25\0\2\25"+
    "\7\0\32\25\4\0\1\25\1\140\26\25\25\0\2\25"+
    "\7\0\32\25\4\0\23\25\1\141\4\25\25\0\2\25"+
    "\7\0\32\25\4\0\17\25\1\142\1\143\7\25\25\0"+
    "\2\25\7\0\32\25\4\0\16\25\1\144\11\25\25\0"+
    "\2\25\7\0\32\25\4\0\17\25\1\145\2\25\1\146"+
    "\5\25\25\0\2\25\7\0\32\25\4\0\5\25\1\147"+
    "\22\25\25\0\2\25\7\0\32\25\4\0\10\25\1\150"+
    "\1\151\16\25\124\0\1\67\1\0\2\71\3\0\117\71"+
    "\23\0\2\152\7\0\6\152\31\0\6\152\42\0\1\153"+
    "\3\0\2\154\77\0\16\76\1\155\105\76\23\0\2\156"+
    "\116\0\1\157\3\0\2\160\124\0\1\161\1\0\1\162"+
    "\117\0\2\25\7\0\1\163\23\25\1\164\5\25\4\0"+
    "\30\25\25\0\2\25\7\0\21\25\1\165\10\25\4\0"+
    "\30\25\25\0\2\25\7\0\23\25\1\166\1\167\5\25"+
    "\4\0\30\25\25\0\2\25\7\0\16\25\1\170\13\25"+
    "\4\0\30\25\25\0\2\25\7\0\22\25\1\171\7\25"+
    "\4\0\30\25\25\0\2\25\7\0\21\25\1\112\10\25"+
    "\4\0\30\25\25\0\2\25\7\0\4\25\1\172\25\25"+
    "\4\0\30\25\25\0\2\25\7\0\21\25\1\173\10\25"+
    "\4\0\30\25\25\0\2\25\7\0\15\25\1\174\14\25"+
    "\4\0\30\25\25\0\2\25\7\0\15\25\1\175\14\25"+
    "\4\0\30\25\25\0\2\25\7\0\13\25\1\176\16\25"+
    "\4\0\30\25\25\0\2\25\7\0\4\25\1\177\25\25"+
    "\4\0\30\25\25\0\2\25\7\0\21\25\1\200\10\25"+
    "\4\0\30\25\25\0\2\25\7\0\3\25\1\201\26\25"+
    "\4\0\30\25\25\0\2\25\7\0\15\25\1\202\14\25"+
    "\4\0\30\25\25\0\2\25\7\0\2\25\1\203\10\25"+
    "\1\204\16\25\4\0\30\25\25\0\2\25\7\0\30\25"+
    "\1\201\1\25\4\0\30\25\25\0\2\25\7\0\1\25"+
    "\1\205\30\25\4\0\30\25\25\0\2\25\7\0\27\25"+
    "\1\206\2\25\4\0\30\25\25\0\2\25\7\0\21\25"+
    "\1\207\10\25\4\0\30\25\25\0\2\25\7\0\10\25"+
    "\1\210\21\25\4\0\30\25\25\0\2\25\7\0\13\25"+
    "\1\211\16\25\4\0\30\25\25\0\2\25\7\0\32\25"+
    "\4\0\3\25\1\212\24\25\25\0\2\25\7\0\32\25"+
    "\4\0\20\25\1\213\7\25\25\0\2\25\7\0\32\25"+
    "\4\0\13\25\1\214\1\25\1\215\2\25\1\216\7\25"+
    "\25\0\2\25\7\0\32\25\4\0\1\25\1\217\26\25"+
    "\25\0\2\25\7\0\32\25\4\0\5\25\1\220\22\25"+
    "\25\0\2\25\7\0\32\25\4\0\15\25\1\221\12\25"+
    "\25\0\2\25\7\0\32\25\4\0\11\25\1\222\16\25"+
    "\25\0\2\25\7\0\32\25\4\0\2\25\1\223\25\25"+
    "\25\0\2\25\7\0\32\25\4\0\14\25\1\224\13\25"+
    "\25\0\2\25\7\0\32\25\4\0\22\25\1\225\5\25"+
    "\25\0\2\25\7\0\32\25\4\0\11\25\1\226\16\25"+
    "\25\0\2\25\7\0\32\25\4\0\11\25\1\227\16\25"+
    "\25\0\2\25\7\0\32\25\4\0\5\25\1\230\22\25"+
    "\25\0\2\25\7\0\32\25\4\0\20\25\1\231\5\25"+
    "\1\232\1\25\25\0\2\25\7\0\32\25\4\0\25\25"+
    "\1\233\2\25\25\0\2\25\7\0\32\25\4\0\16\25"+
    "\1\234\11\25\25\0\2\25\7\0\32\25\4\0\4\25"+
    "\1\235\23\25\25\0\2\236\7\0\6\236\31\0\6\236"+
    "\46\0\2\237\116\0\1\153\3\0\2\240\77\0\16\76"+
    "\1\155\3\76\1\241\101\76\23\0\2\242\116\0\1\157"+
    "\3\0\2\243\113\0\1\244\1\245\53\0\1\246\3\0"+
    "\1\247\4\0\1\250\10\0\1\251\6\0\1\252\25\0"+
    "\1\253\2\0\1\162\117\0\2\25\7\0\2\25\1\254"+
    "\27\25\4\0\30\25\25\0\2\25\7\0\4\25\1\201"+
    "\25\25\4\0\30\25\25\0\2\25\7\0\22\25\1\255"+
    "\7\25\4\0\30\25\25\0\2\25\7\0\23\25\1\256"+
    "\6\25\4\0\30\25\25\0\2\25\7\0\1\25\1\257"+
    "\30\25\4\0\30\25\25\0\2\25\7\0\17\25\1\260"+
    "\12\25\4\0\30\25\25\0\2\25\7\0\4\25\1\112"+
    "\25\25\4\0\30\25\25\0\2\25\7\0\4\25\1\261"+
    "\25\25\4\0\30\25\25\0\2\25\7\0\10\25\1\262"+
    "\21\25\4\0\30\25\25\0\2\25\7\0\4\25\1\263"+
    "\25\25\4\0\30\25\25\0\2\25\7\0\16\25\1\112"+
    "\13\25\4\0\30\25\25\0\2\25\7\0\23\25\1\264"+
    "\6\25\4\0\30\25\25\0\2\25\7\0\15\25\1\260"+
    "\14\25\4\0\30\25\25\0\2\25\7\0\17\25\1\265"+
    "\12\25\4\0\30\25\25\0\2\25\7\0\22\25\1\266"+
    "\7\25\4\0\30\25\25\0\2\25\7\0\23\25\1\267"+
    "\6\25\4\0\30\25\25\0\2\25\7\0\4\25\1\270"+
    "\25\25\4\0\30\25\25\0\2\25\7\0\13\25\1\171"+
    "\16\25\4\0\30\25\25\0\2\25\7\0\23\25\1\112"+
    "\6\25\4\0\30\25\25\0\2\25\7\0\23\25\1\271"+
    "\6\25\4\0\30\25\25\0\2\25\7\0\13\25\1\171"+
    "\7\25\1\164\6\25\4\0\30\25\25\0\2\25\7\0"+
    "\13\25\1\272\16\25\4\0\30\25\25\0\2\25\7\0"+
    "\32\25\4\0\12\25\1\273\15\25\25\0\2\25\7\0"+
    "\32\25\4\0\4\25\1\274\23\25\25\0\2\25\7\0"+
    "\32\25\4\0\16\25\1\275\11\25\25\0\2\25\7\0"+
    "\32\25\4\0\22\25\1\276\5\25\25\0\2\25\7\0"+
    "\32\25\4\0\20\25\1\277\7\25\25\0\2\25\7\0"+
    "\32\25\4\0\24\25\1\112\3\25\25\0\2\25\7\0"+
    "\32\25\4\0\14\25\1\300\13\25\25\0\2\25\7\0"+
    "\32\25\4\0\22\25\1\301\5\25\25\0\2\25\7\0"+
    "\32\25\4\0\7\25\1\302\20\25\25\0\2\25\7\0"+
    "\32\25\4\0\5\25\1\303\22\25\25\0\2\25\7\0"+
    "\32\25\4\0\2\25\1\274\25\25\25\0\2\25\7\0"+
    "\32\25\4\0\11\25\1\304\16\25\25\0\2\25\7\0"+
    "\32\25\4\0\5\25\1\305\22\25\25\0\2\25\7\0"+
    "\32\25\4\0\15\25\1\306\12\25\25\0\2\25\7\0"+
    "\32\25\4\0\3\25\1\307\24\25\25\0\2\25\7\0"+
    "\32\25\4\0\11\25\1\310\16\25\25\0\2\25\7\0"+
    "\32\25\4\0\13\25\1\311\14\25\25\0\2\25\7\0"+
    "\32\25\4\0\22\25\1\312\5\25\25\0\2\25\7\0"+
    "\32\25\4\0\1\313\27\25\25\0\2\25\7\0\32\25"+
    "\4\0\22\25\1\314\5\25\25\0\2\315\7\0\6\315"+
    "\31\0\6\315\42\0\1\316\3\0\2\317\116\0\1\153"+
    "\123\0\1\320\3\0\2\321\116\0\1\157\120\0\1\244"+
    "\53\0\1\322\50\0\1\245\52\0\1\323\124\0\1\324"+
    "\125\0\1\325\127\0\1\326\117\0\1\327\3\0\1\330"+
    "\6\0\1\331\5\0\1\332\77\0\1\333\31\0\1\252"+
    "\25\0\1\253\43\0\1\334\56\0\2\25\7\0\12\25"+
    "\1\201\17\25\4\0\30\25\25\0\2\25\7\0\10\25"+
    "\1\335\21\25\4\0\30\25\25\0\2\25\7\0\4\25"+
    "\1\336\25\25\4\0\30\25\25\0\2\25\7\0\13\25"+
    "\1\174\16\25\4\0\30\25\25\0\2\25\7\0\32\25"+
    "\4\0\1\337\27\25\25\0\2\25\7\0\15\25\1\201"+
    "\14\25\4\0\30\25\25\0\2\25\7\0\31\25\1\340"+
    "\4\0\30\25\25\0\2\25\7\0\10\25\1\341\21\25"+
    "\4\0\30\25\25\0\2\25\7\0\13\25\1\164\16\25"+
    "\4\0\30\25\25\0\2\25\7\0\32\25\4\0\1\342"+
    "\27\25\25\0\2\25\7\0\10\25\1\343\21\25\4\0"+
    "\30\25\25\0\2\25\7\0\2\25\1\344\27\25\4\0"+
    "\30\25\25\0\2\25\7\0\10\25\1\345\21\25\4\0"+
    "\30\25\25\0\2\25\7\0\16\25\1\346\13\25\4\0"+
    "\30\25\25\0\2\25\7\0\32\25\4\0\7\25\1\347"+
    "\20\25\25\0\2\25\7\0\32\25\4\0\5\25\1\275"+
    "\22\25\25\0\2\25\7\0\32\25\4\0\20\25\1\112"+
    "\7\25\25\0\2\25\7\0\32\25\4\0\5\25\1\350"+
    "\22\25\25\0\2\25\7\0\32\25\4\0\5\25\1\351"+
    "\22\25\25\0\2\25\7\0\32\25\4\0\5\25\1\352"+
    "\22\25\7\0\1\353\15\0\2\25\7\0\32\25\4\0"+
    "\30\25\25\0\2\25\7\0\32\25\4\0\10\25\1\354"+
    "\17\25\25\0\2\25\7\0\32\25\4\0\13\25\1\355"+
    "\14\25\25\0\2\25\7\0\32\25\4\0\16\25\1\356"+
    "\11\25\25\0\2\25\7\0\32\25\4\0\15\25\1\357"+
    "\12\25\25\0\2\25\7\0\32\25\4\0\22\25\1\360"+
    "\5\25\25\0\2\25\7\0\32\25\4\0\11\25\1\361"+
    "\16\25\25\0\2\25\7\0\32\25\4\0\15\25\1\362"+
    "\12\25\25\0\2\25\7\0\32\25\4\0\5\25\1\363"+
    "\22\25\7\0\1\364\15\0\2\25\7\0\32\25\4\0"+
    "\30\25\25\0\2\25\7\0\32\25\4\0\11\25\1\365"+
    "\16\25\25\0\2\25\7\0\32\25\4\0\10\25\1\355"+
    "\17\25\25\0\2\366\7\0\6\366\31\0\6\366\46\0"+
    "\2\367\116\0\1\316\3\0\2\370\122\0\2\371\116\0"+
    "\1\320\3\0\2\372\124\0\1\373\212\0\1\324\102\0"+
    "\1\374\126\0\1\375\137\0\1\376\114\0\1\377\113\0"+
    "\1\u0100\53\0\2\25\7\0\25\25\1\171\4\25\4\0"+
    "\30\25\25\0\2\25\7\0\3\25\1\263\26\25\4\0"+
    "\30\25\25\0\2\25\7\0\20\25\1\u0101\11\25\4\0"+
    "\30\25\25\0\2\25\7\0\16\25\1\u0102\13\25\4\0"+
    "\30\25\25\0\2\25\7\0\17\25\1\u0103\12\25\4\0"+
    "\30\25\25\0\2\25\7\0\22\25\1\u0104\7\25\4\0"+
    "\30\25\25\0\2\25\7\0\16\25\1\u0105\13\25\4\0"+
    "\30\25\25\0\2\25\7\0\23\25\1\260\6\25\4\0"+
    "\30\25\25\0\2\25\7\0\2\25\1\u0106\27\25\4\0"+
    "\30\25\25\0\2\25\7\0\26\25\1\201\3\25\4\0"+
    "\30\25\25\0\2\25\7\0\32\25\4\0\20\25\1\u0107"+
    "\7\25\25\0\2\25\7\0\32\25\4\0\15\25\1\354"+
    "\12\25\25\0\2\25\7\0\32\25\4\0\3\25\1\354"+
    "\24\25\25\0\2\25\7\0\32\25\4\0\15\25\1\u0108"+
    "\12\25\102\0\1\u0109\46\0\2\25\7\0\32\25\4\0"+
    "\22\25\1\355\5\25\25\0\2\25\7\0\32\25\4\0"+
    "\15\25\1\u010a\12\25\25\0\2\25\7\0\32\25\4\0"+
    "\22\25\1\u010b\5\25\25\0\2\25\7\0\27\25\2\355"+
    "\1\25\4\0\30\25\25\0\2\25\7\0\32\25\4\0"+
    "\1\25\1\u010c\26\25\25\0\2\25\7\0\32\25\4\0"+
    "\7\25\1\112\20\25\25\0\2\25\7\0\32\25\4\0"+
    "\21\25\1\112\6\25\115\0\1\u010d\33\0\2\25\7\0"+
    "\32\25\4\0\21\25\1\u010e\6\25\25\0\2\u010f\7\0"+
    "\6\u010f\31\0\6\u010f\40\0\1\u0110\5\0\2\u0111\116\0"+
    "\1\316\127\0\2\u0112\4\0\1\u0113\111\0\1\320\174\0"+
    "\1\u0114\145\0\1\u0115\36\0\1\u0116\201\0\1\u0117\125\0"+
    "\1\u0118\130\0\1\u0119\34\0\2\25\7\0\24\25\1\u011a"+
    "\5\25\4\0\30\25\25\0\2\25\7\0\15\25\1\u011b"+
    "\14\25\4\0\30\25\25\0\2\25\7\0\13\25\1\u011c"+
    "\16\25\4\0\30\25\25\0\2\25\7\0\4\25\1\u011d"+
    "\25\25\4\0\30\25\25\0\2\25\7\0\15\25\1\112"+
    "\14\25\4\0\30\25\25\0\2\25\7\0\1\u011e\31\25"+
    "\4\0\30\25\25\0\2\25\7\0\32\25\4\0\16\25"+
    "\1\u011f\11\25\25\0\2\25\7\0\32\25\4\0\22\25"+
    "\1\u010a\5\25\75\0\1\u0120\53\0\2\25\7\0\32\25"+
    "\4\0\21\25\1\355\6\25\25\0\2\25\7\0\32\25"+
    "\4\0\1\25\1\u0121\26\25\25\0\2\25\7\0\32\25"+
    "\4\0\13\25\1\112\14\25\105\0\1\u0122\43\0\2\25"+
    "\7\0\32\25\4\0\1\u0123\27\25\17\0\1\u0110\5\0"+
    "\2\u0124\122\0\2\u0125\4\0\1\u0113\206\0\1\u0126\77\0"+
    "\1\322\143\0\1\u0127\112\0\1\u0128\44\0\1\u0129\4\0"+
    "\1\u012a\121\0\2\25\7\0\4\25\1\u012b\25\25\4\0"+
    "\30\25\25\0\2\25\7\0\23\25\1\u0106\6\25\4\0"+
    "\30\25\25\0\2\25\7\0\4\25\1\260\25\25\4\0"+
    "\30\25\25\0\2\25\7\0\21\25\1\u012c\10\25\4\0"+
    "\30\25\25\0\2\25\7\0\13\25\1\112\16\25\4\0"+
    "\30\25\25\0\2\25\7\0\32\25\4\0\23\25\1\u012d"+
    "\4\25\110\0\1\u012e\40\0\2\25\7\0\32\25\4\0"+
    "\22\25\1\u012f\5\25\123\0\1\u0130\25\0\2\25\7\0"+
    "\32\25\4\0\22\25\1\u0131\5\25\17\0\1\u0110\137\0"+
    "\1\u0113\117\0\1\u0132\213\0\1\u0133\33\0\1\u0134\121\0"+
    "\2\u012a\122\0\2\u012a\43\0\1\u0135\56\0\2\25\7\0"+
    "\22\25\1\203\7\25\4\0\30\25\25\0\2\25\7\0"+
    "\10\25\1\35\21\25\4\0\30\25\25\0\2\25\7\0"+
    "\32\25\4\0\15\25\1\u0136\12\25\105\0\1\u0137\43\0"+
    "\2\25\7\0\32\25\4\0\11\25\1\u0138\16\25\101\0"+
    "\1\u0139\47\0\2\25\7\0\32\25\4\0\10\25\1\u013a"+
    "\17\25\72\0\1\334\146\0\1\u013b\100\0\1\323\56\0"+
    "\2\25\7\0\32\25\4\0\4\25\1\u013c\23\25\107\0"+
    "\1\u013d\41\0\2\25\7\0\32\25\4\0\16\25\1\u013e"+
    "\11\25\25\0\2\25\7\0\32\25\4\0\1\25\1\u013f"+
    "\26\25\27\0\1\u0140\103\0\1\u0141\15\0\2\25\7\0"+
    "\32\25\4\0\30\25\122\0\1\u0139\26\0\2\25\7\0"+
    "\32\25\4\0\15\25\1\355\12\25\25\0\2\25\7\0"+
    "\32\25\4\0\22\25\1\u0142\5\25\72\0\1\333\130\0"+
    "\1\u0143\51\0\2\25\7\0\32\25\4\0\1\u0144\27\25"+
    "\112\0\1\u0145\36\0\2\25\7\0\32\25\4\0\17\25"+
    "\1\u0146\10\25\107\0\1\u0147\41\0\2\25\7\0\32\25"+
    "\4\0\16\25\1\u0148\11\25\112\0\1\u0149\36\0\2\25"+
    "\7\0\32\25\4\0\12\25\1\u014a\15\25\114\0\1\u0139"+
    "\34\0\2\25\7\0\32\25\4\0\5\25\1\u014b\22\25"+
    "\25\0\2\25\7\0\32\25\4\0\14\25\1\u014c\13\25"+
    "\25\0\2\25\7\0\32\25\4\0\16\25\1\56\11\25"+
    "\2\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[25788];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\1\11\2\1\2\11\6\1\1\11"+
    "\43\1\2\11\1\0\1\11\7\0\50\1\4\0\1\1"+
    "\4\0\53\1\3\0\1\11\12\0\41\1\5\0\2\11"+
    "\7\0\2\11\16\1\1\0\10\1\1\0\1\1\13\0"+
    "\10\1\1\0\3\1\1\0\1\1\2\11\2\0\2\11"+
    "\5\0\6\1\1\0\1\1\1\0\1\1\7\0\3\1"+
    "\1\0\1\1\1\0\1\1\3\0\1\11\1\1\1\0"+
    "\1\1\1\11\1\1\1\0\1\1\1\0\2\1\2\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\3\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[332];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */

private List<ErrorLexico> errores = new ArrayList<>();

  public List<ErrorLexico> getErrores() {
      return errores;
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
  //constructor
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public com.example.proyecto1_compi1.models.Token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
              {
                return null;
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { errores.add(
                                                new ErrorLexico(
                                                        yytext(),
                                                        yyline+1,
                                                        yycolumn+1,
                                                        "Lexico",
                                                        "Caracter no reconocido"
                                                )
                                                );
            }
          // fall through
          case 28: break;
          case 2:
            { /*ignorar termporalmente*/
            }
          // fall through
          case 29: break;
          case 3:
            { /*comentario de una linea*/
            }
          // fall through
          case 30: break;
          case 4:
            { return new Token("OP_ARITMETICO", yytext(), yyline+1, yycolumn+1);
            }
          // fall through
          case 31: break;
          case 5:
            { return new Token("LPAREN", yytext(), yyline+1, yycolumn+1);
            }
          // fall through
          case 32: break;
          case 6:
            { return new Token("RPAREN", yytext(), yyline+1, yycolumn+1);
            }
          // fall through
          case 33: break;
          case 7:
            { return new Token("SIMBOLO", yytext(), yyline+1, yycolumn+1);
            }
          // fall through
          case 34: break;
          case 8:
            { return new Token("NUMERO", yytext(), yyline+1, yycolumn+1);
            }
          // fall through
          case 35: break;
          case 9:
            { return new Token("OP_COMPARACION", yytext(), yyline+1, yycolumn+1);
            }
          // fall through
          case 36: break;
          case 10:
            { return new Token("COMODIN", yytext(), yyline+1, yycolumn+1);
            }
          // fall through
          case 37: break;
          case 11:
            { return new Token("ID", yytext(), yyline+1, yycolumn+1);
            }
          // fall through
          case 38: break;
          case 12:
            { return new Token("OP_LOGICO", yytext(), yyline+1, yycolumn+1);
            }
          // fall through
          case 39: break;
          case 13:
            { return new Token("CADENA", yytext(), yyline+1, yycolumn+1);
            }
          // fall through
          case 40: break;
          case 14:
            { return new Token("PALABRA RESERVADA", yytext(), yyline+1, yycolumn+1);
            }
          // fall through
          case 41: break;
          case 15:
            { return new Token("COLOR_BASE", yytext(), yyline+1, yycolumn+1);
            }
          // fall through
          case 42: break;
          case 16:
            { /* comentario multilínea */
            }
          // fall through
          case 43: break;
          case 17:
            { return new Token("PROPIEDAD", yytext(), yyline+1, yycolumn+1);
            }
          // fall through
          case 44: break;
          case 18:
            { return new Token("EMOJI_SAD", yytext(), yyline+1, yycolumn+1);
            }
          // fall through
          case 45: break;
          case 19:
            { return new Token("EMOJI_SMILE", yytext(), yyline+1, yycolumn+1);
            }
          // fall through
          case 46: break;
          case 20:
            { return new Token("EMOJI_SERIOUS", yytext(), yyline+1, yycolumn+1);
            }
          // fall through
          case 47: break;
          case 21:
            { return new Token("EMOJI_HEART", yytext(), yyline+1, yycolumn+1);
            }
          // fall through
          case 48: break;
          case 22:
            { return new Token("CONFIG", yytext(), yyline+1, yycolumn+1);
            }
          // fall through
          case 49: break;
          case 23:
            { return new Token("HEX_COLOR", yytext(), yyline+1, yycolumn+1);
            }
          // fall through
          case 50: break;
          case 24:
            { return new Token("RGB_COLOR", yytext(), yyline+1, yycolumn+1);
            }
          // fall through
          case 51: break;
          case 25:
            { return new Token("HSL_COLOR", yytext(), yyline+1, yycolumn+1);
            }
          // fall through
          case 52: break;
          case 26:
            { return new Token("EMOJI_CAT", yytext(), yyline+1, yycolumn+1);
            }
          // fall through
          case 53: break;
          case 27:
            { return new Token("EMOJI_STAR", yytext(), yyline+1, yycolumn+1);
            }
          // fall through
          case 54: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
