// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: /home/herson/Repositorios Git/Proyecto1_Compi1/Proyecto1_Compi1/app/src/main/Flex/Lexer2.flex

package com.example.proyecto1_compi1.Analizadores;

import java_cup.runtime.Symbol;
import com.example.proyecto1_compi1.models.ErrorLexico;
import java.util.ArrayList;
import java.util.List;


@SuppressWarnings("fallthrough")
public class Lexer2 implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int METADATA = 2;
  public static final int STRING = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2, 2
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\1\u0400\266\u0200\10\u0500\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\2\1\1\2\2\1\22\0\1\1\1\0\1\3"+
    "\1\4\4\0\1\5\1\6\2\0\1\7\1\10\1\11"+
    "\1\12\12\13\2\0\1\14\1\15\1\16\2\0\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\0\1\30\1\31\1\32\1\33\1\34\1\35\1\0"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\0\1\47\2\0\1\50\1\0\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\0"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\0\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\51\1\0\1\52\7\0\1\2\252\0\2\27\115\0"+
    "\1\37\u01a8\0\2\2\u0100\0\1\30\325\0\u0100\2";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\3\1\1\1\4\1\5\1\6"+
    "\2\1\1\7\1\1\1\10\15\1\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\3\0\1\17\36\0\1\20\1\21"+
    "\1\22\1\0\1\7\43\0\1\23\1\0\1\24\3\0"+
    "\1\25\34\0\1\26\6\0\1\27\1\30\42\0\1\31"+
    "\4\0\1\32\4\0\1\33\22\0\1\34\2\0\1\35"+
    "\1\0\1\36\5\0\1\37\1\0\1\40\1\41\1\0"+
    "\1\42\2\0\1\43\1\44\1\0\1\45\1\0\1\46"+
    "\1\0\1\47\6\0\1\50\2\0\1\51\6\0\1\52"+
    "\1\53\1\0\1\54\10\0\1\55\1\56\2\0\1\57"+
    "\5\0\1\60\3\0\1\61\4\0\1\62\1\0\1\63"+
    "\1\64\2\0\1\65\3\0\1\66\1\67\1\0\1\70"+
    "\2\0\1\71\1\0\1\72\1\73\1\74\2\0\1\75"+
    "\3\0\1\76\4\0\1\77";

  private static int [] zzUnpackAction() {
    int [] result = new int[322];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\126\0\201\0\254\0\201\0\327\0\201"+
    "\0\201\0\201\0\u0102\0\u012d\0\u0158\0\u0183\0\201\0\u01ae"+
    "\0\u01d9\0\u0204\0\u022f\0\u025a\0\u0285\0\u02b0\0\u02db\0\u0306"+
    "\0\u0331\0\u035c\0\u0387\0\u03b2\0\201\0\201\0\u03dd\0\u0408"+
    "\0\u0433\0\201\0\u045e\0\u0489\0\u04b4\0\201\0\u04df\0\u050a"+
    "\0\u0535\0\u0560\0\u058b\0\u05b6\0\u05e1\0\u060c\0\u0637\0\u0662"+
    "\0\u068d\0\u06b8\0\u06e3\0\u070e\0\u0739\0\u0764\0\u078f\0\u07ba"+
    "\0\u07e5\0\u0810\0\u083b\0\u0866\0\u0891\0\u08bc\0\u08e7\0\u0912"+
    "\0\u093d\0\u0968\0\u0993\0\u09be\0\201\0\201\0\201\0\u09e9"+
    "\0\u04df\0\u0a14\0\u0a3f\0\u0a6a\0\u0a95\0\u0ac0\0\u0aeb\0\u0b16"+
    "\0\u0b41\0\u0b6c\0\u0b97\0\u0bc2\0\u0bed\0\u0c18\0\u0c43\0\u0c6e"+
    "\0\u0c99\0\u0cc4\0\u0cef\0\u0d1a\0\u0d45\0\u0d70\0\u0d9b\0\u0dc6"+
    "\0\u0df1\0\u0e1c\0\u0e47\0\u0e72\0\u0e9d\0\u0ec8\0\u0ef3\0\u0f1e"+
    "\0\u0f49\0\u0f74\0\u0f9f\0\u0fca\0\201\0\u0ff5\0\201\0\u1020"+
    "\0\u104b\0\u1076\0\201\0\u10a1\0\u10cc\0\u10f7\0\u1122\0\u114d"+
    "\0\u1178\0\u11a3\0\u11ce\0\u11f9\0\u1224\0\u124f\0\u127a\0\u12a5"+
    "\0\u12d0\0\u12fb\0\u1326\0\u1351\0\u137c\0\u13a7\0\u13d2\0\u13fd"+
    "\0\u1428\0\u1453\0\u147e\0\u14a9\0\u14d4\0\u14ff\0\u152a\0\201"+
    "\0\u1555\0\u1580\0\u15ab\0\u15d6\0\u1601\0\u162c\0\201\0\201"+
    "\0\u1657\0\u1682\0\u16ad\0\u16d8\0\u1703\0\u172e\0\u1759\0\u1784"+
    "\0\u17af\0\u17da\0\u1805\0\u1830\0\u185b\0\u1886\0\u18b1\0\u18dc"+
    "\0\u1907\0\u1932\0\u195d\0\u1988\0\u19b3\0\u19de\0\u1a09\0\u1a34"+
    "\0\u1a5f\0\u1a8a\0\u1ab5\0\u1ae0\0\u1b0b\0\u1b36\0\u1b61\0\u1b8c"+
    "\0\u1bb7\0\u1be2\0\201\0\u1c0d\0\u1c38\0\u1c63\0\u1c8e\0\201"+
    "\0\u1cb9\0\u1ce4\0\u1d0f\0\u1d3a\0\201\0\u1d65\0\u1d90\0\u1dbb"+
    "\0\u1de6\0\u1e11\0\u1e3c\0\u1e67\0\u1e92\0\u1ebd\0\u1ee8\0\u1f13"+
    "\0\u1f3e\0\u1f69\0\u1f94\0\u1fbf\0\u1fea\0\u2015\0\u2040\0\201"+
    "\0\u206b\0\u2096\0\201\0\u20c1\0\201\0\u20ec\0\u2117\0\u2142"+
    "\0\u216d\0\u2198\0\201\0\u21c3\0\201\0\201\0\u21ee\0\201"+
    "\0\u2219\0\u2244\0\201\0\201\0\u226f\0\201\0\u229a\0\201"+
    "\0\u22c5\0\201\0\u22f0\0\u231b\0\u2346\0\u2371\0\u239c\0\u23c7"+
    "\0\201\0\u23f2\0\u241d\0\201\0\u2448\0\u2473\0\u249e\0\u24c9"+
    "\0\u24f4\0\u251f\0\201\0\201\0\u254a\0\201\0\u2575\0\u25a0"+
    "\0\u25cb\0\u25f6\0\u2621\0\u264c\0\u2677\0\u26a2\0\201\0\201"+
    "\0\u26cd\0\u26f8\0\201\0\u2723\0\u274e\0\u2779\0\u27a4\0\u27cf"+
    "\0\201\0\u27fa\0\u2825\0\u2850\0\201\0\u287b\0\u28a6\0\u28d1"+
    "\0\u28fc\0\201\0\u2927\0\201\0\201\0\u2952\0\u297d\0\201"+
    "\0\u29a8\0\u29d3\0\u29fe\0\201\0\201\0\u2a29\0\201\0\u2a54"+
    "\0\u2a7f\0\201\0\u2aaa\0\201\0\201\0\201\0\u2ad5\0\u2b00"+
    "\0\201\0\u2b2b\0\u2b56\0\u2b81\0\201\0\u2bac\0\u2bd7\0\u2c02"+
    "\0\u2c2d\0\201";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[322];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\0\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\4\1\14\1\15\1\16\1\4\1\17\1\4"+
    "\1\20\1\21\1\22\2\4\1\23\1\24\2\4\1\25"+
    "\1\26\2\4\1\27\1\30\1\31\2\4\1\32\1\33"+
    "\1\4\1\34\3\4\1\35\1\36\4\37\1\40\46\37"+
    "\3\41\1\42\43\41\1\43\3\41\54\0\1\5\55\0"+
    "\1\44\6\0\1\45\3\0\6\45\41\0\1\15\55\0"+
    "\1\46\45\0\1\47\1\0\1\15\40\0\1\50\10\0"+
    "\1\51\1\52\4\0\1\53\1\54\1\55\1\56\1\57"+
    "\4\0\1\60\1\61\1\0\1\62\2\0\1\63\1\64"+
    "\43\0\1\65\55\0\1\66\4\0\1\67\45\0\1\70"+
    "\54\0\1\71\50\0\1\72\45\0\1\73\57\0\1\74"+
    "\57\0\1\75\34\0\1\76\46\0\1\77\10\0\1\100"+
    "\45\0\1\101\55\0\1\102\47\0\1\103\27\0\4\37"+
    "\1\0\46\37\4\0\1\104\46\0\3\41\1\0\43\41"+
    "\1\0\3\41\3\0\1\105\43\0\1\106\7\0\1\107"+
    "\61\0\1\110\3\0\6\110\41\0\1\111\40\0\1\50"+
    "\11\0\1\52\60\0\1\112\1\113\1\114\5\0\1\115"+
    "\1\116\1\0\1\117\2\0\1\120\1\121\13\0\1\122"+
    "\5\0\1\123\1\0\1\124\1\0\1\52\56\0\1\125"+
    "\14\0\1\126\52\0\1\127\54\0\1\130\45\0\1\131"+
    "\55\0\1\132\45\0\1\133\64\0\1\134\46\0\1\135"+
    "\40\0\1\136\14\0\1\137\31\0\1\140\3\0\1\141"+
    "\46\0\1\142\21\0\1\143\42\0\1\144\57\0\1\145"+
    "\54\0\1\146\1\147\34\0\1\150\65\0\1\151\47\0"+
    "\1\152\52\0\1\153\55\0\1\154\36\0\1\155\63\0"+
    "\1\156\64\0\1\157\43\0\1\160\43\0\1\161\54\0"+
    "\1\162\25\0\1\163\61\0\1\164\3\0\6\164\62\0"+
    "\1\165\54\0\1\166\45\0\1\167\50\0\1\170\64\0"+
    "\1\171\46\0\1\172\40\0\1\173\14\0\1\174\31\0"+
    "\1\175\34\0\1\122\5\0\1\123\44\0\1\123\11\0"+
    "\1\176\52\0\1\177\60\0\1\200\67\0\1\201\45\0"+
    "\1\202\1\0\1\203\53\0\1\204\41\0\1\205\62\0"+
    "\1\206\52\0\1\207\50\0\1\210\44\0\1\211\50\0"+
    "\1\212\7\0\1\213\66\0\1\214\25\0\1\215\76\0"+
    "\1\216\27\0\1\217\54\0\1\220\63\0\1\221\55\0"+
    "\1\222\53\0\1\223\32\0\1\224\55\0\1\225\56\0"+
    "\1\226\46\0\1\227\63\0\1\230\53\0\1\231\54\0"+
    "\1\232\53\0\1\233\52\0\1\234\43\0\1\235\34\0"+
    "\1\236\3\0\6\236\61\0\1\237\53\0\1\240\41\0"+
    "\1\241\62\0\1\242\50\0\1\243\44\0\1\244\50\0"+
    "\1\245\7\0\1\246\66\0\1\247\25\0\1\250\33\0"+
    "\1\251\5\0\1\252\1\0\1\253\1\0\1\176\40\0"+
    "\1\122\5\0\1\123\3\0\1\177\67\0\1\254\44\0"+
    "\1\255\64\0\1\256\56\0\1\257\47\0\1\260\47\0"+
    "\1\261\60\0\1\262\35\0\1\263\67\0\1\264\45\0"+
    "\1\265\57\0\1\266\35\0\1\267\60\0\1\270\52\0"+
    "\1\271\61\0\1\272\42\0\1\273\60\0\1\274\43\0"+
    "\1\275\46\0\1\276\60\0\1\277\54\0\1\300\65\0"+
    "\1\301\35\0\1\302\71\0\1\303\31\0\1\304\46\0"+
    "\1\305\63\0\1\306\31\0\1\307\3\0\6\307\66\0"+
    "\1\310\47\0\1\311\47\0\1\312\43\0\1\313\67\0"+
    "\1\314\45\0\1\315\57\0\1\316\35\0\1\317\60\0"+
    "\1\320\52\0\1\321\22\0\1\251\5\0\1\252\44\0"+
    "\1\252\11\0\1\322\52\0\1\323\64\0\1\324\50\0"+
    "\1\325\65\0\1\326\37\0\1\327\44\0\1\330\60\0"+
    "\1\331\30\0\1\332\67\0\1\333\63\0\1\334\40\0"+
    "\1\335\64\0\1\336\44\0\1\337\54\0\1\340\52\0"+
    "\1\341\30\0\1\342\66\0\1\343\77\0\1\344\32\0"+
    "\1\345\53\0\1\346\63\0\1\347\41\0\1\350\66\0"+
    "\1\351\34\0\1\352\74\0\1\353\22\0\1\354\3\0"+
    "\6\354\51\0\1\355\45\0\1\356\57\0\1\357\45\0"+
    "\1\360\63\0\1\361\41\0\1\362\63\0\1\363\44\0"+
    "\1\364\54\0\1\365\52\0\1\366\30\0\1\367\7\0"+
    "\1\370\1\0\1\322\2\0\1\371\35\0\1\251\5\0"+
    "\1\252\3\0\1\323\75\0\1\372\52\0\1\373\31\0"+
    "\1\374\70\0\1\375\52\0\1\376\20\0\1\332\22\0"+
    "\1\377\63\0\1\u0100\51\0\1\u0101\56\0\1\u0102\30\0"+
    "\1\u0103\51\0\1\u0104\36\0\1\342\35\0\1\u0105\36\0"+
    "\1\u0106\62\0\1\u0107\42\0\1\u0108\46\0\1\u0109\66\0"+
    "\1\u010a\52\0\1\u010b\54\0\1\u010c\51\0\1\u010d\56\0"+
    "\1\u010e\30\0\1\u010f\52\0\1\u0110\35\0\1\367\14\0"+
    "\1\371\47\0\1\u0111\73\0\1\u0112\25\0\1\u0113\103\0"+
    "\1\u0114\52\0\1\u0115\31\0\1\u0116\64\0\1\u0117\54\0"+
    "\1\u0118\34\0\1\u0119\64\0\1\u011a\63\0\1\u011b\50\0"+
    "\1\u011c\45\0\1\u011d\61\0\1\u011e\52\0\1\u011f\43\0"+
    "\1\u0120\54\0\1\u0121\35\0\1\u0122\35\0\1\367\11\0"+
    "\1\u0111\2\0\1\371\75\0\1\u0123\27\0\1\u0124\52\0"+
    "\1\u0125\66\0\1\u0126\43\0\1\u0127\44\0\1\u0128\103\0"+
    "\1\u0129\23\0\1\u012a\62\0\1\u012b\41\0\1\u012c\52\0"+
    "\1\u012d\57\0\1\u012e\45\0\1\u012f\67\0\1\u0130\46\0"+
    "\1\u0131\40\0\1\u0132\60\0\1\u0133\60\0\1\u0134\45\0"+
    "\1\u0135\44\0\1\u0136\56\0\1\u0137\61\0\1\u0138\36\0"+
    "\1\u0139\36\0\1\u013a\116\0\1\u013b\6\0\1\u013a\17\0"+
    "\1\u013c\46\0\1\u013d\71\0\1\u013e\47\0\1\u013f\55\0"+
    "\1\u0140\54\0\1\u0141\31\0\1\u0142\35\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[11352];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\1\1\1\11\1\1\3\11\4\1\1\11"+
    "\15\1\2\11\3\1\1\11\3\0\1\11\36\0\3\11"+
    "\1\0\1\1\43\0\1\11\1\0\1\11\3\0\1\11"+
    "\34\0\1\11\6\0\2\11\42\0\1\11\4\0\1\11"+
    "\4\0\1\11\22\0\1\11\2\0\1\11\1\0\1\11"+
    "\5\0\1\11\1\0\2\11\1\0\1\11\2\0\2\11"+
    "\1\0\1\11\1\0\1\11\1\0\1\11\6\0\1\11"+
    "\2\0\1\11\6\0\2\11\1\0\1\11\10\0\2\11"+
    "\2\0\1\11\5\0\1\11\3\0\1\11\4\0\1\11"+
    "\1\0\2\11\2\0\1\11\3\0\2\11\1\0\1\11"+
    "\2\0\1\11\1\0\3\11\2\0\1\11\3\0\1\11"+
    "\4\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[322];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private List<ErrorLexico> errores = new ArrayList<>();
    private StringBuilder stringBuffer = new StringBuilder();

    public List<ErrorLexico> getErrores() {
        return errores;
    }

    private Symbol symbol(int type) {
        return new Symbol(type, yyline + 1, yycolumn + 1);
    }

    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline + 1, yycolumn + 1, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer2(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { errores.add(new ErrorLexico(yytext(), yyline + 1, yycolumn + 1, "Lexico", "Caracter no reconocido: '" + yytext() + "'"));
            }
          // fall through
          case 64: break;
          case 2:
            { /* ignorar */
            }
          // fall through
          case 65: break;
          case 3:
            { yybegin(STRING); stringBuffer.setLength(0);
            }
          // fall through
          case 66: break;
          case 4:
            { return symbol(sym2.LPAREN);
            }
          // fall through
          case 67: break;
          case 5:
            { return symbol(sym2.RPAREN);
            }
          // fall through
          case 68: break;
          case 6:
            { return symbol(sym2.COMA);
            }
          // fall through
          case 69: break;
          case 7:
            { return symbol(sym2.NUMERO, yytext());
            }
          // fall through
          case 70: break;
          case 8:
            { return symbol(sym2.TAG_CLOSE);
            }
          // fall through
          case 71: break;
          case 9:
            { return symbol(sym2.LLLAVE);
            }
          // fall through
          case 72: break;
          case 10:
            { return symbol(sym2.RLLAVE);
            }
          // fall through
          case 73: break;
          case 11:
            { /* ignorar contenido de metadatos */
            }
          // fall through
          case 74: break;
          case 12:
            { /* # suelto dentro de metadatos */
            }
          // fall through
          case 75: break;
          case 13:
            { stringBuffer.append(yytext());
            }
          // fall through
          case 76: break;
          case 14:
            { yybegin(YYINITIAL); return symbol(sym2.CADENA, stringBuffer.toString());
            }
          // fall through
          case 77: break;
          case 15:
            { return symbol(sym2.SELF_CLOSE);
            }
          // fall through
          case 78: break;
          case 16:
            { stringBuffer.append("\"");
            }
          // fall through
          case 79: break;
          case 17:
            { stringBuffer.append("\\");
            }
          // fall through
          case 80: break;
          case 18:
            { yybegin(METADATA); return symbol(sym2.TRIPLE_HASH);
            }
          // fall through
          case 81: break;
          case 19:
            { return symbol(sym2.RED);
            }
          // fall through
          case 82: break;
          case 20:
            { return symbol(sym2.SKY);
            }
          // fall through
          case 83: break;
          case 21:
            { yybegin(YYINITIAL); return symbol(sym2.TRIPLE_HASH);
            }
          // fall through
          case 84: break;
          case 22:
            { return symbol(sym2.BLUE);
            }
          // fall through
          case 85: break;
          case 23:
            { return symbol(sym2.LINE_TYPE);
            }
          // fall through
          case 86: break;
          case 24:
            { return symbol(sym2.MONO);
            }
          // fall through
          case 87: break;
          case 25:
            { return symbol(sym2.BLACK);
            }
          // fall through
          case 88: break;
          case 26:
            { return symbol(sym2.GREEN);
            }
          // fall through
          case 89: break;
          case 27:
            { return symbol(sym2.WHITE);
            }
          // fall through
          case 90: break;
          case 28:
            { return symbol(sym2.DROP_TAG);
            }
          // fall through
          case 91: break;
          case 29:
            { return symbol(sym2.LINE_OPEN);
            }
          // fall through
          case 92: break;
          case 30:
            { return symbol(sym2.OPEN_TAG);
            }
          // fall through
          case 93: break;
          case 31:
            { return symbol(sym2.COLOR_ATTR);
            }
          // fall through
          case 94: break;
          case 32:
            { return symbol(sym2.DOTTED);
            }
          // fall through
          case 95: break;
          case 33:
            { return symbol(sym2.DOUBLE_TYPE);
            }
          // fall through
          case 96: break;
          case 34:
            { return symbol(sym2.PURPLE);
            }
          // fall through
          case 97: break;
          case 35:
            { return symbol(sym2.YELLOW);
            }
          // fall through
          case 98: break;
          case 36:
            { return symbol(sym2.HEX_COLOR, yytext());
            }
          // fall through
          case 99: break;
          case 37:
            { return symbol(sym2.DROP_CLOSE);
            }
          // fall through
          case 100: break;
          case 38:
            { return symbol(sym2.LINE_CLOSE);
            }
          // fall through
          case 101: break;
          case 39:
            { return symbol(sym2.OPEN_CLOSE);
            }
          // fall through
          case 102: break;
          case 40:
            { return symbol(sym2.HSL_COLOR, yytext());
            }
          // fall through
          case 103: break;
          case 41:
            { return symbol(sym2.COLOR_TAG);
            }
          // fall through
          case 104: break;
          case 42:
            { return symbol(sym2.STYLE_OPEN);
            }
          // fall through
          case 105: break;
          case 43:
            { return symbol(sym2.TABLE_OPEN);
            }
          // fall through
          case 106: break;
          case 44:
            { return symbol(sym2.CURSIVE);
            }
          // fall through
          case 107: break;
          case 45:
            { return symbol(sym2.STYLE_CLOSE);
            }
          // fall through
          case 108: break;
          case 46:
            { return symbol(sym2.TABLE_CLOSE);
            }
          // fall through
          case 109: break;
          case 47:
            { return symbol(sym2.BORDER_TAG);
            }
          // fall through
          case 110: break;
          case 48:
            { return symbol(sym2.SELECT_TAG);
            }
          // fall through
          case 111: break;
          case 49:
            { return symbol(sym2.VERTICAL);
            }
          // fall through
          case 112: break;
          case 50:
            { return symbol(sym2.SELECT_CLOSE);
            }
          // fall through
          case 113: break;
          case 51:
            { return symbol(sym2.CONTENT_OPEN);
            }
          // fall through
          case 114: break;
          case 52:
            { return symbol(sym2.ELEMENT_OPEN);
            }
          // fall through
          case 115: break;
          case 53:
            { return symbol(sym2.SECTION_OPEN);
            }
          // fall through
          case 116: break;
          case 54:
            { return symbol(sym2.CONTENT_CLOSE);
            }
          // fall through
          case 117: break;
          case 55:
            { return symbol(sym2.ELEMENT_CLOSE);
            }
          // fall through
          case 118: break;
          case 56:
            { return symbol(sym2.SECTION_CLOSE);
            }
          // fall through
          case 119: break;
          case 57:
            { return symbol(sym2.MULTIPLE_TAG);
            }
          // fall through
          case 120: break;
          case 58:
            { return symbol(sym2.HORIZONTAL);
            }
          // fall through
          case 121: break;
          case 59:
            { return symbol(sym2.SANS_SERIF);
            }
          // fall through
          case 122: break;
          case 60:
            { return symbol(sym2.MULTIPLE_CLOSE);
            }
          // fall through
          case 123: break;
          case 61:
            { return symbol(sym2.TEXT_SIZE_TAG);
            }
          // fall through
          case 124: break;
          case 62:
            { return symbol(sym2.FONT_TAG);
            }
          // fall through
          case 125: break;
          case 63:
            { return symbol(sym2.BG_COLOR_TAG);
            }
          // fall through
          case 126: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
