
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.proyecto1_compi1.Analizadores;

import java_cup.runtime.Symbol;
import com.example.proyecto1_compi1.models.ErrorSintactico;
import java.util.*;
import com.example.proyecto1_compi1.models.nodo2.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser2 extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym2.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser2() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser2(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser2(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\103\000\002\002\004\000\002\002\004\000\002\002" +
    "\003\000\002\003\004\000\002\004\003\000\002\004\004" +
    "\000\002\005\003\000\002\005\003\000\002\005\003\000" +
    "\002\005\003\000\002\005\003\000\002\005\003\000\002" +
    "\006\020\000\002\006\016\000\002\026\003\000\002\026" +
    "\003\000\002\032\003\000\002\032\002\000\002\031\005" +
    "\000\002\023\003\000\002\023\002\000\002\022\005\000" +
    "\002\033\002\000\002\033\004\000\002\024\005\000\002" +
    "\024\005\000\002\024\005\000\002\024\005\000\002\024" +
    "\005\000\002\024\012\000\002\027\003\000\002\027\003" +
    "\000\002\027\003\000\002\030\003\000\002\030\003\000" +
    "\002\030\003\000\002\025\003\000\002\025\003\000\002" +
    "\025\011\000\002\025\003\000\002\025\003\000\002\025" +
    "\003\000\002\025\003\000\002\025\003\000\002\025\003" +
    "\000\002\025\003\000\002\025\003\000\002\007\010\000" +
    "\002\010\003\000\002\010\004\000\002\011\005\000\002" +
    "\012\003\000\002\012\004\000\002\013\005\000\002\014" +
    "\011\000\002\014\013\000\002\015\017\000\002\015\021" +
    "\000\002\016\015\000\002\016\017\000\002\017\017\000" +
    "\002\017\021\000\002\017\016\000\002\020\003\000\002" +
    "\020\005\000\002\021\003\000\002\021\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\251\000\020\004\022\005\005\006\021\007\017\010" +
    "\023\011\024\012\011\001\002\000\024\002\ufff6\005\ufff6" +
    "\006\ufff6\007\ufff6\010\ufff6\011\ufff6\012\ufff6\026\ufff6\030" +
    "\ufff6\001\002\000\004\046\225\001\002\000\024\002\ufffa" +
    "\005\ufffa\006\ufffa\007\ufffa\010\ufffa\011\ufffa\012\ufffa\026" +
    "\ufffa\030\ufffa\001\002\000\022\002\ufffd\005\ufffd\006\ufffd" +
    "\007\ufffd\010\ufffd\011\ufffd\012\ufffd\026\ufffd\001\002\000" +
    "\020\002\uffff\005\005\006\021\007\017\010\023\011\024" +
    "\012\011\001\002\000\006\013\051\014\uffed\001\002\000" +
    "\024\002\ufffb\005\ufffb\006\ufffb\007\ufffb\010\ufffb\011\ufffb" +
    "\012\ufffb\026\ufffb\030\ufffb\001\002\000\024\002\ufff8\005" +
    "\ufff8\006\ufff8\007\ufff8\010\ufff8\011\ufff8\012\ufff8\026\ufff8" +
    "\030\ufff8\001\002\000\016\005\005\006\021\007\017\010" +
    "\023\011\024\012\011\001\002\000\024\002\ufff9\005\ufff9" +
    "\006\ufff9\007\ufff9\010\ufff9\011\ufff9\012\ufff9\026\ufff9\030" +
    "\ufff9\001\002\000\024\002\ufff7\005\ufff7\006\ufff7\007\ufff7" +
    "\010\ufff7\011\ufff7\012\ufff7\026\ufff7\030\ufff7\001\002\000" +
    "\004\046\164\001\002\000\004\002\163\001\002\000\004" +
    "\046\152\001\002\000\004\004\151\001\002\000\004\046" +
    "\134\001\002\000\004\046\025\001\002\000\004\041\026" +
    "\001\002\000\004\046\027\001\002\000\004\041\030\001" +
    "\002\000\004\042\031\001\002\000\004\047\033\001\002" +
    "\000\006\041\034\043\035\001\002\000\006\041\uffc2\043" +
    "\uffc2\001\002\000\004\047\133\001\002\000\004\041\036" +
    "\001\002\000\004\042\037\001\002\000\006\043\042\046" +
    "\040\001\002\000\006\041\uffc0\043\uffc0\001\002\000\006" +
    "\041\044\043\045\001\002\000\004\037\043\001\002\000" +
    "\024\002\uffc3\005\uffc3\006\uffc3\007\uffc3\010\uffc3\011\uffc3" +
    "\012\uffc3\026\uffc3\030\uffc3\001\002\000\004\046\132\001" +
    "\002\000\006\037\047\040\046\001\002\000\004\013\051" +
    "\001\002\000\024\002\uffc5\005\uffc5\006\uffc5\007\uffc5\010" +
    "\uffc5\011\uffc5\012\uffc5\026\uffc5\030\uffc5\001\002\000\004" +
    "\024\131\001\002\000\016\025\uffeb\031\uffeb\032\uffeb\033" +
    "\uffeb\034\uffeb\035\uffeb\001\002\000\016\025\056\031\054" +
    "\032\057\033\060\034\061\035\053\001\002\000\004\046" +
    "\117\001\002\000\030\044\104\050\101\051\076\052\103" +
    "\053\077\054\072\055\100\056\105\057\074\060\102\061" +
    "\073\001\002\000\016\025\uffea\031\uffea\032\uffea\033\uffea" +
    "\034\uffea\035\uffea\001\002\000\016\014\uffec\017\uffec\021" +
    "\uffec\022\uffec\023\uffec\024\uffec\001\002\000\030\044\104" +
    "\050\101\051\076\052\103\053\077\054\072\055\100\056" +
    "\105\057\074\060\102\061\073\001\002\000\010\062\066" +
    "\063\070\064\067\001\002\000\004\046\062\001\002\000" +
    "\006\037\064\040\063\001\002\000\016\025\uffe6\031\uffe6" +
    "\032\uffe6\033\uffe6\034\uffe6\035\uffe6\001\002\000\016\025" +
    "\uffe5\031\uffe5\032\uffe5\033\uffe5\034\uffe5\035\uffe5\001\002" +
    "\000\004\037\071\001\002\000\004\037\uffe3\001\002\000" +
    "\004\037\uffe1\001\002\000\004\037\uffe2\001\002\000\016" +
    "\025\uffe7\031\uffe7\032\uffe7\033\uffe7\034\uffe7\035\uffe7\001" +
    "\002\000\004\037\uffd8\001\002\000\004\037\uffd3\001\002" +
    "\000\004\037\uffd5\001\002\000\004\037\114\001\002\000" +
    "\004\037\uffdc\001\002\000\004\037\uffd9\001\002\000\004" +
    "\037\uffd7\001\002\000\004\037\uffdd\001\002\000\004\037" +
    "\uffd4\001\002\000\004\037\uffda\001\002\000\004\046\106" +
    "\001\002\000\004\037\uffd6\001\002\000\004\041\107\001" +
    "\002\000\004\046\110\001\002\000\004\041\111\001\002" +
    "\000\004\046\112\001\002\000\004\045\113\001\002\000" +
    "\004\037\uffdb\001\002\000\016\025\uffe8\031\uffe8\032\uffe8" +
    "\033\uffe8\034\uffe8\035\uffe8\001\002\000\004\037\116\001" +
    "\002\000\016\025\uffe9\031\uffe9\032\uffe9\033\uffe9\034\uffe9" +
    "\035\uffe9\001\002\000\004\041\120\001\002\000\010\065" +
    "\123\066\124\067\121\001\002\000\004\041\uffde\001\002" +
    "\000\004\041\125\001\002\000\004\041\uffe0\001\002\000" +
    "\004\041\uffdf\001\002\000\004\036\126\001\002\000\030" +
    "\044\104\050\101\051\076\052\103\053\077\054\072\055" +
    "\100\056\105\057\074\060\102\061\073\001\002\000\004" +
    "\037\130\001\002\000\016\025\uffe4\031\uffe4\032\uffe4\033" +
    "\uffe4\034\uffe4\035\uffe4\001\002\000\024\002\uffc4\005\uffc4" +
    "\006\uffc4\007\uffc4\010\uffc4\011\uffc4\012\uffc4\026\uffc4\030" +
    "\uffc4\001\002\000\006\041\uffbf\043\uffbf\001\002\000\006" +
    "\041\uffc1\043\uffc1\001\002\000\004\041\135\001\002\000" +
    "\004\046\136\001\002\000\004\041\137\001\002\000\004" +
    "\042\140\001\002\000\004\047\033\001\002\000\006\041" +
    "\034\043\142\001\002\000\004\041\143\001\002\000\004" +
    "\046\144\001\002\000\006\037\146\040\145\001\002\000" +
    "\004\013\051\001\002\000\024\002\uffc7\005\uffc7\006\uffc7" +
    "\007\uffc7\010\uffc7\011\uffc7\012\uffc7\026\uffc7\030\uffc7\001" +
    "\002\000\004\023\150\001\002\000\024\002\uffc6\005\uffc6" +
    "\006\uffc6\007\uffc6\010\uffc6\011\uffc6\012\uffc6\026\uffc6\030" +
    "\uffc6\001\002\000\016\005\ufffe\006\ufffe\007\ufffe\010\ufffe" +
    "\011\ufffe\012\ufffe\001\002\000\004\041\153\001\002\000" +
    "\004\046\154\001\002\000\004\041\155\001\002\000\004" +
    "\047\156\001\002\000\006\037\160\040\157\001\002\000" +
    "\004\013\051\001\002\000\024\002\uffcb\005\uffcb\006\uffcb" +
    "\007\uffcb\010\uffcb\011\uffcb\012\uffcb\026\uffcb\030\uffcb\001" +
    "\002\000\004\021\162\001\002\000\024\002\uffca\005\uffca" +
    "\006\uffca\007\uffca\010\uffca\011\uffca\012\uffca\026\uffca\030" +
    "\uffca\001\002\000\004\002\001\001\002\000\004\041\165" +
    "\001\002\000\004\046\166\001\002\000\004\041\167\001" +
    "\002\000\004\047\170\001\002\000\004\041\171\001\002" +
    "\000\004\042\172\001\002\000\004\047\033\001\002\000" +
    "\006\041\034\043\174\001\002\000\004\041\175\001\002" +
    "\000\004\046\176\001\002\000\006\037\200\040\177\001" +
    "\002\000\004\013\051\001\002\000\024\002\uffc9\005\uffc9" +
    "\006\uffc9\007\uffc9\010\uffc9\011\uffc9\012\uffc9\026\uffc9\030" +
    "\uffc9\001\002\000\004\022\202\001\002\000\024\002\uffc8" +
    "\005\uffc8\006\uffc8\007\uffc8\010\uffc8\011\uffc8\012\uffc8\026" +
    "\uffc8\030\uffc8\001\002\000\020\002\000\005\005\006\021" +
    "\007\017\010\023\011\024\012\011\001\002\000\022\002" +
    "\ufffc\005\ufffc\006\ufffc\007\ufffc\010\ufffc\011\ufffc\012\ufffc" +
    "\026\ufffc\001\002\000\004\014\207\001\002\000\006\014" +
    "\uffee\017\uffee\001\002\000\004\015\210\001\002\000\004" +
    "\016\220\001\002\000\006\015\210\026\213\001\002\000" +
    "\006\015\uffd1\026\uffd1\001\002\000\004\020\215\001\002" +
    "\000\006\015\uffd0\026\uffd0\001\002\000\024\002\uffd2\005" +
    "\uffd2\006\uffd2\007\uffd2\010\uffd2\011\uffd2\012\uffd2\026\uffd2" +
    "\030\uffd2\001\002\000\006\016\220\027\224\001\002\000" +
    "\006\016\uffce\027\uffce\001\002\000\016\005\005\006\021" +
    "\007\017\010\023\011\024\012\011\001\002\000\004\030" +
    "\222\001\002\000\006\016\uffcc\027\uffcc\001\002\000\006" +
    "\016\uffcd\027\uffcd\001\002\000\006\015\uffcf\026\uffcf\001" +
    "\002\000\004\041\226\001\002\000\004\046\227\001\002" +
    "\000\004\041\230\001\002\000\004\046\231\001\002\000" +
    "\004\041\232\001\002\000\004\046\233\001\002\000\006" +
    "\040\235\041\234\001\002\000\006\070\246\071\245\001" +
    "\002\000\010\013\051\014\uffed\017\uffed\001\002\000\006" +
    "\014\240\017\ufff0\001\002\000\004\017\ufff1\001\002\000" +
    "\016\005\005\006\021\007\017\010\023\011\024\012\011" +
    "\001\002\000\004\017\242\001\002\000\024\002\ufff4\005" +
    "\ufff4\006\ufff4\007\ufff4\010\ufff4\011\ufff4\012\ufff4\026\ufff4" +
    "\030\ufff4\001\002\000\020\005\005\006\021\007\017\010" +
    "\023\011\024\012\011\026\244\001\002\000\004\017\uffef" +
    "\001\002\000\004\040\ufff2\001\002\000\004\040\ufff3\001" +
    "\002\000\004\040\250\001\002\000\010\013\051\014\uffed" +
    "\017\uffed\001\002\000\006\014\240\017\ufff0\001\002\000" +
    "\004\017\253\001\002\000\024\002\ufff5\005\ufff5\006\ufff5" +
    "\007\ufff5\010\ufff5\011\ufff5\012\ufff5\026\ufff5\030\ufff5\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\251\000\026\002\017\003\013\004\007\005\006\006" +
    "\011\007\005\014\014\015\012\016\015\017\003\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\020\005\203\006\011\007\005\014\014" +
    "\015\012\016\015\017\003\001\001\000\006\022\205\023" +
    "\204\001\001\000\002\001\001\000\002\001\001\000\022" +
    "\004\202\005\006\006\011\007\005\014\014\015\012\016" +
    "\015\017\003\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\020\031\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\021\040\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\022\047\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\033\051\001\001\000" +
    "\004\024\054\001\001\000\002\001\001\000\004\025\114" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\025" +
    "\074\001\001\000\004\027\064\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\030\121\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\025\126\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\020\140\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\022\146\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\022\160\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\020\172\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\022\200\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\020\005\203\006\011\007\005\014\014\015\012\016" +
    "\015\017\003\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\010\210\011\211\001\001\000" +
    "\006\012\215\013\216\001\001\000\004\011\213\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\013\222\001\001\000\002\001\001" +
    "\000\020\005\220\006\011\007\005\014\014\015\012\016" +
    "\015\017\003\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\026" +
    "\246\001\001\000\006\022\205\023\235\001\001\000\006" +
    "\031\236\032\240\001\001\000\002\001\001\000\022\004" +
    "\242\005\006\006\011\007\005\014\014\015\012\016\015" +
    "\017\003\001\001\000\002\001\001\000\002\001\001\000" +
    "\020\005\203\006\011\007\005\014\014\015\012\016\015" +
    "\017\003\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\022\205\023\250" +
    "\001\001\000\006\031\236\032\251\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser2$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser2$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser2$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private List<ErrorSintactico> erroresSintacticos = new ArrayList<>();

    public void syntax_error(Symbol s) {
        String lexema = (s != null && s.value != null)
                ? s.value.toString()
                : (s != null ? symbl_name_from_id(s.sym) : "desconocido");

        int linea   = (s != null) ? s.left  : 0;
        int columna = (s != null) ? s.right : 0;

        StringBuilder descripcion = new StringBuilder();
        descripcion.append("Se encontró '").append(lexema).append("'. ");

        if (expected_token_ids().isEmpty()) {
            descripcion.append("No se esperaba ningún símbolo.");
        } else {
            descripcion.append("Se esperaba: ");
            for (Integer id : expected_token_ids()) {
                String nombre = symbl_name_from_id(id);
                if (!nombre.equals("error")) {
                    descripcion.append(nombre).append(", ");
                }
            }
            if (descripcion.toString().endsWith(", ")) {
                descripcion.setLength(descripcion.length() - 2);
            }
        }

        erroresSintacticos.add(new ErrorSintactico(
            lexema, linea, columna, descripcion.toString()
        ));
    }

    public void unrecovered_syntax_error(Symbol s) {
        String lexema = (s != null && s.value != null)
                ? s.value.toString()
                : (s != null ? symbl_name_from_id(s.sym) : "EOF");

        erroresSintacticos.add(new ErrorSintactico(
            lexema,
            s != null ? s.left  : 0,
            s != null ? s.right : 0,
            "Error irrecuperable cerca de '" + lexema + "'"
        ));
    }

    public List<ErrorSintactico> getErroresSintacticos() {
        return erroresSintacticos;
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser2$actions {
  private final Parser2 parser;

  /** Constructor */
  CUP$Parser2$actions(Parser2 parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser2$do_action_part00000000(
    int                        CUP$Parser2$act_num,
    java_cup.runtime.lr_parser CUP$Parser2$parser,
    java.util.Stack            CUP$Parser2$stack,
    int                        CUP$Parser2$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser2$result;

      /* select the action based on the action number */
      switch (CUP$Parser2$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		Nodo2Programa start_val = (Nodo2Programa)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		RESULT = start_val;
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser2$parser.done_parsing();
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= metadatos lista_elementos 
            {
              Nodo2Programa RESULT =null;
		int elemsleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int elemsright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		java.util.List elems = (java.util.List)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = new Nodo2Programa(elems); 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // inicio ::= lista_elementos 
            {
              Nodo2Programa RESULT =null;
		int elemsleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int elemsright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		java.util.List elems = (java.util.List)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = new Nodo2Programa(elems); 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // metadatos ::= TRIPLE_HASH TRIPLE_HASH 
            {
              Object RESULT =null;

              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("metadatos",1, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // lista_elementos ::= elemento 
            {
              java.util.List RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		Nodo2Elemento e = (Nodo2Elemento)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		
                        java.util.List lista = new java.util.ArrayList<>();
                        if (e != null) lista.add(e);
                        RESULT = lista;
                    
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("lista_elementos",2, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // lista_elementos ::= lista_elementos elemento 
            {
              java.util.List RESULT =null;
		int listaleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int listaright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		java.util.List lista = (java.util.List)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		Nodo2Elemento e = (Nodo2Elemento)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		
                        if (e != null) lista.add(e);
                        RESULT = lista;
                    
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("lista_elementos",2, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // elemento ::= seccion 
            {
              Nodo2Elemento RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		Nodo2Elemento s = (Nodo2Elemento)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = s; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("elemento",3, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // elemento ::= tabla 
            {
              Nodo2Elemento RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		Nodo2Elemento t = (Nodo2Elemento)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = t; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("elemento",3, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // elemento ::= open_elem 
            {
              Nodo2Elemento RESULT =null;
		int oleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int oright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		Nodo2Elemento o = (Nodo2Elemento)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = o; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("elemento",3, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // elemento ::= drop_elem 
            {
              Nodo2Elemento RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		Nodo2Elemento d = (Nodo2Elemento)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = d; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("elemento",3, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // elemento ::= select_elem 
            {
              Nodo2Elemento RESULT =null;
		int seleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int seright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		Nodo2Elemento se = (Nodo2Elemento)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = se; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("elemento",3, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // elemento ::= multiple_elem 
            {
              Nodo2Elemento RESULT =null;
		int mleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int mright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		Nodo2Elemento m = (Nodo2Elemento)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = m; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("elemento",3, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // seccion ::= SECTION_OPEN NUMERO COMA NUMERO COMA NUMERO COMA NUMERO COMA orientacion TAG_CLOSE opt_estilos opt_contenido SECTION_CLOSE 
            {
              Nodo2Elemento RESULT =null;
		int wleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-12)).left;
		int wright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-12)).right;
		String w = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-12)).value;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-10)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-10)).right;
		String h = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-10)).value;
		int pxleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-8)).left;
		int pxright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-8)).right;
		String px = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-8)).value;
		int pyleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-6)).left;
		int pyright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-6)).right;
		String py = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-6)).value;
		int orileft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-4)).left;
		int oriright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-4)).right;
		String ori = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-4)).value;
		int estleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).left;
		int estright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).right;
		Nodo2Estilos est = (Nodo2Estilos)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).value;
		int contleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int contright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		java.util.List cont = (java.util.List)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		
                RESULT = new Nodo2Seccion(
                    Double.parseDouble(w), Double.parseDouble(h),
                    Double.parseDouble(px), Double.parseDouble(py),
                    ori, est, cont
                );
            
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("seccion",4, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-13)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // seccion ::= SECTION_OPEN NUMERO COMA NUMERO COMA NUMERO COMA NUMERO TAG_CLOSE opt_estilos opt_contenido SECTION_CLOSE 
            {
              Nodo2Elemento RESULT =null;
		int wleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-10)).left;
		int wright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-10)).right;
		String w = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-10)).value;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-8)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-8)).right;
		String h = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-8)).value;
		int pxleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-6)).left;
		int pxright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-6)).right;
		String px = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-6)).value;
		int pyleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-4)).left;
		int pyright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-4)).right;
		String py = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-4)).value;
		int estleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).left;
		int estright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).right;
		Nodo2Estilos est = (Nodo2Estilos)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).value;
		int contleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int contright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		java.util.List cont = (java.util.List)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		
                RESULT = new Nodo2Seccion(
                    Double.parseDouble(w), Double.parseDouble(h),
                    Double.parseDouble(px), Double.parseDouble(py),
                    "VERTICAL", est, cont
                );
            
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("seccion",4, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-11)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // orientacion ::= VERTICAL 
            {
              String RESULT =null;
		 RESULT = "VERTICAL"; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("orientacion",20, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // orientacion ::= HORIZONTAL 
            {
              String RESULT =null;
		 RESULT = "HORIZONTAL"; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("orientacion",20, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // opt_contenido ::= bloque_contenido 
            {
              java.util.List RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		java.util.List c = (java.util.List)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = c; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("opt_contenido",24, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // opt_contenido ::= 
            {
              java.util.List RESULT =null;
		 RESULT = new java.util.ArrayList<>(); 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("opt_contenido",24, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // bloque_contenido ::= CONTENT_OPEN lista_elementos CONTENT_CLOSE 
            {
              java.util.List RESULT =null;
		int elemsleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int elemsright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		java.util.List elems = (java.util.List)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		 RESULT = elems; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("bloque_contenido",23, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // opt_estilos ::= bloque_estilos 
            {
              Nodo2Estilos RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		Nodo2Estilos e = (Nodo2Estilos)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = e; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("opt_estilos",17, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // opt_estilos ::= 
            {
              Nodo2Estilos RESULT =null;
		 RESULT = null; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("opt_estilos",17, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // bloque_estilos ::= STYLE_OPEN prop_estilos_list STYLE_CLOSE 
            {
              Nodo2Estilos RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		Nodo2Estilos e = (Nodo2Estilos)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		 RESULT = e; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("bloque_estilos",16, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // prop_estilos_list ::= 
            {
              Nodo2Estilos RESULT =null;
		 RESULT = new Nodo2Estilos(); 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("prop_estilos_list",25, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // prop_estilos_list ::= prop_estilos_list prop_estilo 
            {
              Nodo2Estilos RESULT =null;
		int estleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int estright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		Nodo2Estilos est = (Nodo2Estilos)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		
                          if (p instanceof Object[]) {
                              Object[] pair = (Object[]) p;
                              String key = (String) pair[0];
                              Object val = pair[1];
                              switch (key) {
                                  case "color": est.setColor((Nodo2Color) val); break;
                                  case "bgColor": est.setBgColor((Nodo2Color) val); break;
                                  case "fontFamily": est.setFontFamily((String) val); break;
                                  case "textSize": est.setTextSize((Double) val); break;
                                  case "border": est.setBorde((Nodo2Borde) val); break;
                              }
                          }
                          RESULT = est;
                      
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("prop_estilos_list",25, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // prop_estilo ::= COLOR_TAG color SELF_CLOSE 
            {
              Object RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		Nodo2Color c = (Nodo2Color)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		 RESULT = new Object[]{"color", c}; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("prop_estilo",18, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // prop_estilo ::= BG_COLOR_TAG color SELF_CLOSE 
            {
              Object RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		Nodo2Color c = (Nodo2Color)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		 RESULT = new Object[]{"bgColor", c}; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("prop_estilo",18, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // prop_estilo ::= FONT_TAG fuente SELF_CLOSE 
            {
              Object RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		String f = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		 RESULT = new Object[]{"fontFamily", f}; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("prop_estilo",18, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // prop_estilo ::= TEXT_SIZE_TAG NUMERO TAG_CLOSE 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		 RESULT = new Object[]{"textSize", Double.parseDouble(n)}; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("prop_estilo",18, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // prop_estilo ::= TEXT_SIZE_TAG NUMERO SELF_CLOSE 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		 RESULT = new Object[]{"textSize", Double.parseDouble(n)}; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("prop_estilo",18, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // prop_estilo ::= BORDER_TAG NUMERO COMA tipo_borde COMA COLOR_ATTR color SELF_CLOSE 
            {
              Object RESULT =null;
		int grosorleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-6)).left;
		int grosorright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-6)).right;
		String grosor = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-6)).value;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-4)).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-4)).right;
		String tipo = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-4)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		Nodo2Color c = (Nodo2Color)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		 RESULT = new Object[]{"border", new Nodo2Borde(Double.parseDouble(grosor), tipo, c)}; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("prop_estilo",18, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-7)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // fuente ::= MONO 
            {
              String RESULT =null;
		 RESULT = "MONO"; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("fuente",21, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // fuente ::= SANS_SERIF 
            {
              String RESULT =null;
		 RESULT = "SANS_SERIF"; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("fuente",21, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // fuente ::= CURSIVE 
            {
              String RESULT =null;
		 RESULT = "CURSIVE"; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("fuente",21, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // tipo_borde ::= LINE_TYPE 
            {
              String RESULT =null;
		 RESULT = "LINE"; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("tipo_borde",22, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // tipo_borde ::= DOTTED 
            {
              String RESULT =null;
		 RESULT = "DOTTED"; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("tipo_borde",22, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // tipo_borde ::= DOUBLE_TYPE 
            {
              String RESULT =null;
		 RESULT = "DOUBLE"; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("tipo_borde",22, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // color ::= HEX_COLOR 
            {
              Nodo2Color RESULT =null;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		String h = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = new Nodo2ColorHex(h); 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("color",19, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // color ::= HSL_COLOR 
            {
              Nodo2Color RESULT =null;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		String h = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 RESULT = new Nodo2ColorHSL(h); 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("color",19, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // color ::= LPAREN NUMERO COMA NUMERO COMA NUMERO RPAREN 
            {
              Nodo2Color RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-5)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-5)).right;
		String r = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-5)).value;
		int gleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-3)).left;
		int gright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-3)).right;
		String g = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-3)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		 RESULT = new Nodo2ColorRGB(Double.parseDouble(r), Double.parseDouble(g), Double.parseDouble(b)); 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("color",19, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-6)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // color ::= RED 
            {
              Nodo2Color RESULT =null;
		 RESULT = new Nodo2ColorNombre("RED"); 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("color",19, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // color ::= BLUE 
            {
              Nodo2Color RESULT =null;
		 RESULT = new Nodo2ColorNombre("BLUE"); 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("color",19, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // color ::= GREEN 
            {
              Nodo2Color RESULT =null;
		 RESULT = new Nodo2ColorNombre("GREEN"); 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("color",19, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // color ::= YELLOW 
            {
              Nodo2Color RESULT =null;
		 RESULT = new Nodo2ColorNombre("YELLOW"); 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("color",19, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // color ::= BLACK 
            {
              Nodo2Color RESULT =null;
		 RESULT = new Nodo2ColorNombre("BLACK"); 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("color",19, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // color ::= WHITE 
            {
              Nodo2Color RESULT =null;
		 RESULT = new Nodo2ColorNombre("WHITE"); 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("color",19, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // color ::= PURPLE 
            {
              Nodo2Color RESULT =null;
		 RESULT = new Nodo2ColorNombre("PURPLE"); 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("color",19, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // color ::= SKY 
            {
              Nodo2Color RESULT =null;
		 RESULT = new Nodo2ColorNombre("SKY"); 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("color",19, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // tabla ::= TABLE_OPEN opt_estilos CONTENT_OPEN lista_lineas CONTENT_CLOSE TABLE_CLOSE 
            {
              Nodo2Elemento RESULT =null;
		int estleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-4)).left;
		int estright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-4)).right;
		Nodo2Estilos est = (Nodo2Estilos)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-4)).value;
		int lineasleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).left;
		int lineasright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).right;
		java.util.List lineas = (java.util.List)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).value;
		 RESULT = new Nodo2Tabla(est, lineas); 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("tabla",5, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-5)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // lista_lineas ::= linea 
            {
              java.util.List RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		java.util.List l = (java.util.List)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		
                     java.util.List lista = new java.util.ArrayList<>();
                     lista.add(l);
                     RESULT = lista;
                 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("lista_lineas",6, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // lista_lineas ::= lista_lineas linea 
            {
              java.util.List RESULT =null;
		int listaleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int listaright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		java.util.List lista = (java.util.List)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		java.util.List l = (java.util.List)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		
                     lista.add(l);
                     RESULT = lista;
                 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("lista_lineas",6, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // linea ::= LINE_OPEN lista_celdas LINE_CLOSE 
            {
              java.util.List RESULT =null;
		int celdasleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int celdasright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		java.util.List celdas = (java.util.List)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		 RESULT = celdas; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("linea",7, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // lista_celdas ::= celda 
            {
              java.util.List RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		Nodo2Elemento c = (Nodo2Elemento)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		
                     java.util.List lista = new java.util.ArrayList<>();
                     if (c != null) lista.add(c);
                     RESULT = lista;
                 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("lista_celdas",8, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // lista_celdas ::= lista_celdas celda 
            {
              java.util.List RESULT =null;
		int listaleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int listaright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		java.util.List lista = (java.util.List)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		Nodo2Elemento c = (Nodo2Elemento)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		
                     if (c != null) lista.add(c);
                     RESULT = lista;
                 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("lista_celdas",8, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // celda ::= ELEMENT_OPEN elemento ELEMENT_CLOSE 
            {
              Nodo2Elemento RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		Nodo2Elemento e = (Nodo2Elemento)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		 RESULT = e; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("celda",9, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // open_elem ::= OPEN_TAG NUMERO COMA NUMERO COMA CADENA SELF_CLOSE 
            {
              Nodo2Elemento RESULT =null;
		int wleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-5)).left;
		int wright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-5)).right;
		String w = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-5)).value;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-3)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-3)).right;
		String h = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-3)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		
                  RESULT = new Nodo2Open(
                      Double.parseDouble(w), Double.parseDouble(h), c, null
                  );
              
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("open_elem",10, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-6)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // open_elem ::= OPEN_TAG NUMERO COMA NUMERO COMA CADENA TAG_CLOSE bloque_estilos OPEN_CLOSE 
            {
              Nodo2Elemento RESULT =null;
		int wleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-7)).left;
		int wright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-7)).right;
		String w = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-7)).value;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-5)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-5)).right;
		String h = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-5)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-3)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-3)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-3)).value;
		int estleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int estright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		Nodo2Estilos est = (Nodo2Estilos)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		
                  RESULT = new Nodo2Open(
                      Double.parseDouble(w), Double.parseDouble(h), c, est
                  );
              
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("open_elem",10, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-8)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // drop_elem ::= DROP_TAG NUMERO COMA NUMERO COMA CADENA COMA LLLAVE lista_opciones RLLAVE COMA NUMERO SELF_CLOSE 
            {
              Nodo2Elemento RESULT =null;
		int wleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-11)).left;
		int wright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-11)).right;
		String w = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-11)).value;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-9)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-9)).right;
		String h = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-9)).value;
		int labelleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-7)).left;
		int labelright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-7)).right;
		String label = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-7)).value;
		int optsleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-4)).left;
		int optsright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-4)).right;
		java.util.List opts = (java.util.List)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-4)).value;
		int corrleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int corrright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		String corr = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		
                  RESULT = new Nodo2Drop(
                      Double.parseDouble(w), Double.parseDouble(h),
                      label, opts, Double.parseDouble(corr), null
                  );
              
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("drop_elem",11, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-12)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // drop_elem ::= DROP_TAG NUMERO COMA NUMERO COMA CADENA COMA LLLAVE lista_opciones RLLAVE COMA NUMERO TAG_CLOSE bloque_estilos DROP_CLOSE 
            {
              Nodo2Elemento RESULT =null;
		int wleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-13)).left;
		int wright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-13)).right;
		String w = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-13)).value;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-11)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-11)).right;
		String h = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-11)).value;
		int labelleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-9)).left;
		int labelright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-9)).right;
		String label = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-9)).value;
		int optsleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-6)).left;
		int optsright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-6)).right;
		java.util.List opts = (java.util.List)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-6)).value;
		int corrleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-3)).left;
		int corrright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-3)).right;
		String corr = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-3)).value;
		int estleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int estright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		Nodo2Estilos est = (Nodo2Estilos)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		
                  RESULT = new Nodo2Drop(
                      Double.parseDouble(w), Double.parseDouble(h),
                      label, opts, Double.parseDouble(corr), est
                  );
              
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("drop_elem",11, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-14)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // select_elem ::= SELECT_TAG NUMERO COMA NUMERO COMA LLLAVE lista_opciones RLLAVE COMA NUMERO SELF_CLOSE 
            {
              Nodo2Elemento RESULT =null;
		int wleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-9)).left;
		int wright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-9)).right;
		String w = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-9)).value;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-7)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-7)).right;
		String h = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-7)).value;
		int optsleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-4)).left;
		int optsright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-4)).right;
		java.util.List opts = (java.util.List)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-4)).value;
		int corrleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int corrright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		String corr = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		
                    RESULT = new Nodo2Select(
                        Double.parseDouble(w), Double.parseDouble(h),
                        opts, Double.parseDouble(corr), null
                    );
                
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("select_elem",12, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-10)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // select_elem ::= SELECT_TAG NUMERO COMA NUMERO COMA LLLAVE lista_opciones RLLAVE COMA NUMERO TAG_CLOSE bloque_estilos SELECT_CLOSE 
            {
              Nodo2Elemento RESULT =null;
		int wleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-11)).left;
		int wright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-11)).right;
		String w = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-11)).value;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-9)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-9)).right;
		String h = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-9)).value;
		int optsleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-6)).left;
		int optsright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-6)).right;
		java.util.List opts = (java.util.List)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-6)).value;
		int corrleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-3)).left;
		int corrright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-3)).right;
		String corr = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-3)).value;
		int estleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int estright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		Nodo2Estilos est = (Nodo2Estilos)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		
                    RESULT = new Nodo2Select(
                        Double.parseDouble(w), Double.parseDouble(h),
                        opts, Double.parseDouble(corr), est
                    );
                
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("select_elem",12, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-12)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // multiple_elem ::= MULTIPLE_TAG NUMERO COMA NUMERO COMA LLLAVE lista_opciones RLLAVE COMA LLLAVE lista_correctos RLLAVE SELF_CLOSE 
            {
              Nodo2Elemento RESULT =null;
		int wleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-11)).left;
		int wright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-11)).right;
		String w = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-11)).value;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-9)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-9)).right;
		String h = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-9)).value;
		int optsleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-6)).left;
		int optsright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-6)).right;
		java.util.List opts = (java.util.List)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-6)).value;
		int corrsleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).left;
		int corrsright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).right;
		java.util.List corrs = (java.util.List)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).value;
		
                      RESULT = new Nodo2Multiple(
                          Double.parseDouble(w), Double.parseDouble(h),
                          opts, corrs, null
                      );
                  
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("multiple_elem",13, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-12)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // multiple_elem ::= MULTIPLE_TAG NUMERO COMA NUMERO COMA LLLAVE lista_opciones RLLAVE COMA LLLAVE lista_correctos RLLAVE TAG_CLOSE bloque_estilos MULTIPLE_CLOSE 
            {
              Nodo2Elemento RESULT =null;
		int wleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-13)).left;
		int wright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-13)).right;
		String w = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-13)).value;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-11)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-11)).right;
		String h = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-11)).value;
		int optsleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-8)).left;
		int optsright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-8)).right;
		java.util.List opts = (java.util.List)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-8)).value;
		int corrsleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-4)).left;
		int corrsright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-4)).right;
		java.util.List corrs = (java.util.List)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-4)).value;
		int estleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).left;
		int estright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).right;
		Nodo2Estilos est = (Nodo2Estilos)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-1)).value;
		
                      RESULT = new Nodo2Multiple(
                          Double.parseDouble(w), Double.parseDouble(h),
                          opts, corrs, est
                      );
                  
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("multiple_elem",13, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-14)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // multiple_elem ::= MULTIPLE_TAG NUMERO COMA NUMERO COMA LLLAVE lista_opciones RLLAVE COMA LLLAVE RLLAVE SELF_CLOSE 
            {
              Nodo2Elemento RESULT =null;
		int wleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-10)).left;
		int wright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-10)).right;
		String w = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-10)).value;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-8)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-8)).right;
		String h = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-8)).value;
		int optsleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-5)).left;
		int optsright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-5)).right;
		java.util.List opts = (java.util.List)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-5)).value;
		
                      RESULT = new Nodo2Multiple(
                          Double.parseDouble(w), Double.parseDouble(h),
                          opts, new java.util.ArrayList<>(), null
                      );
                  
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("multiple_elem",13, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-11)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // lista_opciones ::= CADENA 
            {
              java.util.List RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		
                       java.util.List lista = new java.util.ArrayList<>();
                       lista.add(s);
                       RESULT = lista;
                   
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("lista_opciones",14, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // lista_opciones ::= lista_opciones COMA CADENA 
            {
              java.util.List RESULT =null;
		int listaleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).left;
		int listaright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).right;
		java.util.List lista = (java.util.List)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 lista.add(s); RESULT = lista; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("lista_opciones",14, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // lista_correctos ::= NUMERO 
            {
              java.util.List RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		
                        java.util.List lista = new java.util.ArrayList<>();
                        lista.add(Double.parseDouble(n));
                        RESULT = lista;
                    
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("lista_correctos",15, ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // lista_correctos ::= lista_correctos COMA NUMERO 
            {
              java.util.List RESULT =null;
		int listaleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).left;
		int listaright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).right;
		java.util.List lista = (java.util.List)((java_cup.runtime.Symbol) CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser2$stack.peek()).value;
		 lista.add(Double.parseDouble(n)); RESULT = lista; 
              CUP$Parser2$result = parser.getSymbolFactory().newSymbol("lista_correctos",15, ((java_cup.runtime.Symbol)CUP$Parser2$stack.elementAt(CUP$Parser2$top-2)), ((java_cup.runtime.Symbol)CUP$Parser2$stack.peek()), RESULT);
            }
          return CUP$Parser2$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser2$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser2$do_action(
    int                        CUP$Parser2$act_num,
    java_cup.runtime.lr_parser CUP$Parser2$parser,
    java.util.Stack            CUP$Parser2$stack,
    int                        CUP$Parser2$top)
    throws java.lang.Exception
    {
              return CUP$Parser2$do_action_part00000000(
                               CUP$Parser2$act_num,
                               CUP$Parser2$parser,
                               CUP$Parser2$stack,
                               CUP$Parser2$top);
    }
}

}
