
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.proyecto1_compi1.Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int HORIZONTAL = 11;
  public static final int SELECT_QUESTION = 8;
  public static final int TEXT_SIZE = 27;
  public static final int POKEMON = 84;
  public static final int MENOR_IGUAL = 65;
  public static final int RLLAVE = 76;
  public static final int TABLE = 44;
  public static final int LLLAVE = 75;
  public static final int POTENCIA = 60;
  public static final int MAYOR = 62;
  public static final int SANS_SERIF = 40;
  public static final int DROP_QUESTION = 10;
  public static final int SPECIAL = 6;
  public static final int BLUE = 33;
  public static final int YELLOW = 35;
  public static final int DIFERENTE = 67;
  public static final int ELEMENTS = 18;
  public static final int DRAW = 83;
  public static final int WHITE = 37;
  public static final int RPAREN = 72;
  public static final int OPEN_QUESTION = 7;
  public static final int BLACK = 36;
  public static final int NUMERO = 54;
  public static final int DOUBLE = 46;
  public static final int BACKGROUND_COLOR = 25;
  public static final int LPAREN = 71;
  public static final int NUMBER_TYPE = 4;
  public static final int NOT = 70;
  public static final int TEXT = 3;
  public static final int MULTI = 58;
  public static final int DOS_PUNTOS = 78;
  public static final int PURPLE = 38;
  public static final int WIDTH = 13;
  public static final int RGB_COLOR = 30;
  public static final int PUNTO_COMA = 79;
  public static final int STYLES = 23;
  public static final int MOD = 61;
  public static final int COMA = 77;
  public static final int RCORCHETE = 73;
  public static final int CURSIVE = 42;
  public static final int MONO = 41;
  public static final int IGUAL = 66;
  public static final int WHILE = 47;
  public static final int HSL_COLOR = 31;
  public static final int DO = 51;
  public static final int FOR = 48;
  public static final int DIV = 59;
  public static final int COMODIN = 85;
  public static final int ORIENTATION = 17;
  public static final int ELSE = 49;
  public static final int MULTIPLE_QUESTION = 9;
  public static final int MENOR = 63;
  public static final int CORRECT = 20;
  public static final int CONTENT = 21;
  public static final int EOF = 0;
  public static final int PUNTO = 80;
  public static final int VERTICAL = 12;
  public static final int LCORCHETE = 74;
  public static final int SUMA = 56;
  public static final int LINE = 43;
  public static final int LABEL = 22;
  public static final int IN = 52;
  public static final int OR = 69;
  public static final int SKY = 39;
  public static final int error = 1;
  public static final int RESTA = 57;
  public static final int IF = 50;
  public static final int DOTTED = 45;
  public static final int ID = 55;
  public static final int COLOR = 24;
  public static final int HEX_COLOR = 29;
  public static final int RANGO = 82;
  public static final int BORDER = 28;
  public static final int HEIGHT = 14;
  public static final int RED = 32;
  public static final int ASIGNACION = 81;
  public static final int FONT_FAMILY = 26;
  public static final int CADENA = 53;
  public static final int POINTY = 16;
  public static final int OPTIONS = 19;
  public static final int POINTX = 15;
  public static final int AND = 68;
  public static final int MAYOR_IGUAL = 64;
  public static final int SECTION = 2;
  public static final int GREEN = 34;
  public static final int STRING_TYPE = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SECTION",
  "TEXT",
  "NUMBER_TYPE",
  "STRING_TYPE",
  "SPECIAL",
  "OPEN_QUESTION",
  "SELECT_QUESTION",
  "MULTIPLE_QUESTION",
  "DROP_QUESTION",
  "HORIZONTAL",
  "VERTICAL",
  "WIDTH",
  "HEIGHT",
  "POINTX",
  "POINTY",
  "ORIENTATION",
  "ELEMENTS",
  "OPTIONS",
  "CORRECT",
  "CONTENT",
  "LABEL",
  "STYLES",
  "COLOR",
  "BACKGROUND_COLOR",
  "FONT_FAMILY",
  "TEXT_SIZE",
  "BORDER",
  "HEX_COLOR",
  "RGB_COLOR",
  "HSL_COLOR",
  "RED",
  "BLUE",
  "GREEN",
  "YELLOW",
  "BLACK",
  "WHITE",
  "PURPLE",
  "SKY",
  "SANS_SERIF",
  "MONO",
  "CURSIVE",
  "LINE",
  "TABLE",
  "DOTTED",
  "DOUBLE",
  "WHILE",
  "FOR",
  "ELSE",
  "IF",
  "DO",
  "IN",
  "CADENA",
  "NUMERO",
  "ID",
  "SUMA",
  "RESTA",
  "MULTI",
  "DIV",
  "POTENCIA",
  "MOD",
  "MAYOR",
  "MENOR",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "IGUAL",
  "DIFERENTE",
  "AND",
  "OR",
  "NOT",
  "LPAREN",
  "RPAREN",
  "RCORCHETE",
  "LCORCHETE",
  "LLLAVE",
  "RLLAVE",
  "COMA",
  "DOS_PUNTOS",
  "PUNTO_COMA",
  "PUNTO",
  "ASIGNACION",
  "RANGO",
  "DRAW",
  "POKEMON",
  "COMODIN"
  };
}

