
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.proyecto1_compi1.Analizadores;

/** CUP generated class containing symbol constants. */
public class sym2 {
  /* terminals */
  public static final int NUMERO = 36;
  public static final int HSL_COLOR = 39;
  public static final int ELEMENT_CLOSE = 22;
  public static final int TRIPLE_HASH = 2;
  public static final int LINE_CLOSE = 21;
  public static final int WHITE = 45;
  public static final int MONO = 48;
  public static final int LPAREN = 34;
  public static final int LINE_TYPE = 51;
  public static final int FONT_TAG = 25;
  public static final int ELEMENT_OPEN = 12;
  public static final int RED = 40;
  public static final int RPAREN = 35;
  public static final int HORIZONTAL = 55;
  public static final int LLLAVE = 32;
  public static final int TABLE_CLOSE = 14;
  public static final int CONTENT_OPEN = 10;
  public static final int DROP_CLOSE = 16;
  public static final int CURSIVE = 50;
  public static final int RLLAVE = 33;
  public static final int SELECT_CLOSE = 17;
  public static final int VERTICAL = 54;
  public static final int BORDER_TAG = 27;
  public static final int SECTION_CLOSE = 13;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int SECTION_OPEN = 3;
  public static final int COMA = 31;
  public static final int CADENA = 37;
  public static final int COLOR_TAG = 23;
  public static final int STYLE_OPEN = 9;
  public static final int DOUBLE_TYPE = 53;
  public static final int SELECT_TAG = 6;
  public static final int CONTENT_CLOSE = 20;
  public static final int STYLE_CLOSE = 19;
  public static final int MULTIPLE_CLOSE = 18;
  public static final int SELF_CLOSE = 29;
  public static final int COLOR_ATTR = 28;
  public static final int LINE_OPEN = 11;
  public static final int DROP_TAG = 5;
  public static final int MULTIPLE_TAG = 7;
  public static final int YELLOW = 43;
  public static final int SANS_SERIF = 49;
  public static final int BLUE = 41;
  public static final int BG_COLOR_TAG = 24;
  public static final int PURPLE = 46;
  public static final int GREEN = 42;
  public static final int TABLE_OPEN = 8;
  public static final int BLACK = 44;
  public static final int OPEN_TAG = 4;
  public static final int TEXT_SIZE_TAG = 26;
  public static final int DOTTED = 52;
  public static final int SKY = 47;
  public static final int TAG_CLOSE = 30;
  public static final int HEX_COLOR = 38;
  public static final int OPEN_CLOSE = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TRIPLE_HASH",
  "SECTION_OPEN",
  "OPEN_TAG",
  "DROP_TAG",
  "SELECT_TAG",
  "MULTIPLE_TAG",
  "TABLE_OPEN",
  "STYLE_OPEN",
  "CONTENT_OPEN",
  "LINE_OPEN",
  "ELEMENT_OPEN",
  "SECTION_CLOSE",
  "TABLE_CLOSE",
  "OPEN_CLOSE",
  "DROP_CLOSE",
  "SELECT_CLOSE",
  "MULTIPLE_CLOSE",
  "STYLE_CLOSE",
  "CONTENT_CLOSE",
  "LINE_CLOSE",
  "ELEMENT_CLOSE",
  "COLOR_TAG",
  "BG_COLOR_TAG",
  "FONT_TAG",
  "TEXT_SIZE_TAG",
  "BORDER_TAG",
  "COLOR_ATTR",
  "SELF_CLOSE",
  "TAG_CLOSE",
  "COMA",
  "LLLAVE",
  "RLLAVE",
  "LPAREN",
  "RPAREN",
  "NUMERO",
  "CADENA",
  "HEX_COLOR",
  "HSL_COLOR",
  "RED",
  "BLUE",
  "GREEN",
  "YELLOW",
  "BLACK",
  "WHITE",
  "PURPLE",
  "SKY",
  "MONO",
  "SANS_SERIF",
  "CURSIVE",
  "LINE_TYPE",
  "DOTTED",
  "DOUBLE_TYPE",
  "VERTICAL",
  "HORIZONTAL"
  };
}

