// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: /home/herson/Repositorios Git/Proyecto1_Compi1/Proyecto1_Compi1/app/src/main/Flex/Lexer.flex

//imports


@SuppressWarnings("fallthrough")
public class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\2\22\0\1\4\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\0\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\12\23\1\24"+
    "\1\0\1\25\1\26\1\27\1\30\1\0\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\1\55\1\56\1\57\1\60\1\61\1\62"+
    "\1\63\1\64\1\65\1\66\1\67\1\0\1\70\1\71"+
    "\1\72\1\73\1\74\1\75\1\76\1\77\1\100\1\42"+
    "\1\101\1\102\1\103\1\104\1\105\1\106\1\42\1\107"+
    "\1\110\1\111\1\112\1\42\1\113\1\114\1\115\1\116"+
    "\1\117\1\120\1\121\1\122\6\0\1\3\u01a2\0\2\3"+
    "\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\3\1\1\4\1\5\1\1"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\1\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\23\23\1\24"+
    "\1\25\1\26\15\23\1\27\1\1\1\30\1\31\1\32"+
    "\1\0\1\33\2\0\1\34\1\0\1\35\3\0\1\36"+
    "\1\37\1\40\2\23\1\41\5\23\1\42\24\23\1\43"+
    "\12\23\1\44\4\0\1\15\2\0\7\23\1\45\7\23"+
    "\1\46\3\23\1\47\30\23\3\0\1\50\2\0\1\23"+
    "\1\51\4\23\1\52\2\23\1\53\1\54\7\23\1\55"+
    "\25\23\1\0\1\23\5\0\1\56\3\23\1\0\1\57"+
    "\2\23\1\0\1\23\1\0\2\23\1\60\1\23\1\61"+
    "\1\62\3\23\1\63\3\23\1\0\1\23\1\64\7\23"+
    "\2\0\1\65\5\0\1\23\1\66\1\67\1\0\2\23"+
    "\1\0\1\70\1\0\3\23\1\71\1\23\1\72\3\23"+
    "\1\0\1\73\1\74\2\23\1\75\1\76\1\23\1\77"+
    "\1\100\2\0\1\101\1\102\2\0\1\103\1\104\1\0"+
    "\2\23\2\0\1\105\1\0\2\23\1\106\1\107\1\23"+
    "\1\0\1\110\1\23\1\111\5\0\2\23\3\0\1\112"+
    "\1\23\1\113\1\0\1\23\3\0\1\23\4\0\1\23"+
    "\1\0\1\23\1\114\2\0\1\115\2\0\1\116\1\0"+
    "\1\23\1\0\1\23\6\0\1\117\1\120\7\0\1\121"+
    "\1\0\1\122\10\0\1\123\3\0\1\124\1\0\1\125"+
    "\2\0\1\126";

  private static int [] zzUnpackAction() {
    int [] result = new int[389];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\123\0\246\0\123\0\371\0\u014c\0\u019f\0\u01f2"+
    "\0\123\0\u0245\0\u0298\0\123\0\123\0\123\0\123\0\123"+
    "\0\u02eb\0\u033e\0\u0391\0\123\0\u03e4\0\u0437\0\u048a\0\123"+
    "\0\u04dd\0\u0530\0\u0583\0\u05d6\0\u0629\0\u067c\0\u06cf\0\u0722"+
    "\0\u0775\0\u07c8\0\u081b\0\u086e\0\u08c1\0\u0914\0\u0967\0\u09ba"+
    "\0\u0a0d\0\u0a60\0\u0ab3\0\123\0\123\0\123\0\u0b06\0\u0b59"+
    "\0\u0bac\0\u0bff\0\u0c52\0\u0ca5\0\u0cf8\0\u0d4b\0\u0d9e\0\u0df1"+
    "\0\u0e44\0\u0e97\0\u0eea\0\123\0\u0f3d\0\123\0\123\0\123"+
    "\0\u014c\0\123\0\u0f90\0\u0fe3\0\123\0\u1036\0\123\0\u1089"+
    "\0\u10dc\0\u112f\0\123\0\123\0\123\0\u1182\0\u11d5\0\u1228"+
    "\0\u127b\0\u12ce\0\u1321\0\u1374\0\u13c7\0\u04dd\0\u141a\0\u146d"+
    "\0\u14c0\0\u1513\0\u1566\0\u15b9\0\u160c\0\u165f\0\u16b2\0\u1705"+
    "\0\u1758\0\u17ab\0\u17fe\0\u1851\0\u18a4\0\u18f7\0\u194a\0\u199d"+
    "\0\u19f0\0\u1a43\0\u04dd\0\u1a96\0\u1ae9\0\u1b3c\0\u1b8f\0\u1be2"+
    "\0\u1c35\0\u1c88\0\u1cdb\0\u1d2e\0\u1d81\0\123\0\u1dd4\0\u1e27"+
    "\0\u1e7a\0\u1ecd\0\u10dc\0\u1f20\0\u1f73\0\u1fc6\0\u2019\0\u206c"+
    "\0\u20bf\0\u2112\0\u2165\0\u21b8\0\u04dd\0\u220b\0\u225e\0\u22b1"+
    "\0\u2304\0\u2357\0\u23aa\0\u23fd\0\u04dd\0\u2450\0\u24a3\0\u24f6"+
    "\0\u04dd\0\u2549\0\u259c\0\u25ef\0\u2642\0\u2695\0\u26e8\0\u273b"+
    "\0\u278e\0\u27e1\0\u2834\0\u2887\0\u28da\0\u292d\0\u2980\0\u29d3"+
    "\0\u2a26\0\u2a79\0\u2acc\0\u2b1f\0\u2b72\0\u2bc5\0\u2c18\0\u2c6b"+
    "\0\u2cbe\0\u2d11\0\u2d64\0\u2db7\0\123\0\u2e0a\0\u2e5d\0\u2eb0"+
    "\0\u04dd\0\u2f03\0\u2f56\0\u2fa9\0\u2ffc\0\u04dd\0\u304f\0\u30a2"+
    "\0\u04dd\0\u04dd\0\u30f5\0\u3148\0\u319b\0\u31ee\0\u3241\0\u3294"+
    "\0\u32e7\0\u04dd\0\u333a\0\u338d\0\u33e0\0\u3433\0\u3486\0\u34d9"+
    "\0\u352c\0\u357f\0\u35d2\0\u3625\0\u3678\0\u36cb\0\u371e\0\u3771"+
    "\0\u37c4\0\u3817\0\u386a\0\u38bd\0\u3910\0\u3963\0\u39b6\0\u3a09"+
    "\0\u3a5c\0\u3aaf\0\u3b02\0\u3b55\0\u3ba8\0\u3bfb\0\u04dd\0\u3c4e"+
    "\0\u3ca1\0\u3cf4\0\u3d47\0\u04dd\0\u3d9a\0\u3ded\0\u3e40\0\u3e93"+
    "\0\u3ee6\0\u3f39\0\u3f8c\0\u04dd\0\u3fdf\0\u04dd\0\u04dd\0\u4032"+
    "\0\u4085\0\u40d8\0\u04dd\0\u412b\0\u417e\0\u41d1\0\u4224\0\u4277"+
    "\0\u04dd\0\u42ca\0\u431d\0\u4370\0\u43c3\0\u4416\0\u4469\0\u44bc"+
    "\0\u450f\0\u4562\0\u04dd\0\u45b5\0\u4608\0\u465b\0\u46ae\0\u4701"+
    "\0\u4754\0\u04dd\0\u04dd\0\u47a7\0\u47fa\0\u484d\0\u48a0\0\u04dd"+
    "\0\u48f3\0\u4946\0\u4999\0\u49ec\0\u04dd\0\u4a3f\0\u04dd\0\u4a92"+
    "\0\u4ae5\0\u4b38\0\u4b8b\0\u04dd\0\u04dd\0\u4bde\0\u4c31\0\u04dd"+
    "\0\u04dd\0\u4c84\0\u04dd\0\u04dd\0\u4cd7\0\u4d2a\0\123\0\123"+
    "\0\u4d7d\0\u4dd0\0\123\0\u04dd\0\u4e23\0\u4e76\0\u4ec9\0\u4f1c"+
    "\0\u4f6f\0\u04dd\0\u4fc2\0\u5015\0\u5068\0\u04dd\0\u04dd\0\u50bb"+
    "\0\u510e\0\u04dd\0\u5161\0\u04dd\0\u51b4\0\u5207\0\u525a\0\u52ad"+
    "\0\u5300\0\u5353\0\u53a6\0\u53f9\0\u544c\0\u549f\0\u04dd\0\u54f2"+
    "\0\u04dd\0\u5545\0\u5598\0\u55eb\0\u563e\0\u5691\0\u56e4\0\u5737"+
    "\0\u578a\0\u57dd\0\u5830\0\u5883\0\u58d6\0\u5929\0\123\0\u597c"+
    "\0\u59cf\0\u04dd\0\u5a22\0\u5a75\0\123\0\u5ac8\0\u5b1b\0\u5b6e"+
    "\0\u5bc1\0\u5c14\0\u5c67\0\u5cba\0\u5d0d\0\u5d60\0\u5db3\0\123"+
    "\0\u04dd\0\u5e06\0\u5e59\0\u5eac\0\u5eff\0\u5f52\0\u5fa5\0\u5ff8"+
    "\0\123\0\u604b\0\123\0\u609e\0\u60f1\0\u6144\0\u6197\0\u61ea"+
    "\0\u623d\0\u6290\0\u62e3\0\123\0\u6336\0\u6389\0\u63dc\0\123"+
    "\0\u642f\0\123\0\u6482\0\u64d5\0\123";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[389];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\3\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\2\31\1\42\1\43\1\31\1\44\1\45\1\31"+
    "\1\46\1\47\1\50\1\31\1\51\1\52\1\31\1\53"+
    "\1\31\1\54\1\2\1\55\1\56\2\31\1\57\1\60"+
    "\1\31\1\61\1\62\1\31\1\63\1\64\1\31\1\65"+
    "\1\31\1\66\1\67\1\70\1\31\1\71\1\72\1\31"+
    "\1\73\3\31\1\74\1\75\1\76\1\77\124\0\2\3"+
    "\1\0\1\3\123\0\1\100\115\0\6\101\1\102\55\101"+
    "\1\103\36\101\23\0\1\104\5\0\6\104\31\0\6\104"+
    "\25\0\2\10\2\0\117\10\12\0\1\105\133\0\1\106"+
    "\120\0\1\107\116\0\1\110\126\0\1\111\1\0\1\23"+
    "\122\0\1\112\2\0\1\113\122\0\1\114\122\0\1\115"+
    "\117\0\1\31\5\0\32\31\5\0\27\31\27\0\1\31"+
    "\5\0\13\31\1\116\16\31\5\0\27\31\27\0\1\31"+
    "\5\0\24\31\1\117\5\31\5\0\27\31\27\0\1\31"+
    "\5\0\16\31\1\120\2\31\1\121\10\31\5\0\27\31"+
    "\27\0\1\31\5\0\13\31\1\122\16\31\5\0\27\31"+
    "\27\0\1\31\5\0\16\31\1\123\13\31\5\0\27\31"+
    "\27\0\1\31\5\0\21\31\1\124\10\31\5\0\27\31"+
    "\27\0\1\31\5\0\16\31\1\125\13\31\5\0\27\31"+
    "\27\0\1\31\5\0\5\31\1\126\24\31\5\0\27\31"+
    "\27\0\1\31\5\0\10\31\1\127\21\31\5\0\27\31"+
    "\27\0\1\31\5\0\16\31\1\130\5\31\1\131\5\31"+
    "\5\0\27\31\27\0\1\31\5\0\17\31\1\132\12\31"+
    "\5\0\27\31\27\0\1\31\5\0\24\31\1\133\5\31"+
    "\5\0\27\31\27\0\1\31\5\0\4\31\1\134\25\31"+
    "\5\0\27\31\27\0\1\31\5\0\1\135\3\31\1\136"+
    "\5\31\1\137\17\31\5\0\27\31\27\0\1\31\5\0"+
    "\1\140\3\31\1\141\25\31\5\0\27\31\27\0\1\31"+
    "\5\0\4\31\1\142\25\31\5\0\27\31\27\0\1\31"+
    "\5\0\7\31\1\143\22\31\5\0\27\31\27\0\1\31"+
    "\5\0\4\31\1\144\25\31\5\0\27\31\27\0\1\31"+
    "\5\0\32\31\5\0\1\145\14\31\1\146\11\31\27\0"+
    "\1\31\5\0\32\31\5\0\15\31\1\147\11\31\27\0"+
    "\1\31\5\0\32\31\5\0\12\31\1\150\14\31\27\0"+
    "\1\31\5\0\32\31\5\0\15\31\1\151\11\31\27\0"+
    "\1\31\5\0\32\31\5\0\4\31\1\152\22\31\27\0"+
    "\1\31\5\0\32\31\5\0\14\31\1\153\12\31\27\0"+
    "\1\31\5\0\32\31\5\0\1\154\26\31\27\0\1\31"+
    "\5\0\32\31\5\0\22\31\1\155\4\31\27\0\1\31"+
    "\5\0\32\31\5\0\16\31\1\156\1\157\7\31\27\0"+
    "\1\31\5\0\32\31\5\0\15\31\1\160\11\31\27\0"+
    "\1\31\5\0\32\31\5\0\16\31\1\161\2\31\1\162"+
    "\5\31\27\0\1\31\5\0\32\31\5\0\4\31\1\163"+
    "\22\31\27\0\1\31\5\0\32\31\5\0\7\31\1\164"+
    "\1\165\16\31\124\0\1\166\2\0\2\101\2\0\117\101"+
    "\23\0\1\167\5\0\6\167\31\0\6\167\44\0\1\170"+
    "\3\0\1\171\77\0\15\110\1\172\105\110\23\0\1\173"+
    "\116\0\1\174\3\0\1\175\122\0\1\31\5\0\1\176"+
    "\23\31\1\177\5\31\5\0\27\31\27\0\1\31\5\0"+
    "\21\31\1\200\10\31\5\0\27\31\27\0\1\31\5\0"+
    "\23\31\1\201\1\202\5\31\5\0\27\31\27\0\1\31"+
    "\5\0\16\31\1\203\13\31\5\0\27\31\27\0\1\31"+
    "\5\0\22\31\1\204\7\31\5\0\27\31\27\0\1\31"+
    "\5\0\21\31\1\205\10\31\5\0\27\31\27\0\1\31"+
    "\5\0\4\31\1\206\25\31\5\0\27\31\27\0\1\31"+
    "\5\0\21\31\1\207\10\31\5\0\27\31\27\0\1\31"+
    "\5\0\15\31\1\210\14\31\5\0\27\31\27\0\1\31"+
    "\5\0\15\31\1\211\14\31\5\0\27\31\27\0\1\31"+
    "\5\0\13\31\1\212\16\31\5\0\27\31\27\0\1\31"+
    "\5\0\4\31\1\213\25\31\5\0\27\31\27\0\1\31"+
    "\5\0\21\31\1\214\10\31\5\0\27\31\27\0\1\31"+
    "\5\0\3\31\1\215\26\31\5\0\27\31\27\0\1\31"+
    "\5\0\15\31\1\216\14\31\5\0\27\31\27\0\1\31"+
    "\5\0\2\31\1\217\10\31\1\220\16\31\5\0\27\31"+
    "\27\0\1\31\5\0\30\31\1\221\1\31\5\0\27\31"+
    "\27\0\1\31\5\0\1\31\1\222\30\31\5\0\27\31"+
    "\27\0\1\31\5\0\27\31\1\223\2\31\5\0\27\31"+
    "\27\0\1\31\5\0\21\31\1\224\10\31\5\0\27\31"+
    "\27\0\1\31\5\0\10\31\1\225\21\31\5\0\27\31"+
    "\27\0\1\31\5\0\13\31\1\226\16\31\5\0\27\31"+
    "\27\0\1\31\5\0\32\31\5\0\2\31\1\227\24\31"+
    "\27\0\1\31\5\0\32\31\5\0\17\31\1\230\7\31"+
    "\27\0\1\31\5\0\32\31\5\0\12\31\1\231\1\31"+
    "\1\232\2\31\1\233\7\31\27\0\1\31\5\0\32\31"+
    "\5\0\4\31\1\234\22\31\27\0\1\31\5\0\32\31"+
    "\5\0\14\31\1\235\12\31\27\0\1\31\5\0\32\31"+
    "\5\0\10\31\1\236\16\31\27\0\1\31\5\0\32\31"+
    "\5\0\1\31\1\237\25\31\27\0\1\31\5\0\32\31"+
    "\5\0\13\31\1\240\13\31\27\0\1\31\5\0\32\31"+
    "\5\0\21\31\1\241\5\31\27\0\1\31\5\0\32\31"+
    "\5\0\10\31\1\242\16\31\27\0\1\31\5\0\32\31"+
    "\5\0\10\31\1\243\16\31\27\0\1\31\5\0\32\31"+
    "\5\0\4\31\1\244\22\31\27\0\1\31\5\0\32\31"+
    "\5\0\17\31\1\245\5\31\1\246\1\31\27\0\1\31"+
    "\5\0\32\31\5\0\24\31\1\247\2\31\27\0\1\31"+
    "\5\0\32\31\5\0\15\31\1\250\11\31\27\0\1\31"+
    "\5\0\32\31\5\0\3\31\1\251\23\31\27\0\1\252"+
    "\5\0\6\252\31\0\6\252\50\0\1\253\116\0\1\170"+
    "\3\0\1\254\77\0\15\110\1\172\4\110\1\255\100\110"+
    "\23\0\1\256\116\0\1\174\3\0\1\257\122\0\1\31"+
    "\5\0\2\31\1\260\27\31\5\0\27\31\27\0\1\31"+
    "\5\0\4\31\1\261\25\31\5\0\27\31\27\0\1\31"+
    "\5\0\22\31\1\262\7\31\5\0\27\31\27\0\1\31"+
    "\5\0\23\31\1\263\6\31\5\0\27\31\27\0\1\31"+
    "\5\0\1\31\1\264\30\31\5\0\27\31\27\0\1\31"+
    "\5\0\17\31\1\265\12\31\5\0\27\31\27\0\1\31"+
    "\5\0\4\31\1\266\25\31\5\0\27\31\27\0\1\31"+
    "\5\0\4\31\1\267\25\31\5\0\27\31\27\0\1\31"+
    "\5\0\10\31\1\270\21\31\5\0\27\31\27\0\1\31"+
    "\5\0\4\31\1\271\25\31\5\0\27\31\27\0\1\31"+
    "\5\0\16\31\1\272\13\31\5\0\27\31\27\0\1\31"+
    "\5\0\23\31\1\273\6\31\5\0\27\31\27\0\1\31"+
    "\5\0\15\31\1\274\14\31\5\0\27\31\27\0\1\31"+
    "\5\0\17\31\1\275\12\31\5\0\27\31\27\0\1\31"+
    "\5\0\22\31\1\276\7\31\5\0\27\31\27\0\1\31"+
    "\5\0\23\31\1\277\6\31\5\0\27\31\27\0\1\31"+
    "\5\0\4\31\1\300\25\31\5\0\27\31\27\0\1\31"+
    "\5\0\13\31\1\301\16\31\5\0\27\31\27\0\1\31"+
    "\5\0\23\31\1\302\6\31\5\0\27\31\27\0\1\31"+
    "\5\0\23\31\1\303\6\31\5\0\27\31\27\0\1\31"+
    "\5\0\13\31\1\304\7\31\1\305\6\31\5\0\27\31"+
    "\27\0\1\31\5\0\13\31\1\306\16\31\5\0\27\31"+
    "\27\0\1\31\5\0\32\31\5\0\11\31\1\307\15\31"+
    "\27\0\1\31\5\0\32\31\5\0\3\31\1\310\23\31"+
    "\27\0\1\31\5\0\32\31\5\0\15\31\1\311\11\31"+
    "\27\0\1\31\5\0\32\31\5\0\21\31\1\312\5\31"+
    "\27\0\1\31\5\0\32\31\5\0\17\31\1\313\7\31"+
    "\27\0\1\31\5\0\32\31\5\0\13\31\1\314\13\31"+
    "\27\0\1\31\5\0\32\31\5\0\21\31\1\315\5\31"+
    "\27\0\1\31\5\0\32\31\5\0\6\31\1\316\20\31"+
    "\27\0\1\31\5\0\32\31\5\0\4\31\1\317\22\31"+
    "\27\0\1\31\5\0\32\31\5\0\1\31\1\320\25\31"+
    "\27\0\1\31\5\0\32\31\5\0\10\31\1\321\16\31"+
    "\27\0\1\31\5\0\32\31\5\0\4\31\1\322\22\31"+
    "\27\0\1\31\5\0\32\31\5\0\14\31\1\323\12\31"+
    "\27\0\1\31\5\0\32\31\5\0\2\31\1\324\24\31"+
    "\27\0\1\31\5\0\32\31\5\0\10\31\1\325\16\31"+
    "\27\0\1\31\5\0\32\31\5\0\12\31\1\326\14\31"+
    "\27\0\1\31\5\0\32\31\5\0\21\31\1\327\5\31"+
    "\27\0\1\31\5\0\32\31\4\0\1\330\27\31\27\0"+
    "\1\31\5\0\32\31\5\0\21\31\1\331\5\31\27\0"+
    "\1\332\5\0\6\332\31\0\6\332\44\0\1\333\3\0"+
    "\1\334\116\0\1\170\122\0\1\335\3\0\1\336\116\0"+
    "\1\174\126\0\1\31\5\0\12\31\1\337\17\31\5\0"+
    "\27\31\27\0\1\31\5\0\10\31\1\340\21\31\5\0"+
    "\27\31\27\0\1\31\5\0\4\31\1\341\25\31\5\0"+
    "\27\31\27\0\1\31\5\0\13\31\1\342\16\31\5\0"+
    "\27\31\27\0\1\31\5\0\32\31\4\0\1\343\27\31"+
    "\27\0\1\31\5\0\15\31\1\344\14\31\5\0\27\31"+
    "\27\0\1\31\5\0\31\31\1\345\5\0\27\31\27\0"+
    "\1\31\5\0\10\31\1\346\21\31\5\0\27\31\27\0"+
    "\1\31\5\0\32\31\4\0\1\347\27\31\27\0\1\31"+
    "\5\0\13\31\1\350\16\31\5\0\27\31\27\0\1\31"+
    "\5\0\32\31\4\0\1\351\27\31\27\0\1\31\5\0"+
    "\10\31\1\352\21\31\5\0\27\31\27\0\1\31\5\0"+
    "\2\31\1\353\27\31\5\0\27\31\27\0\1\31\5\0"+
    "\4\31\1\354\25\31\5\0\27\31\27\0\1\31\5\0"+
    "\10\31\1\355\21\31\5\0\27\31\27\0\1\31\5\0"+
    "\4\31\1\356\25\31\5\0\27\31\27\0\1\31\5\0"+
    "\4\31\1\357\25\31\5\0\27\31\27\0\1\31\5\0"+
    "\16\31\1\360\13\31\5\0\27\31\27\0\1\31\5\0"+
    "\32\31\5\0\6\31\1\361\20\31\27\0\1\31\5\0"+
    "\32\31\5\0\4\31\1\362\22\31\27\0\1\31\5\0"+
    "\32\31\5\0\17\31\1\363\7\31\27\0\1\31\5\0"+
    "\32\31\5\0\4\31\1\364\22\31\27\0\1\31\5\0"+
    "\32\31\5\0\4\31\1\365\22\31\27\0\1\31\5\0"+
    "\32\31\5\0\4\31\1\366\22\31\10\0\1\367\16\0"+
    "\1\31\5\0\32\31\5\0\27\31\27\0\1\31\5\0"+
    "\32\31\5\0\7\31\1\370\17\31\27\0\1\31\5\0"+
    "\32\31\5\0\12\31\1\371\14\31\27\0\1\31\5\0"+
    "\32\31\5\0\4\31\1\372\22\31\27\0\1\31\5\0"+
    "\32\31\5\0\15\31\1\373\11\31\27\0\1\31\5\0"+
    "\32\31\5\0\14\31\1\374\12\31\27\0\1\31\5\0"+
    "\32\31\5\0\21\31\1\375\5\31\27\0\1\31\5\0"+
    "\32\31\5\0\10\31\1\376\16\31\27\0\1\31\5\0"+
    "\32\31\5\0\14\31\1\377\12\31\27\0\1\31\5\0"+
    "\32\31\5\0\4\31\1\u0100\22\31\10\0\1\u0101\16\0"+
    "\1\31\5\0\32\31\5\0\27\31\104\0\1\u0102\45\0"+
    "\1\31\5\0\32\31\5\0\7\31\1\u0103\17\31\27\0"+
    "\1\u0104\5\0\6\u0104\31\0\6\u0104\50\0\1\u0105\116\0"+
    "\1\333\3\0\1\u0106\122\0\1\u0107\116\0\1\335\3\0"+
    "\1\u0108\122\0\1\31\5\0\25\31\1\u0109\4\31\5\0"+
    "\27\31\27\0\1\31\5\0\3\31\1\u010a\26\31\5\0"+
    "\27\31\27\0\1\31\5\0\4\31\1\u010b\25\31\5\0"+
    "\27\31\55\0\1\u010c\74\0\1\31\5\0\16\31\1\u010d"+
    "\13\31\5\0\27\31\27\0\1\31\5\0\17\31\1\u010e"+
    "\12\31\5\0\27\31\55\0\1\u010f\74\0\1\31\5\0"+
    "\4\31\1\u0110\25\31\5\0\27\31\57\0\1\u0111\72\0"+
    "\1\31\5\0\16\31\1\u0112\13\31\5\0\27\31\27\0"+
    "\1\31\5\0\23\31\1\u0113\6\31\5\0\27\31\27\0"+
    "\1\31\5\0\2\31\1\u0114\27\31\5\0\27\31\27\0"+
    "\1\31\5\0\26\31\1\u0115\3\31\5\0\27\31\27\0"+
    "\1\31\5\0\32\31\5\0\17\31\1\u0116\7\31\27\0"+
    "\1\31\5\0\32\31\5\0\17\31\1\u0117\7\31\27\0"+
    "\1\31\5\0\32\31\5\0\14\31\1\u0118\12\31\27\0"+
    "\1\31\5\0\32\31\5\0\2\31\1\u0119\24\31\27\0"+
    "\1\31\5\0\32\31\5\0\14\31\1\u011a\12\31\101\0"+
    "\1\u011b\50\0\1\31\5\0\32\31\5\0\21\31\1\u011c"+
    "\5\31\27\0\1\31\5\0\32\31\5\0\17\31\1\u011d"+
    "\7\31\27\0\1\31\5\0\32\31\5\0\14\31\1\u011e"+
    "\12\31\27\0\1\31\5\0\32\31\5\0\21\31\1\u011f"+
    "\5\31\27\0\1\31\5\0\27\31\1\u0120\1\u0121\1\31"+
    "\5\0\27\31\27\0\1\31\5\0\32\31\5\0\1\u0122"+
    "\26\31\27\0\1\31\5\0\32\31\5\0\6\31\1\u0123"+
    "\20\31\27\0\1\31\5\0\32\31\5\0\20\31\1\u0124"+
    "\6\31\114\0\1\u0125\122\0\1\u0126\35\0\1\u0127\5\0"+
    "\6\u0127\31\0\6\u0127\41\0\1\u0128\6\0\1\u0129\116\0"+
    "\1\333\126\0\1\u012a\3\0\1\u012b\112\0\1\335\126\0"+
    "\1\31\5\0\4\31\1\u012c\25\31\5\0\27\31\61\0"+
    "\1\u012d\70\0\1\31\5\0\15\31\1\u012e\14\31\5\0"+
    "\27\31\27\0\1\31\5\0\13\31\1\u012f\16\31\5\0"+
    "\27\31\61\0\1\u0130\102\0\1\u0131\110\0\1\31\5\0"+
    "\15\31\1\u0132\14\31\5\0\27\31\27\0\1\31\5\0"+
    "\32\31\4\0\1\u0133\27\31\27\0\1\31\5\0\1\u0134"+
    "\31\31\5\0\27\31\27\0\1\31\5\0\32\31\5\0"+
    "\15\31\1\u0135\11\31\27\0\1\31\5\0\32\31\5\0"+
    "\21\31\1\u0136\5\31\27\0\1\31\5\0\32\31\5\0"+
    "\21\31\1\u0137\5\31\27\0\1\31\5\0\32\31\5\0"+
    "\21\31\1\u0138\5\31\74\0\1\u0139\55\0\1\31\5\0"+
    "\32\31\5\0\20\31\1\u013a\6\31\27\0\1\31\5\0"+
    "\32\31\5\0\1\u013b\26\31\27\0\1\31\5\0\32\31"+
    "\5\0\12\31\1\u013c\14\31\104\0\1\u013d\111\0\1\u013e"+
    "\47\0\1\u0128\6\0\1\u013f\122\0\1\u0140\3\0\1\u012b"+
    "\130\0\1\u0141\110\0\1\31\5\0\23\31\1\u0142\6\31"+
    "\5\0\27\31\27\0\1\31\5\0\4\31\1\u0143\25\31"+
    "\5\0\27\31\41\0\1\u0144\137\0\1\u0145\121\0\1\u0146"+
    "\74\0\1\31\5\0\13\31\1\u0147\16\31\5\0\27\31"+
    "\27\0\1\31\5\0\32\31\5\0\22\31\1\u0148\4\31"+
    "\27\0\1\31\5\0\32\31\5\0\20\31\1\u0149\6\31"+
    "\107\0\1\u014a\42\0\1\31\5\0\32\31\5\0\21\31"+
    "\1\u014b\5\31\122\0\1\u014c\115\0\1\u014d\25\0\1\u0128"+
    "\135\0\1\u012b\146\0\1\u014e\72\0\1\31\5\0\1\u014f"+
    "\31\31\5\0\27\31\27\0\1\31\5\0\32\31\4\0"+
    "\1\u0150\27\31\57\0\1\u0151\110\0\1\u0152\136\0\1\u0153"+
    "\70\0\1\31\5\0\32\31\5\0\14\31\1\u0154\12\31"+
    "\104\0\1\u0155\45\0\1\31\5\0\32\31\5\0\10\31"+
    "\1\u0156\16\31\100\0\1\u0157\125\0\1\u0158\77\0\1\u0159"+
    "\71\0\1\31\5\0\13\31\1\u015a\16\31\5\0\27\31"+
    "\55\0\1\u015b\125\0\1\u015c\104\0\1\u015d\121\0\1\u015e"+
    "\110\0\1\31\5\0\32\31\5\0\3\31\1\u015f\23\31"+
    "\106\0\1\u0160\43\0\1\31\5\0\32\31\5\0\15\31"+
    "\1\u0161\11\31\74\0\1\u0162\73\0\1\u0163\136\0\1\u0164"+
    "\106\0\1\u0165\134\0\1\u0166\53\0\1\u0167\16\0\1\31"+
    "\5\0\32\31\5\0\27\31\121\0\1\u0168\30\0\1\31"+
    "\5\0\32\31\5\0\14\31\1\u0169\12\31\115\0\1\u016a"+
    "\60\0\1\u016b\110\0\1\u016c\134\0\1\u016d\127\0\1\u016e"+
    "\140\0\1\u016f\117\0\1\u0170\101\0\1\u0171\127\0\1\u0172"+
    "\115\0\1\u0173\115\0\1\u0174\166\0\1\u0175\123\0\1\u0176"+
    "\70\0\1\u0177\115\0\1\u0178\155\0\1\u0179\125\0\1\u017a"+
    "\56\0\1\u017b\127\0\1\u017c\161\0\1\u017d\116\0\1\u017e"+
    "\70\0\1\u017f\162\0\1\u0180\107\0\1\u0181\74\0\1\u0182"+
    "\157\0\1\u0183\124\0\1\u0184\121\0\1\u0185\16\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[25896];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\4\1\1\11\2\1\5\11"+
    "\3\1\1\11\3\1\1\11\23\1\3\11\15\1\1\11"+
    "\1\1\3\11\1\0\1\11\2\0\1\11\1\0\1\11"+
    "\3\0\3\11\50\1\1\11\4\0\1\1\2\0\54\1"+
    "\3\0\1\11\2\0\50\1\1\0\1\1\5\0\4\1"+
    "\1\0\3\1\1\0\1\1\1\0\15\1\1\0\11\1"+
    "\2\0\1\1\5\0\3\1\1\0\2\1\1\0\1\1"+
    "\1\0\11\1\1\0\11\1\2\0\2\11\2\0\1\11"+
    "\1\1\1\0\2\1\2\0\1\1\1\0\5\1\1\0"+
    "\3\1\5\0\2\1\3\0\3\1\1\0\1\1\3\0"+
    "\1\1\4\0\1\1\1\0\1\1\1\11\2\0\1\1"+
    "\2\0\1\11\1\0\1\1\1\0\1\1\6\0\1\11"+
    "\1\1\7\0\1\11\1\0\1\11\10\0\1\11\3\0"+
    "\1\11\1\0\1\11\2\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[389];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
private void printToken(String tipo) {
      System.out.println(
              "Token: " + tipo +
              " | Lexema: " + yytext() +
              " | Linea: " + (yyline + 1) +
              " | Columna: " + (yycolumn + 1)
      );
}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
  //constructor
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public int yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
              {
                System.out.println("final del archivo");
                                    return YYEOF;
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("ERROR Lexico: " + yytext() +
                                                            " | Linea: " + (yyline+1) +
                                                            " | Columna: " + (yycolumn+ 1));
            }
          // fall through
          case 87: break;
          case 2:
            { /*ignorar termporalmente*/
            }
          // fall through
          case 88: break;
          case 3:
            { System.out.print(yytext());
            }
          // fall through
          case 89: break;
          case 4:
            { /*comentario de una linea*/
            }
          // fall through
          case 90: break;
          case 5:
            { printToken("MODULO");
            }
          // fall through
          case 91: break;
          case 6:
            { printToken("PARENTESIS_ABRE");
            }
          // fall through
          case 92: break;
          case 7:
            { printToken("PARENTESIS_CIERRA");
            }
          // fall through
          case 93: break;
          case 8:
            { printToken("MULTIPLICACION");
            }
          // fall through
          case 94: break;
          case 9:
            { printToken("SUMA");
            }
          // fall through
          case 95: break;
          case 10:
            { printToken("COMA");
            }
          // fall through
          case 96: break;
          case 11:
            { printToken("RESTA");
            }
          // fall through
          case 97: break;
          case 12:
            { printToken("DIVISION");
            }
          // fall through
          case 98: break;
          case 13:
            { printToken("NUMERO");
            }
          // fall through
          case 99: break;
          case 14:
            { printToken("DOS_PUNTOS");
            }
          // fall through
          case 100: break;
          case 15:
            { printToken("MENOR");
            }
          // fall through
          case 101: break;
          case 16:
            { printToken("ASIGNACION");
            }
          // fall through
          case 102: break;
          case 17:
            { printToken("MAYOR");
            }
          // fall through
          case 103: break;
          case 18:
            { printToken("COMODIN");
            }
          // fall through
          case 104: break;
          case 19:
            { printToken("IDENTIFICADOR");
            }
          // fall through
          case 105: break;
          case 20:
            { printToken("LCOR");
            }
          // fall through
          case 106: break;
          case 21:
            { printToken("RCOR");
            }
          // fall through
          case 107: break;
          case 22:
            { printToken("POTENCIA");
            }
          // fall through
          case 108: break;
          case 23:
            { printToken("LKEY");
            }
          // fall through
          case 109: break;
          case 24:
            { printToken("RKEY");
            }
          // fall through
          case 110: break;
          case 25:
            { printToken("NEGACION");
            }
          // fall through
          case 111: break;
          case 26:
            { printToken("DIFERENTE");
            }
          // fall through
          case 112: break;
          case 27:
            { printToken("CADENA");
            }
          // fall through
          case 113: break;
          case 28:
            { printToken("AND");
            }
          // fall through
          case 114: break;
          case 29:
            { printToken("RANGO");
            }
          // fall through
          case 115: break;
          case 30:
            { printToken("MENOR_IGUAL");
            }
          // fall through
          case 116: break;
          case 31:
            { printToken("IGUALDAD");
            }
          // fall through
          case 117: break;
          case 32:
            { printToken("MAYOR_IGUAL");
            }
          // fall through
          case 118: break;
          case 33:
            { printToken("DO");
            }
          // fall through
          case 119: break;
          case 34:
            { printToken("IF");
            }
          // fall through
          case 120: break;
          case 35:
            { printToken("IN");
            }
          // fall through
          case 121: break;
          case 36:
            { printToken("OR");
            }
          // fall through
          case 122: break;
          case 37:
            { printToken("FOR");
            }
          // fall through
          case 123: break;
          case 38:
            { printToken("RED");
            }
          // fall through
          case 124: break;
          case 39:
            { printToken("SKY");
            }
          // fall through
          case 125: break;
          case 40:
            { /* comentario multilínea */
            }
          // fall through
          case 126: break;
          case 41:
            { printToken("BLUE");
            }
          // fall through
          case 127: break;
          case 42:
            { printToken("ELSE");
            }
          // fall through
          case 128: break;
          case 43:
            { printToken("LINE");
            }
          // fall through
          case 129: break;
          case 44:
            { printToken("MONO");
            }
          // fall through
          case 130: break;
          case 45:
            { printToken("TEXT");
            }
          // fall through
          case 131: break;
          case 46:
            { printToken("BLACK");
            }
          // fall through
          case 132: break;
          case 47:
            { printToken("GREEN");
            }
          // fall through
          case 133: break;
          case 48:
            { printToken("TABLE");
            }
          // fall through
          case 134: break;
          case 49:
            { printToken("WHILE");
            }
          // fall through
          case 135: break;
          case 50:
            { printToken("WHITE");
            }
          // fall through
          case 136: break;
          case 51:
            { printToken("color");
            }
          // fall through
          case 137: break;
          case 52:
            { printToken("label");
            }
          // fall through
          case 138: break;
          case 53:
            { printToken("width");
            }
          // fall through
          case 139: break;
          case 54:
            { printToken("DOTTED");
            }
          // fall through
          case 140: break;
          case 55:
            { printToken("DOUBLE");
            }
          // fall through
          case 141: break;
          case 56:
            { printToken("PURPLE");
            }
          // fall through
          case 142: break;
          case 57:
            { printToken("YELLOW");
            }
          // fall through
          case 143: break;
          case 58:
            { printToken("border");
            }
          // fall through
          case 144: break;
          case 59:
            { printToken("height");
            }
          // fall through
          case 145: break;
          case 60:
            { printToken("number");
            }
          // fall through
          case 146: break;
          case 61:
            { printToken("pointX");
            }
          // fall through
          case 147: break;
          case 62:
            { printToken("pointY");
            }
          // fall through
          case 148: break;
          case 63:
            { printToken("string");
            }
          // fall through
          case 149: break;
          case 64:
            { printToken("styles");
            }
          // fall through
          case 150: break;
          case 65:
            { printToken("HEX_COLOR");
            }
          // fall through
          case 151: break;
          case 66:
            { printToken("RGB_COLOR");
            }
          // fall through
          case 152: break;
          case 67:
            { printToken("HSL_COLOR");
            }
          // fall through
          case 153: break;
          case 68:
            { printToken("CURSIVE");
            }
          // fall through
          case 154: break;
          case 69:
            { printToken("SECTION");
            }
          // fall through
          case 155: break;
          case 70:
            { printToken("content");
            }
          // fall through
          case 156: break;
          case 71:
            { printToken("correct");
            }
          // fall through
          case 157: break;
          case 72:
            { printToken("options");
            }
          // fall through
          case 158: break;
          case 73:
            { printToken("special");
            }
          // fall through
          case 159: break;
          case 74:
            { printToken("VERTICAL");
            }
          // fall through
          case 160: break;
          case 75:
            { printToken("elements");
            }
          // fall through
          case 161: break;
          case 76:
            { printToken("text_size");
            }
          // fall through
          case 162: break;
          case 77:
            { printToken("HORIZONTAL");
            }
          // fall through
          case 163: break;
          case 78:
            { printToken("SANS_SERIF");
            }
          // fall through
          case 164: break;
          case 79:
            { printToken("font_family");
            }
          // fall through
          case 165: break;
          case 80:
            { printToken("orientation");
            }
          // fall through
          case 166: break;
          case 81:
            { printToken("DROP_QUESTION");
            }
          // fall through
          case 167: break;
          case 82:
            { printToken("OPEN_QUESTION");
            }
          // fall through
          case 168: break;
          case 83:
            { printToken("SELECT_QUESTION");
            }
          // fall through
          case 169: break;
          case 84:
            { printToken("background_color");
            }
          // fall through
          case 170: break;
          case 85:
            { printToken("MULTIPLE_QUESTION");
            }
          // fall through
          case 171: break;
          case 86:
            { printToken("who_is_that_pokemon");
            }
          // fall through
          case 172: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java Lexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Lexer scanner = null;
        java.io.FileInputStream stream = null;
        java.io.Reader reader = null;
        try {
          stream = new java.io.FileInputStream(argv[i]);
          reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Lexer(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
        finally {
          if (reader != null) {
            try {
              reader.close();
            }
            catch (java.io.IOException e) {
              System.out.println("IO error closing file \""+argv[i]+"\"");
              System.out.println(e);
            }
          }
          if (stream != null) {
            try {
              stream.close();
            }
            catch (java.io.IOException e) {
              System.out.println("IO error closing file \""+argv[i]+"\"");
              System.out.println(e);
            }
          }
        }
      }
    }
  }


}
