// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: /home/herson/Repositorios Git/Proyecto1_Compi1/Proyecto1_Compi1/app/src/main/Flex/Lexer.flex

package com.example.proyecto1_compi1.Analizadores;
//imports
import com.example.proyecto1_compi1.models.ErrorLexico;
import java.util.ArrayList;
import java.util.List;
import java_cup.runtime.Symbol;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\0\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\3\24\1\25"+
    "\6\24\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\1\55\1\56\1\57\1\60\1\61\1\62\1\63\1\64"+
    "\1\65\1\66\1\67\1\0\1\70\1\71\1\72\1\0"+
    "\1\73\1\74\1\75\1\76\1\77\1\100\1\101\1\102"+
    "\1\103\1\46\1\104\1\105\1\106\1\107\1\110\1\111"+
    "\1\46\1\112\1\113\1\114\1\115\1\46\1\116\1\117"+
    "\1\120\1\121\1\122\1\123\1\124\1\125\6\0\1\3"+
    "\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\1\1\3\1\1\1\4\1\5"+
    "\1\1\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\24\25\1\26\1\27\1\30\13\25\1\31\1\1\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\5\0\1\41"+
    "\1\42\4\0\1\43\1\44\1\45\2\25\1\46\5\25"+
    "\1\47\23\25\1\50\11\25\1\51\10\0\1\16\3\0"+
    "\7\25\1\52\10\25\1\53\3\25\1\54\24\25\10\0"+
    "\1\55\1\0\1\25\1\56\4\25\1\57\2\25\1\60"+
    "\1\61\10\25\1\62\6\25\1\63\14\25\21\0\1\64"+
    "\4\25\1\65\10\25\1\66\1\25\1\67\1\70\5\25"+
    "\1\71\10\25\1\72\1\73\1\74\7\0\1\75\1\76"+
    "\7\0\1\25\1\77\1\100\3\25\1\101\1\25\1\102"+
    "\4\25\1\103\3\25\1\104\1\105\2\25\1\106\1\107"+
    "\1\25\1\110\1\111\1\25\10\0\1\112\2\0\1\113"+
    "\2\0\1\114\1\115\5\25\1\116\2\25\1\117\1\120"+
    "\1\25\1\121\1\25\1\122\1\25\1\123\6\0\1\124"+
    "\2\0\6\25\1\125\1\126\2\25\10\0\10\25\5\0"+
    "\1\127\3\0\1\25\1\130\2\25\1\131\3\25\1\0"+
    "\1\132\1\133\2\0\1\134\4\25\1\135\1\25\3\0"+
    "\5\25\1\0\1\136\1\137\1\25\1\140\2\25\1\0"+
    "\3\25\1\0\1\25\1\141\1\25\1\0\2\25\1\0"+
    "\1\142\1\25\1\143\1\25\1\144";

  private static int [] zzUnpackAction() {
    int [] result = new int[446];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\126\0\254\0\u0102\0\u0158\0\u01ae\0\u0204\0\u025a"+
    "\0\254\0\u02b0\0\254\0\254\0\254\0\254\0\254\0\254"+
    "\0\u0306\0\u035c\0\u03b2\0\254\0\254\0\u0408\0\u045e\0\u04b4"+
    "\0\254\0\u050a\0\u0560\0\u05b6\0\u060c\0\u0662\0\u06b8\0\u070e"+
    "\0\u0764\0\u07ba\0\u0810\0\u0866\0\u08bc\0\u0912\0\u0968\0\u09be"+
    "\0\u0a14\0\u0a6a\0\u0ac0\0\u0b16\0\u0b6c\0\254\0\254\0\254"+
    "\0\u0bc2\0\u0c18\0\u0c6e\0\u0cc4\0\u0d1a\0\u0d70\0\u0dc6\0\u0e1c"+
    "\0\u0e72\0\u0ec8\0\u0f1e\0\254\0\u0f74\0\254\0\254\0\u0fca"+
    "\0\254\0\254\0\u1020\0\254\0\u1076\0\u10cc\0\u1122\0\u1178"+
    "\0\u11ce\0\254\0\254\0\u1224\0\u127a\0\u12d0\0\u1326\0\254"+
    "\0\254\0\254\0\u137c\0\u13d2\0\u1428\0\u147e\0\u14d4\0\u152a"+
    "\0\u1580\0\u15d6\0\u050a\0\u162c\0\u1682\0\u16d8\0\u172e\0\u1784"+
    "\0\u17da\0\u1830\0\u1886\0\u18dc\0\u1932\0\u1988\0\u19de\0\u1a34"+
    "\0\u1a8a\0\u1ae0\0\u1b36\0\u1b8c\0\u1be2\0\u1c38\0\u050a\0\u1c8e"+
    "\0\u1ce4\0\u1d3a\0\u1d90\0\u1de6\0\u1e3c\0\u1e92\0\u1ee8\0\u1f3e"+
    "\0\254\0\u1f94\0\u1fea\0\u2040\0\u2096\0\u20ec\0\u2142\0\u2198"+
    "\0\u21ee\0\u127a\0\u2244\0\u229a\0\u22f0\0\u2346\0\u239c\0\u23f2"+
    "\0\u2448\0\u249e\0\u24f4\0\u254a\0\u050a\0\u25a0\0\u25f6\0\u264c"+
    "\0\u26a2\0\u26f8\0\u274e\0\u27a4\0\u27fa\0\u050a\0\u2850\0\u28a6"+
    "\0\u28fc\0\u050a\0\u2952\0\u29a8\0\u29fe\0\u2a54\0\u2aaa\0\u2b00"+
    "\0\u2b56\0\u2bac\0\u2c02\0\u2c58\0\u2cae\0\u2d04\0\u2d5a\0\u2db0"+
    "\0\u2e06\0\u2e5c\0\u2eb2\0\u2f08\0\u2f5e\0\u2fb4\0\u300a\0\u3060"+
    "\0\u30b6\0\u310c\0\u3162\0\u31b8\0\u320e\0\u3264\0\254\0\u32ba"+
    "\0\u3310\0\u050a\0\u3366\0\u33bc\0\u3412\0\u3468\0\u050a\0\u34be"+
    "\0\u3514\0\u050a\0\u050a\0\u356a\0\u35c0\0\u3616\0\u366c\0\u36c2"+
    "\0\u3718\0\u376e\0\u37c4\0\u050a\0\u381a\0\u3870\0\u38c6\0\u391c"+
    "\0\u3972\0\u39c8\0\u050a\0\u3a1e\0\u3a74\0\u3aca\0\u3b20\0\u3b76"+
    "\0\u3bcc\0\u3c22\0\u3c78\0\u3cce\0\u3d24\0\u3d7a\0\u3dd0\0\u3e26"+
    "\0\u3e7c\0\u3ed2\0\u3f28\0\u3f7e\0\u3fd4\0\u402a\0\u4080\0\u40d6"+
    "\0\u412c\0\u4182\0\u41d8\0\u422e\0\u4284\0\u42da\0\u4330\0\u4386"+
    "\0\u050a\0\u43dc\0\u4432\0\u4488\0\u44de\0\u050a\0\u4534\0\u458a"+
    "\0\u45e0\0\u4636\0\u468c\0\u46e2\0\u4738\0\u478e\0\u050a\0\u47e4"+
    "\0\u050a\0\u050a\0\u483a\0\u4890\0\u48e6\0\u493c\0\u4992\0\u050a"+
    "\0\u49e8\0\u4a3e\0\u4a94\0\u4aea\0\u4b40\0\u4b96\0\u4bec\0\u4c42"+
    "\0\u050a\0\254\0\254\0\u4c98\0\u4cee\0\u4d44\0\u4d9a\0\u4df0"+
    "\0\u4e46\0\u4e9c\0\254\0\254\0\u4ef2\0\u4f48\0\u4f9e\0\u4ff4"+
    "\0\u504a\0\u50a0\0\u50f6\0\u514c\0\u050a\0\u050a\0\u51a2\0\u51f8"+
    "\0\u524e\0\u050a\0\u52a4\0\u050a\0\u52fa\0\u5350\0\u53a6\0\u53fc"+
    "\0\u050a\0\u5452\0\u54a8\0\u54fe\0\u050a\0\u050a\0\u5554\0\u55aa"+
    "\0\u050a\0\u050a\0\u5600\0\u050a\0\u050a\0\u5656\0\u56ac\0\u5702"+
    "\0\u5758\0\u57ae\0\u5804\0\u585a\0\u58b0\0\u5906\0\254\0\u595c"+
    "\0\u59b2\0\254\0\u5a08\0\u5a5e\0\254\0\u050a\0\u5ab4\0\u5b0a"+
    "\0\u5b60\0\u5bb6\0\u5c0c\0\u050a\0\u5c62\0\u5cb8\0\u050a\0\u050a"+
    "\0\u5d0e\0\u050a\0\u5d64\0\u050a\0\u5dba\0\254\0\u5e10\0\u5e66"+
    "\0\u5ebc\0\u5f12\0\u5f68\0\u5fbe\0\254\0\u6014\0\u606a\0\u60c0"+
    "\0\u6116\0\u616c\0\u61c2\0\u6218\0\u626e\0\u050a\0\u050a\0\u62c4"+
    "\0\u631a\0\u6370\0\u63c6\0\u641c\0\u6472\0\u64c8\0\u651e\0\u6574"+
    "\0\u65ca\0\u6620\0\u6676\0\u66cc\0\u6722\0\u6778\0\u67ce\0\u6824"+
    "\0\u687a\0\u68d0\0\u6926\0\u697c\0\u69d2\0\u6a28\0\254\0\u6a7e"+
    "\0\u6ad4\0\u6b2a\0\u6b80\0\u050a\0\u6bd6\0\u6c2c\0\u050a\0\u6c82"+
    "\0\u6cd8\0\u6d2e\0\u6d84\0\254\0\254\0\u6dda\0\u6e30\0\254"+
    "\0\u6e86\0\u6edc\0\u6f32\0\u6f88\0\u050a\0\u6fde\0\u7034\0\u708a"+
    "\0\u70e0\0\u7136\0\u718c\0\u71e2\0\u7238\0\u728e\0\u72e4\0\254"+
    "\0\u050a\0\u733a\0\u050a\0\u7390\0\u73e6\0\u743c\0\u7492\0\u74e8"+
    "\0\u753e\0\u7594\0\u75ea\0\u050a\0\u7640\0\u7696\0\u76ec\0\u7742"+
    "\0\u7798\0\u050a\0\u77ee\0\254\0\u7844\0\u050a";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[446];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\0\2\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\2\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\3\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\2\32\1\43\1\44\1\45\1\46"+
    "\1\47\1\32\1\50\1\51\1\52\1\32\1\53\1\54"+
    "\1\32\1\55\1\32\1\56\1\57\1\60\3\32\1\61"+
    "\1\62\1\63\2\32\1\64\1\65\1\32\1\66\1\32"+
    "\1\67\1\70\1\71\1\32\1\72\2\32\1\73\3\32"+
    "\1\74\1\75\1\76\1\77\2\100\1\101\4\100\1\102"+
    "\24\100\1\103\71\100\127\0\2\4\1\0\2\4\126\0"+
    "\1\104\213\0\1\105\1\106\2\0\1\107\13\0\1\110"+
    "\35\0\2\111\7\0\6\111\30\0\6\111\25\0\2\10"+
    "\1\0\123\10\13\0\1\112\134\0\1\113\121\0\1\114"+
    "\131\0\1\115\1\0\2\23\101\0\1\116\3\0\1\116"+
    "\16\0\2\117\3\0\1\120\125\0\1\121\125\0\1\122"+
    "\120\0\2\32\7\0\32\32\3\0\30\32\30\0\2\32"+
    "\7\0\13\32\1\123\16\32\3\0\30\32\30\0\2\32"+
    "\7\0\24\32\1\124\5\32\3\0\30\32\30\0\2\32"+
    "\7\0\16\32\1\125\2\32\1\126\10\32\3\0\30\32"+
    "\30\0\2\32\7\0\13\32\1\127\16\32\3\0\30\32"+
    "\30\0\2\32\7\0\16\32\1\130\13\32\3\0\30\32"+
    "\30\0\2\32\7\0\21\32\1\131\10\32\3\0\30\32"+
    "\30\0\2\32\7\0\16\32\1\132\13\32\3\0\30\32"+
    "\30\0\2\32\7\0\5\32\1\133\24\32\3\0\30\32"+
    "\30\0\2\32\7\0\10\32\1\134\21\32\3\0\30\32"+
    "\30\0\2\32\7\0\16\32\1\135\5\32\1\136\5\32"+
    "\3\0\30\32\30\0\2\32\7\0\24\32\1\137\5\32"+
    "\3\0\30\32\30\0\2\32\7\0\17\32\1\140\12\32"+
    "\3\0\30\32\30\0\2\32\7\0\24\32\1\141\5\32"+
    "\3\0\30\32\30\0\2\32\7\0\4\32\1\142\25\32"+
    "\3\0\30\32\30\0\2\32\7\0\1\143\3\32\1\144"+
    "\5\32\1\145\17\32\3\0\30\32\30\0\2\32\7\0"+
    "\1\146\3\32\1\147\25\32\3\0\30\32\30\0\2\32"+
    "\7\0\4\32\1\150\25\32\3\0\30\32\30\0\2\32"+
    "\7\0\7\32\1\151\22\32\3\0\30\32\30\0\2\32"+
    "\7\0\4\32\1\152\25\32\3\0\30\32\30\0\2\32"+
    "\7\0\32\32\3\0\16\32\1\153\11\32\30\0\2\32"+
    "\7\0\32\32\3\0\20\32\1\154\7\32\30\0\2\32"+
    "\7\0\32\32\3\0\13\32\1\155\14\32\30\0\2\32"+
    "\7\0\32\32\3\0\5\32\1\156\22\32\30\0\2\32"+
    "\7\0\32\32\3\0\15\32\1\157\12\32\30\0\2\32"+
    "\7\0\32\32\3\0\1\32\1\160\26\32\30\0\2\32"+
    "\7\0\32\32\3\0\23\32\1\161\4\32\30\0\2\32"+
    "\7\0\32\32\3\0\17\32\1\162\1\163\7\32\30\0"+
    "\2\32\7\0\32\32\3\0\16\32\1\164\11\32\30\0"+
    "\2\32\7\0\32\32\3\0\17\32\1\165\2\32\1\166"+
    "\5\32\30\0\2\32\7\0\32\32\3\0\10\32\1\167"+
    "\1\170\16\32\127\0\1\171\2\0\2\100\1\0\4\100"+
    "\1\0\24\100\1\0\71\100\67\0\1\172\131\0\1\173"+
    "\14\0\1\174\125\0\1\175\125\0\1\176\114\0\1\177"+
    "\52\0\2\200\7\0\6\200\30\0\6\200\25\0\16\114"+
    "\1\201\107\114\24\0\2\202\101\0\1\116\3\0\1\116"+
    "\16\0\2\117\101\0\1\203\3\0\1\203\12\0\1\204"+
    "\3\0\2\205\124\0\2\32\7\0\1\206\23\32\1\207"+
    "\5\32\3\0\30\32\30\0\2\32\7\0\21\32\1\210"+
    "\10\32\3\0\30\32\30\0\2\32\7\0\23\32\1\211"+
    "\1\212\5\32\3\0\30\32\30\0\2\32\7\0\16\32"+
    "\1\213\13\32\3\0\30\32\30\0\2\32\7\0\22\32"+
    "\1\214\7\32\3\0\30\32\30\0\2\32\7\0\21\32"+
    "\1\215\10\32\3\0\30\32\30\0\2\32\7\0\4\32"+
    "\1\216\25\32\3\0\30\32\30\0\2\32\7\0\21\32"+
    "\1\217\10\32\3\0\30\32\30\0\2\32\7\0\15\32"+
    "\1\220\14\32\3\0\30\32\30\0\2\32\7\0\15\32"+
    "\1\221\14\32\3\0\30\32\30\0\2\32\7\0\13\32"+
    "\1\222\16\32\3\0\30\32\30\0\2\32\7\0\14\32"+
    "\1\223\15\32\3\0\30\32\30\0\2\32\7\0\4\32"+
    "\1\224\25\32\3\0\30\32\30\0\2\32\7\0\21\32"+
    "\1\225\10\32\3\0\30\32\30\0\2\32\7\0\3\32"+
    "\1\226\26\32\3\0\30\32\30\0\2\32\7\0\15\32"+
    "\1\227\14\32\3\0\30\32\30\0\2\32\7\0\2\32"+
    "\1\230\10\32\1\231\16\32\3\0\30\32\30\0\2\32"+
    "\7\0\30\32\1\232\1\32\3\0\30\32\30\0\2\32"+
    "\7\0\1\32\1\233\30\32\3\0\30\32\30\0\2\32"+
    "\7\0\27\32\1\234\2\32\3\0\30\32\30\0\2\32"+
    "\7\0\21\32\1\235\10\32\3\0\30\32\30\0\2\32"+
    "\7\0\10\32\1\236\21\32\3\0\30\32\30\0\2\32"+
    "\7\0\13\32\1\237\16\32\3\0\30\32\30\0\2\32"+
    "\7\0\32\32\3\0\15\32\1\240\2\32\1\241\7\32"+
    "\30\0\2\32\7\0\32\32\3\0\1\32\1\242\26\32"+
    "\30\0\2\32\7\0\32\32\3\0\5\32\1\243\22\32"+
    "\30\0\2\32\7\0\32\32\3\0\11\32\1\244\16\32"+
    "\30\0\2\32\7\0\32\32\3\0\2\32\1\245\25\32"+
    "\30\0\2\32\7\0\32\32\3\0\14\32\1\246\13\32"+
    "\30\0\2\32\7\0\32\32\3\0\22\32\1\247\5\32"+
    "\30\0\2\32\7\0\32\32\3\0\11\32\1\250\16\32"+
    "\30\0\2\32\7\0\32\32\3\0\11\32\1\251\16\32"+
    "\30\0\2\32\7\0\32\32\3\0\5\32\1\252\22\32"+
    "\30\0\2\32\7\0\32\32\3\0\20\32\1\253\5\32"+
    "\1\254\1\32\30\0\2\32\7\0\32\32\3\0\16\32"+
    "\1\255\11\32\30\0\2\32\7\0\32\32\3\0\4\32"+
    "\1\256\23\32\32\0\1\257\1\0\1\260\172\0\1\261"+
    "\142\0\1\262\120\0\1\263\127\0\1\264\135\0\1\265"+
    "\32\0\2\266\7\0\6\266\30\0\6\266\25\0\16\114"+
    "\1\201\4\114\1\267\102\114\1\0\1\203\3\0\1\203"+
    "\12\0\1\204\106\0\1\204\3\0\1\204\16\0\2\270"+
    "\101\0\1\203\3\0\1\203\12\0\1\204\3\0\2\203"+
    "\124\0\2\32\7\0\2\32\1\271\27\32\3\0\30\32"+
    "\30\0\2\32\7\0\4\32\1\272\25\32\3\0\30\32"+
    "\30\0\2\32\7\0\22\32\1\273\7\32\3\0\30\32"+
    "\30\0\2\32\7\0\23\32\1\274\6\32\3\0\30\32"+
    "\30\0\2\32\7\0\1\32\1\275\30\32\3\0\30\32"+
    "\30\0\2\32\7\0\17\32\1\276\12\32\3\0\30\32"+
    "\30\0\2\32\7\0\4\32\1\277\25\32\3\0\30\32"+
    "\30\0\2\32\7\0\4\32\1\300\25\32\3\0\30\32"+
    "\30\0\2\32\7\0\10\32\1\301\21\32\3\0\30\32"+
    "\30\0\2\32\7\0\4\32\1\302\25\32\3\0\30\32"+
    "\30\0\2\32\7\0\16\32\1\303\13\32\3\0\30\32"+
    "\30\0\2\32\7\0\23\32\1\304\6\32\3\0\30\32"+
    "\30\0\2\32\7\0\1\32\1\305\30\32\3\0\30\32"+
    "\30\0\2\32\7\0\15\32\1\306\14\32\3\0\30\32"+
    "\30\0\2\32\7\0\17\32\1\307\12\32\3\0\30\32"+
    "\30\0\2\32\7\0\22\32\1\310\7\32\3\0\30\32"+
    "\30\0\2\32\7\0\23\32\1\311\6\32\3\0\30\32"+
    "\30\0\2\32\7\0\4\32\1\312\25\32\3\0\30\32"+
    "\30\0\2\32\7\0\13\32\1\313\16\32\3\0\30\32"+
    "\30\0\2\32\7\0\23\32\1\314\6\32\3\0\30\32"+
    "\30\0\2\32\7\0\23\32\1\315\6\32\3\0\30\32"+
    "\30\0\2\32\7\0\13\32\1\316\7\32\1\317\6\32"+
    "\3\0\30\32\30\0\2\32\7\0\13\32\1\320\16\32"+
    "\3\0\30\32\30\0\2\32\7\0\32\32\3\0\22\32"+
    "\1\321\5\32\30\0\2\32\7\0\32\32\3\0\20\32"+
    "\1\322\7\32\30\0\2\32\7\0\32\32\3\0\24\32"+
    "\1\323\3\32\30\0\2\32\7\0\32\32\3\0\14\32"+
    "\1\324\13\32\30\0\2\32\7\0\32\32\3\0\7\32"+
    "\1\325\20\32\30\0\2\32\7\0\32\32\3\0\5\32"+
    "\1\326\22\32\30\0\2\32\7\0\32\32\3\0\2\32"+
    "\1\327\25\32\30\0\2\32\7\0\32\32\3\0\11\32"+
    "\1\330\16\32\30\0\2\32\7\0\32\32\3\0\5\32"+
    "\1\331\22\32\30\0\2\32\7\0\32\32\3\0\15\32"+
    "\1\332\12\32\30\0\2\32\7\0\32\32\3\0\3\32"+
    "\1\333\24\32\30\0\2\32\7\0\32\32\3\0\11\32"+
    "\1\334\16\32\30\0\2\32\7\0\32\32\3\0\13\32"+
    "\1\335\14\32\30\0\2\32\7\0\32\32\3\0\1\336"+
    "\27\32\30\0\2\32\7\0\32\32\3\0\22\32\1\337"+
    "\5\32\20\0\1\340\1\341\53\0\1\342\3\0\1\343"+
    "\4\0\1\344\10\0\1\345\7\0\1\346\27\0\1\347"+
    "\2\0\1\260\201\0\1\350\117\0\1\351\137\0\1\352"+
    "\131\0\1\353\125\0\1\354\35\0\2\355\7\0\6\355"+
    "\30\0\6\355\26\0\1\356\3\0\1\356\12\0\1\357"+
    "\3\0\2\360\124\0\2\32\7\0\12\32\1\361\17\32"+
    "\3\0\30\32\30\0\2\32\7\0\10\32\1\362\21\32"+
    "\3\0\30\32\30\0\2\32\7\0\4\32\1\363\25\32"+
    "\3\0\30\32\30\0\2\32\7\0\13\32\1\364\16\32"+
    "\3\0\30\32\30\0\2\32\7\0\32\32\3\0\1\365"+
    "\27\32\30\0\2\32\7\0\15\32\1\366\14\32\3\0"+
    "\30\32\30\0\2\32\7\0\31\32\1\367\3\0\30\32"+
    "\30\0\2\32\7\0\10\32\1\370\21\32\3\0\30\32"+
    "\30\0\2\32\7\0\4\32\1\371\25\32\3\0\30\32"+
    "\30\0\2\32\7\0\32\32\3\0\1\372\27\32\30\0"+
    "\2\32\7\0\13\32\1\373\16\32\3\0\30\32\30\0"+
    "\2\32\7\0\32\32\3\0\1\374\27\32\30\0\2\32"+
    "\7\0\10\32\1\375\21\32\3\0\30\32\30\0\2\32"+
    "\7\0\2\32\1\376\27\32\3\0\30\32\30\0\2\32"+
    "\7\0\4\32\1\377\25\32\3\0\30\32\30\0\2\32"+
    "\7\0\10\32\1\u0100\21\32\3\0\30\32\30\0\2\32"+
    "\7\0\4\32\1\u0101\25\32\3\0\30\32\30\0\2\32"+
    "\7\0\4\32\1\u0102\25\32\3\0\30\32\30\0\2\32"+
    "\7\0\16\32\1\u0103\13\32\3\0\30\32\30\0\2\32"+
    "\7\0\32\32\3\0\5\32\1\u0104\22\32\30\0\2\32"+
    "\7\0\32\32\3\0\5\32\1\u0105\22\32\30\0\2\32"+
    "\7\0\32\32\3\0\5\32\1\u0106\22\32\30\0\2\32"+
    "\7\0\32\32\3\0\10\32\1\u0107\17\32\30\0\2\32"+
    "\7\0\32\32\3\0\13\32\1\u0108\14\32\30\0\2\32"+
    "\7\0\32\32\3\0\5\32\1\u0109\22\32\30\0\2\32"+
    "\7\0\32\32\3\0\16\32\1\u010a\11\32\30\0\2\32"+
    "\7\0\32\32\3\0\15\32\1\u010b\12\32\30\0\2\32"+
    "\7\0\32\32\3\0\22\32\1\u010c\5\32\30\0\2\32"+
    "\7\0\32\32\3\0\11\32\1\u010d\16\32\30\0\2\32"+
    "\7\0\32\32\3\0\15\32\1\u010e\12\32\30\0\2\32"+
    "\7\0\32\32\3\0\5\32\1\u010f\22\32\30\0\2\32"+
    "\7\0\32\32\3\0\11\32\1\u0110\16\32\30\0\2\32"+
    "\7\0\32\32\3\0\10\32\1\u0111\17\32\20\0\1\340"+
    "\53\0\1\u0112\52\0\1\341\52\0\1\u0113\126\0\1\u0114"+
    "\127\0\1\u0115\131\0\1\u0116\121\0\1\u0117\3\0\1\u0118"+
    "\6\0\1\u0119\5\0\1\u011a\101\0\1\u011b\32\0\1\346"+
    "\27\0\1\347\42\0\1\u011c\136\0\1\u011d\123\0\1\u011e"+
    "\140\0\1\u011f\20\0\1\u0120\125\0\1\u0121\144\0\2\u0122"+
    "\7\0\6\u0122\30\0\6\u0122\26\0\1\356\3\0\1\356"+
    "\12\0\1\357\106\0\1\357\3\0\1\357\16\0\2\u0123"+
    "\101\0\1\356\3\0\1\356\12\0\1\357\3\0\2\356"+
    "\124\0\2\32\7\0\25\32\1\u0124\4\32\3\0\30\32"+
    "\30\0\2\32\7\0\3\32\1\u0125\26\32\3\0\30\32"+
    "\30\0\2\32\7\0\4\32\1\u0126\25\32\3\0\30\32"+
    "\30\0\2\32\7\0\20\32\1\u0127\11\32\3\0\30\32"+
    "\30\0\2\32\7\0\16\32\1\u0128\13\32\3\0\30\32"+
    "\30\0\2\32\7\0\17\32\1\u0129\12\32\3\0\30\32"+
    "\30\0\2\32\7\0\21\32\1\u012a\10\32\3\0\30\32"+
    "\30\0\2\32\7\0\20\32\1\u012b\11\32\3\0\30\32"+
    "\30\0\2\32\7\0\4\32\1\u012c\25\32\3\0\30\32"+
    "\30\0\2\32\7\0\22\32\1\u012d\7\32\3\0\30\32"+
    "\30\0\2\32\7\0\16\32\1\u012e\13\32\3\0\30\32"+
    "\30\0\2\32\7\0\23\32\1\u012f\6\32\3\0\30\32"+
    "\30\0\2\32\7\0\2\32\1\u0130\27\32\3\0\30\32"+
    "\30\0\2\32\7\0\26\32\1\u0131\3\32\3\0\30\32"+
    "\30\0\2\32\7\0\32\32\3\0\15\32\1\u0132\12\32"+
    "\30\0\2\32\7\0\32\32\3\0\3\32\1\u0133\24\32"+
    "\30\0\2\32\7\0\32\32\3\0\15\32\1\u0134\12\32"+
    "\30\0\2\32\7\0\32\32\3\0\22\32\1\u0135\5\32"+
    "\30\0\2\32\7\0\32\32\3\0\20\32\1\u0136\7\32"+
    "\30\0\2\32\7\0\32\32\3\0\15\32\1\u0137\12\32"+
    "\30\0\2\32\7\0\32\32\3\0\22\32\1\u0138\5\32"+
    "\30\0\2\32\7\0\27\32\1\u0139\1\u013a\1\32\3\0"+
    "\30\32\30\0\2\32\7\0\32\32\3\0\1\32\1\u013b"+
    "\26\32\30\0\2\32\7\0\32\32\3\0\7\32\1\u013c"+
    "\20\32\30\0\2\32\7\0\32\32\3\0\21\32\1\u013d"+
    "\6\32\30\0\2\32\7\0\32\32\3\0\21\32\1\u013e"+
    "\6\32\32\0\1\u013f\213\0\1\u0114\104\0\1\u0140\130\0"+
    "\1\u0141\141\0\1\u0142\116\0\1\u0143\115\0\1\u0144\144\0"+
    "\1\u0145\125\0\1\u0146\22\0\1\u0147\216\0\1\u0148\140\0"+
    "\1\u0149\36\0\2\u014a\7\0\6\u014a\30\0\6\u014a\26\0"+
    "\1\u014b\3\0\1\u014b\16\0\2\u014c\4\0\1\u014d\117\0"+
    "\2\32\7\0\4\32\1\u014e\25\32\3\0\30\32\30\0"+
    "\2\32\7\0\24\32\1\u014f\5\32\3\0\30\32\30\0"+
    "\2\32\7\0\15\32\1\u0150\14\32\3\0\30\32\30\0"+
    "\2\32\7\0\13\32\1\u0151\16\32\3\0\30\32\30\0"+
    "\2\32\7\0\24\32\1\u0152\5\32\3\0\30\32\30\0"+
    "\2\32\7\0\4\32\1\u0153\25\32\3\0\30\32\30\0"+
    "\2\32\7\0\15\32\1\u0154\14\32\3\0\30\32\30\0"+
    "\2\32\7\0\32\32\3\0\1\u0155\27\32\30\0\2\32"+
    "\7\0\1\u0156\31\32\3\0\30\32\30\0\2\32\7\0"+
    "\32\32\3\0\22\32\1\u0157\5\32\30\0\2\32\7\0"+
    "\32\32\3\0\22\32\1\u0158\5\32\30\0\2\32\7\0"+
    "\32\32\3\0\22\32\1\u0159\5\32\30\0\2\32\7\0"+
    "\32\32\3\0\21\32\1\u015a\6\32\30\0\2\32\7\0"+
    "\32\32\3\0\1\32\1\u015b\26\32\30\0\2\32\7\0"+
    "\32\32\3\0\13\32\1\u015c\14\32\30\0\2\32\7\0"+
    "\32\32\3\0\1\u015d\27\32\74\0\1\u015e\147\0\1\u015f"+
    "\41\0\1\u0160\202\0\1\u0161\127\0\1\u0162\132\0\1\u0163"+
    "\123\0\1\u0164\24\0\1\u0165\211\0\1\u0166\135\0\1\u0167"+
    "\23\0\1\u014b\3\0\1\u014b\24\0\1\u014d\74\0\1\u014b"+
    "\3\0\1\u014b\16\0\2\u014b\4\0\1\u014d\117\0\2\32"+
    "\7\0\4\32\1\u0168\25\32\3\0\30\32\30\0\2\32"+
    "\7\0\23\32\1\u0169\6\32\3\0\30\32\30\0\2\32"+
    "\7\0\4\32\1\u016a\25\32\3\0\30\32\30\0\2\32"+
    "\7\0\4\32\1\u016b\25\32\3\0\30\32\30\0\2\32"+
    "\7\0\21\32\1\u016c\10\32\3\0\30\32\30\0\2\32"+
    "\7\0\20\32\1\u016d\11\32\3\0\30\32\30\0\2\32"+
    "\7\0\13\32\1\u016e\16\32\3\0\30\32\30\0\2\32"+
    "\7\0\32\32\3\0\21\32\1\u016f\6\32\30\0\2\32"+
    "\7\0\32\32\3\0\22\32\1\u0170\5\32\30\0\2\32"+
    "\7\0\32\32\3\0\22\32\1\u0171\5\32\120\0\1\u0172"+
    "\101\0\1\u0112\145\0\1\u0173\114\0\1\u0174\47\0\1\u0175"+
    "\4\0\1\u0176\214\0\1\u0177\116\0\1\u0178\140\0\1\u0179"+
    "\30\0\2\32\7\0\22\32\1\u017a\7\32\3\0\30\32"+
    "\30\0\2\32\7\0\1\u017b\31\32\3\0\30\32\30\0"+
    "\2\32\7\0\32\32\3\0\1\u017c\27\32\30\0\2\32"+
    "\7\0\22\32\1\u017d\7\32\3\0\30\32\30\0\2\32"+
    "\7\0\10\32\1\u017e\21\32\3\0\30\32\30\0\2\32"+
    "\7\0\24\32\1\u017f\5\32\3\0\30\32\30\0\2\32"+
    "\7\0\32\32\3\0\11\32\1\u0180\16\32\30\0\2\32"+
    "\7\0\32\32\3\0\10\32\1\u0181\17\32\32\0\1\u0182"+
    "\214\0\1\u0183\36\0\1\u0184\123\0\2\u0185\124\0\2\u0186"+
    "\42\0\1\u0187\144\0\1\u0188\121\0\1\u0189\121\0\1\u018a"+
    "\52\0\2\32\7\0\23\32\1\u018b\6\32\3\0\30\32"+
    "\30\0\2\32\7\0\13\32\1\u018c\16\32\3\0\30\32"+
    "\30\0\2\32\7\0\20\32\1\u018d\11\32\3\0\30\32"+
    "\30\0\2\32\7\0\23\32\1\u018e\6\32\3\0\30\32"+
    "\30\0\2\32\7\0\5\32\1\u018f\24\32\3\0\30\32"+
    "\30\0\2\32\7\0\4\32\1\u0190\25\32\3\0\30\32"+
    "\30\0\2\32\7\0\32\32\3\0\16\32\1\u0191\11\32"+
    "\30\0\2\32\7\0\32\32\3\0\1\32\1\u0192\26\32"+
    "\74\0\1\u011c\150\0\1\u0193\102\0\1\u0113\61\0\2\u0185"+
    "\42\0\1\u0194\61\0\2\u0186\42\0\1\u0195\133\0\1\u0196"+
    "\134\0\1\u0197\27\0\1\u0198\142\0\2\32\7\0\10\32"+
    "\1\u0199\21\32\3\0\30\32\30\0\2\32\7\0\24\32"+
    "\1\u019a\5\32\3\0\30\32\30\0\2\32\7\0\10\32"+
    "\1\u019b\21\32\3\0\30\32\30\0\2\32\7\0\22\32"+
    "\1\u019c\7\32\3\0\30\32\30\0\2\32\7\0\32\32"+
    "\3\0\15\32\1\u019d\12\32\30\0\2\32\7\0\32\32"+
    "\3\0\22\32\1\u019e\5\32\32\0\1\u019f\104\0\1\u01a0"+
    "\240\0\1\u01a1\31\0\2\32\7\0\16\32\1\u01a2\13\32"+
    "\3\0\30\32\30\0\2\32\7\0\4\32\1\u01a3\25\32"+
    "\3\0\30\32\30\0\2\32\7\0\16\32\1\u01a4\13\32"+
    "\3\0\30\32\30\0\2\32\7\0\23\32\1\u01a5\6\32"+
    "\3\0\30\32\30\0\2\32\7\0\32\32\3\0\1\u01a6"+
    "\27\32\74\0\1\u011b\132\0\1\u01a7\37\0\1\u01a8\142\0"+
    "\2\32\7\0\15\32\1\u01a9\14\32\3\0\30\32\30\0"+
    "\2\32\7\0\22\32\1\u01aa\7\32\3\0\30\32\30\0"+
    "\2\32\7\0\15\32\1\u01ab\14\32\3\0\30\32\30\0"+
    "\2\32\7\0\10\32\1\u01ac\21\32\3\0\30\32\30\0"+
    "\2\32\7\0\32\32\3\0\17\32\1\u01ad\10\32\114\0"+
    "\1\u01ae\41\0\2\32\7\0\23\32\1\u01af\6\32\3\0"+
    "\30\32\30\0\2\32\7\0\16\32\1\u01b0\13\32\3\0"+
    "\30\32\30\0\2\32\7\0\32\32\3\0\16\32\1\u01b1"+
    "\11\32\111\0\1\u01b2\44\0\2\32\7\0\10\32\1\u01b3"+
    "\21\32\3\0\30\32\30\0\2\32\7\0\15\32\1\u01b4"+
    "\14\32\3\0\30\32\30\0\2\32\7\0\32\32\3\0"+
    "\12\32\1\u01b5\15\32\114\0\1\u01b6\41\0\2\32\7\0"+
    "\16\32\1\u01b7\13\32\3\0\30\32\30\0\2\32\7\0"+
    "\32\32\3\0\5\32\1\u01b8\22\32\116\0\1\u01b9\37\0"+
    "\2\32\7\0\15\32\1\u01ba\14\32\3\0\30\32\30\0"+
    "\2\32\7\0\32\32\3\0\14\32\1\u01bb\13\32\13\0"+
    "\1\u01bc\142\0\2\32\7\0\32\32\3\0\16\32\1\u01bd"+
    "\11\32\30\0\2\32\7\0\32\32\3\0\15\32\1\u01be"+
    "\12\32\4\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[30874];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\5\1\1\11\1\1\6\11\3\1\2\11"+
    "\3\1\1\11\24\1\3\11\13\1\1\11\1\1\2\11"+
    "\1\1\2\11\1\1\1\11\5\0\2\11\4\0\3\11"+
    "\46\1\1\11\10\0\1\1\3\0\51\1\10\0\1\11"+
    "\1\0\47\1\21\0\41\1\2\11\7\0\2\11\7\0"+
    "\33\1\10\0\1\11\2\0\1\11\2\0\1\11\20\1"+
    "\1\11\6\0\1\11\2\0\12\1\10\0\10\1\5\0"+
    "\1\11\3\0\10\1\1\0\2\11\2\0\1\11\6\1"+
    "\3\0\5\1\1\0\1\11\5\1\1\0\3\1\1\0"+
    "\3\1\1\0\2\1\1\0\2\1\1\11\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[446];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */

private List<ErrorLexico> errores = new ArrayList<>();

public List<ErrorLexico> getErrores() {
    return errores;
}

private StringBuilder yyStringBuf = new StringBuilder();
private int stringStartLine = 0;
private int stringStartCol = 0;
private final int MAX_STRING_LENGTH = 2000;

private void appendToStringBuf(String s) {
    if (yyStringBuf.length() + s.length() > MAX_STRING_LENGTH) {
        errores.add(new ErrorLexico("Literal demasiado largo", yyline+1, yycolumn+1, "Lexico", "Cadena excede tamaño máximo"));
    } else {
        yyStringBuf.append(s);
    }
}

private Symbol symbol(int type) {
    return new Symbol(type, yyline+1, yycolumn+1);
}

private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline+1, yycolumn+1, value);
}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
  //constructor
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case STRING: {
              errores.add(new ErrorLexico("EOF dentro de literal de cadena",yyline+1, yycolumn+1,"Lexico","Cadena no cerrada"));
        yybegin(YYINITIAL);
        return null;
            }  // fall though
            case 447: break;
            default:
              {
                return symbol(sym.EOF);
              }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { errores.add( new ErrorLexico( yytext(), yyline+1, yycolumn+1, "Lexico", "Caracter no reconocido"));
            }
          // fall through
          case 101: break;
          case 2:
            { 
            }
          // fall through
          case 102: break;
          case 3:
            { stringStartLine = yyline + 1;
    stringStartCol = yycolumn + 1;
    yyStringBuf.setLength(0);
    yybegin(STRING);
            }
          // fall through
          case 103: break;
          case 4:
            { /*comentario de una linea*/
            }
          // fall through
          case 104: break;
          case 5:
            { return symbol(sym.MOD);
            }
          // fall through
          case 105: break;
          case 6:
            { return symbol(sym.LPAREN);
            }
          // fall through
          case 106: break;
          case 7:
            { return symbol(sym.RPAREN);
            }
          // fall through
          case 107: break;
          case 8:
            { return symbol(sym.MULTI);
            }
          // fall through
          case 108: break;
          case 9:
            { return symbol(sym.SUMA);
            }
          // fall through
          case 109: break;
          case 10:
            { return symbol(sym.COMA);
            }
          // fall through
          case 110: break;
          case 11:
            { return symbol(sym.RESTA);
            }
          // fall through
          case 111: break;
          case 12:
            { return symbol(sym.PUNTO);
            }
          // fall through
          case 112: break;
          case 13:
            { return symbol(sym.DIV);
            }
          // fall through
          case 113: break;
          case 14:
            { return symbol(sym.NUMERO);
            }
          // fall through
          case 114: break;
          case 15:
            { return symbol(sym.DOS_PUNTOS);
            }
          // fall through
          case 115: break;
          case 16:
            { return symbol(sym.PUNTO_COMA);
            }
          // fall through
          case 116: break;
          case 17:
            { return symbol(sym.MENOR);
            }
          // fall through
          case 117: break;
          case 18:
            { return symbol(sym.ASIGNACION);
            }
          // fall through
          case 118: break;
          case 19:
            { return symbol(sym.MAYOR);
            }
          // fall through
          case 119: break;
          case 20:
            { return symbol(sym.COMODIN);
            }
          // fall through
          case 120: break;
          case 21:
            { return symbol(sym.ID, yytext());
            }
          // fall through
          case 121: break;
          case 22:
            { return symbol(sym.LCORCHETE);
            }
          // fall through
          case 122: break;
          case 23:
            { return symbol(sym.RCORCHETE);
            }
          // fall through
          case 123: break;
          case 24:
            { return symbol(sym.POTENCIA);
            }
          // fall through
          case 124: break;
          case 25:
            { return symbol(sym.LLLAVE);
            }
          // fall through
          case 125: break;
          case 26:
            { return symbol(sym.RLLAVE);
            }
          // fall through
          case 126: break;
          case 27:
            { return symbol(sym.NOT);
            }
          // fall through
          case 127: break;
          case 28:
            { appendToStringBuf(yytext());
            }
          // fall through
          case 128: break;
          case 29:
            { errores.add(new ErrorLexico( "Nueva linea en literal de cadena", yyline+1, yycolumn+1, "Lexico", "Nueva linea no permitida dentro de cadena" ));
            }
          // fall through
          case 129: break;
          case 30:
            { String finalLexema = yyStringBuf.toString();
        yybegin(YYINITIAL);
        return new Symbol(sym.CADENA, stringStartLine, stringStartCol, finalLexema);
            }
          // fall through
          case 130: break;
          case 31:
            { appendToStringBuf("@");
            }
          // fall through
          case 131: break;
          case 32:
            { return symbol(sym.DIFERENTE);
            }
          // fall through
          case 132: break;
          case 33:
            { return symbol(sym.AND);
            }
          // fall through
          case 133: break;
          case 34:
            { return symbol(sym.RANGO);
            }
          // fall through
          case 134: break;
          case 35:
            { return symbol(sym.MENOR_IGUAL);
            }
          // fall through
          case 135: break;
          case 36:
            { return symbol(sym.IGUAL);
            }
          // fall through
          case 136: break;
          case 37:
            { return symbol(sym.MAYOR_IGUAL);
            }
          // fall through
          case 137: break;
          case 38:
            { return symbol(sym.DO);
            }
          // fall through
          case 138: break;
          case 39:
            { return symbol(sym.IF);
            }
          // fall through
          case 139: break;
          case 40:
            { return symbol(sym.IN);
            }
          // fall through
          case 140: break;
          case 41:
            { return symbol(sym.OR);
            }
          // fall through
          case 141: break;
          case 42:
            { return symbol(sym.FOR);
            }
          // fall through
          case 142: break;
          case 43:
            { return symbol(sym.RED);
            }
          // fall through
          case 143: break;
          case 44:
            { return symbol(sym.SKY);
            }
          // fall through
          case 144: break;
          case 45:
            { /* comentario multilínea */
            }
          // fall through
          case 145: break;
          case 46:
            { return symbol(sym.BLUE);
            }
          // fall through
          case 146: break;
          case 47:
            { return symbol(sym.ELSE);
            }
          // fall through
          case 147: break;
          case 48:
            { return symbol(sym.LINE);
            }
          // fall through
          case 148: break;
          case 49:
            { return symbol(sym.MONO);
            }
          // fall through
          case 149: break;
          case 50:
            { return symbol(sym.TEXT);
            }
          // fall through
          case 150: break;
          case 51:
            { return symbol(sym.DRAW);
            }
          // fall through
          case 151: break;
          case 52:
            { return symbol(sym.BLACK);
            }
          // fall through
          case 152: break;
          case 53:
            { return symbol(sym.GREEN);
            }
          // fall through
          case 153: break;
          case 54:
            { return symbol(sym.TABLE);
            }
          // fall through
          case 154: break;
          case 55:
            { return symbol(sym.WHILE);
            }
          // fall through
          case 155: break;
          case 56:
            { return symbol(sym.WHITE);
            }
          // fall through
          case 156: break;
          case 57:
            { return symbol(sym.LABEL);
            }
          // fall through
          case 157: break;
          case 58:
            { return symbol(sym.WIDTH);
            }
          // fall through
          case 158: break;
          case 59:
            { appendToStringBuf("@[:sad:]");
            }
          // fall through
          case 159: break;
          case 60:
            { appendToStringBuf("@[:smile:]");
            }
          // fall through
          case 160: break;
          case 61:
            { appendToStringBuf("@[:serious:]");
            }
          // fall through
          case 161: break;
          case 62:
            { appendToStringBuf("@[:heart:]");
            }
          // fall through
          case 162: break;
          case 63:
            { return symbol(sym.DOTTED);
            }
          // fall through
          case 163: break;
          case 64:
            { return symbol(sym.DOUBLE);
            }
          // fall through
          case 164: break;
          case 65:
            { return symbol(sym.NUMBER_PK);
            }
          // fall through
          case 165: break;
          case 66:
            { return symbol(sym.PURPLE);
            }
          // fall through
          case 166: break;
          case 67:
            { return symbol(sym.YELLOW);
            }
          // fall through
          case 167: break;
          case 68:
            { return symbol(sym.HEIGHT);
            }
          // fall through
          case 168: break;
          case 69:
            { return symbol(sym.NUMBER_TYPE);
            }
          // fall through
          case 169: break;
          case 70:
            { return symbol(sym.POINTX);
            }
          // fall through
          case 170: break;
          case 71:
            { return symbol(sym.POINTY);
            }
          // fall through
          case 171: break;
          case 72:
            { return symbol(sym.STRING_TYPE);
            }
          // fall through
          case 172: break;
          case 73:
            { return symbol(sym.STYLES);
            }
          // fall through
          case 173: break;
          case 74:
            { return symbol(sym.COLOR);
            }
          // fall through
          case 174: break;
          case 75:
            { return symbol(sym.HEX_COLOR, yytext());
            }
          // fall through
          case 175: break;
          case 76:
            { return symbol(sym.HSL_COLOR, yytext());
            }
          // fall through
          case 176: break;
          case 77:
            { return symbol(sym.CURSIVE);
            }
          // fall through
          case 177: break;
          case 78:
            { return symbol(sym.SECTION);
            }
          // fall through
          case 178: break;
          case 79:
            { return symbol(sym.CONTENT);
            }
          // fall through
          case 179: break;
          case 80:
            { return symbol(sym.CORRECT);
            }
          // fall through
          case 180: break;
          case 81:
            { return symbol(sym.OPTIONS);
            }
          // fall through
          case 181: break;
          case 82:
            { return symbol(sym.SPECIAL);
            }
          // fall through
          case 182: break;
          case 83:
            { appendToStringBuf("@[:cat:]");
            }
          // fall through
          case 183: break;
          case 84:
            { return symbol(sym.BORDER);
            }
          // fall through
          case 184: break;
          case 85:
            { return symbol(sym.VERTICAL);
            }
          // fall through
          case 185: break;
          case 86:
            { return symbol(sym.ELEMENTS);
            }
          // fall through
          case 186: break;
          case 87:
            { appendToStringBuf("@[:star:]");
            }
          // fall through
          case 187: break;
          case 88:
            { return symbol(sym.HORIZONTAL);
            }
          // fall through
          case 188: break;
          case 89:
            { return symbol(sym.SANS_SERIF);
            }
          // fall through
          case 189: break;
          case 90:
            { String lex = yytext(); // @[:star-3]

        int num = Integer.parseInt(
            lex.substring(7, lex.length()-1)
        );

        for(int i=0;i<num;i++){
            appendToStringBuf("@[:star:]");
        }
            }
          // fall through
          case 190: break;
          case 91:
            { String lex = yytext();

        int num = Integer.parseInt(
            lex.substring(7, lex.length()-2)
        );

        for(int i=0;i<num;i++){
            appendToStringBuf("@[:star:]");
        }
            }
          // fall through
          case 191: break;
          case 92:
            { return symbol(sym.TEXT_SIZE);
            }
          // fall through
          case 192: break;
          case 93:
            { return symbol(sym.ORIENTATION);
            }
          // fall through
          case 193: break;
          case 94:
            { return symbol(sym.FONT_FAMILY);
            }
          // fall through
          case 194: break;
          case 95:
            { return symbol(sym.DROP_QUESTION);
            }
          // fall through
          case 195: break;
          case 96:
            { return symbol(sym.OPEN_QUESTION);
            }
          // fall through
          case 196: break;
          case 97:
            { return symbol(sym.SELECT_QUESTION);
            }
          // fall through
          case 197: break;
          case 98:
            { return symbol(sym.MULTIPLE_QUESTION);
            }
          // fall through
          case 198: break;
          case 99:
            { return symbol(sym.BACKGROUND_COLOR);
            }
          // fall through
          case 199: break;
          case 100:
            { return symbol(sym.POKEMON);
            }
          // fall through
          case 200: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
