// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: /home/herson/Repositorios Git/Proyecto1_Compi1/Proyecto1_Compi1/app/src/main/Flex/Lexer2.flex

package com.example.proyecto1_compi1.Analizadores;

import com.example.proyecto1_compi1.models.ErrorLexico;
import java.util.ArrayList;
import java.util.List;
import java_cup.runtime.Symbol;


@SuppressWarnings("fallthrough")
public class Lexer2 implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int METADATA = 2;
  public static final int STRING = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2, 2
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\1\u0400\266\u0200\10\u0500\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\5\1\0"+
    "\1\6\1\7\4\0\1\10\1\11\2\0\1\12\1\0"+
    "\1\13\1\14\12\15\1\16\1\0\1\17\1\20\1\21"+
    "\1\0\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\0\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\0\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\1\0\1\54\1\0"+
    "\1\55\1\0\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\0\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\0\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\56\1\0\1\57\7\0"+
    "\1\3\115\0\1\60\6\0\1\61\30\0\1\60\6\0"+
    "\1\61\65\0\2\33\115\0\1\43\u01a8\0\2\3\u0100\0"+
    "\1\34\325\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\3\1\4\1\1\1\5\1\1"+
    "\1\6\1\1\1\7\15\1\1\10\1\11\2\12\1\2"+
    "\7\12\1\13\1\14\1\15\1\13\4\0\1\16\35\0"+
    "\10\12\1\13\1\17\4\0\1\6\42\0\1\20\1\0"+
    "\1\21\3\0\1\22\10\12\1\13\34\0\1\23\5\0"+
    "\1\24\1\25\5\0\11\12\41\0\1\26\3\0\1\27"+
    "\4\0\1\30\1\0\5\12\1\31\3\12\1\13\21\0"+
    "\1\32\2\0\1\33\1\0\1\34\6\0\1\35\1\36"+
    "\1\0\1\37\2\0\1\40\4\12\1\41\3\12\1\42"+
    "\1\0\1\43\2\0\1\44\1\0\1\45\1\0\1\46"+
    "\6\0\1\47\2\0\1\50\6\0\1\51\1\52\1\0"+
    "\1\53\3\0\1\12\1\54\5\12\5\0\1\55\1\56"+
    "\1\0\1\57\5\0\1\60\3\0\1\61\6\12\4\0"+
    "\1\62\1\0\1\63\1\64\2\0\1\65\3\0\1\66"+
    "\5\12\1\67\1\70\1\0\1\71\2\0\1\72\1\0"+
    "\1\73\1\74\2\12\1\75\1\76\2\12\1\77\2\0"+
    "\1\100\4\12\2\0\1\101\3\12\1\0\1\102\1\103"+
    "\2\12\1\0\2\12\1\0\2\12\1\0\2\12\1\0"+
    "\2\12\1\104\2\12\1\105\1\106";

  private static int [] zzUnpackAction() {
    int [] result = new int[426];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\310\0\226\0\372\0\u012c"+
    "\0\226\0\u015e\0\u0190\0\u01c2\0\226\0\u01f4\0\u0226\0\u0258"+
    "\0\u028a\0\u02bc\0\u02ee\0\u0320\0\u0352\0\u0384\0\u03b6\0\u03e8"+
    "\0\u041a\0\u044c\0\226\0\226\0\u047e\0\u04b0\0\u04e2\0\u0514"+
    "\0\u0546\0\u0578\0\u05aa\0\u05dc\0\u060e\0\u0640\0\u0672\0\226"+
    "\0\226\0\u06a4\0\u06d6\0\u0708\0\u012c\0\u073a\0\226\0\u076c"+
    "\0\u079e\0\u07d0\0\u0802\0\u0834\0\u0866\0\u0898\0\u08ca\0\u08fc"+
    "\0\u092e\0\u0960\0\u0992\0\u09c4\0\u09f6\0\u0a28\0\u0a5a\0\u0a8c"+
    "\0\u0abe\0\u0af0\0\u0b22\0\u0b54\0\u0b86\0\u0bb8\0\u0bea\0\u0c1c"+
    "\0\u0c4e\0\u0c80\0\u0cb2\0\u0ce4\0\u0d16\0\u0d48\0\u0d7a\0\u0dac"+
    "\0\u0dde\0\u0e10\0\u0e42\0\u0e74\0\u0ea6\0\226\0\u0ed8\0\u0f0a"+
    "\0\u0f3c\0\u0f6e\0\u076c\0\u0fa0\0\u0fd2\0\u1004\0\u1036\0\u1068"+
    "\0\u109a\0\u10cc\0\u10fe\0\u1130\0\u1162\0\u1194\0\u11c6\0\u11f8"+
    "\0\u122a\0\u125c\0\u128e\0\u12c0\0\u12f2\0\u1324\0\u1356\0\u1388"+
    "\0\u13ba\0\u13ec\0\u141e\0\u1450\0\u1482\0\u14b4\0\u14e6\0\u1518"+
    "\0\u154a\0\u157c\0\u15ae\0\u15e0\0\u1612\0\226\0\u1644\0\226"+
    "\0\u1676\0\u16a8\0\u16da\0\226\0\u170c\0\u173e\0\u1770\0\u17a2"+
    "\0\u17d4\0\u1806\0\u1838\0\u186a\0\u189c\0\u18ce\0\u1900\0\u1932"+
    "\0\u1964\0\u1996\0\u19c8\0\u19fa\0\u1a2c\0\u1a5e\0\u1a90\0\u1ac2"+
    "\0\u1af4\0\u1b26\0\u1b58\0\u1b8a\0\u1bbc\0\u1bee\0\u1c20\0\u1c52"+
    "\0\u1c84\0\u1cb6\0\u1ce8\0\u1d1a\0\u1d4c\0\u1d7e\0\u1db0\0\u1de2"+
    "\0\u1e14\0\226\0\u1e46\0\u1e78\0\u1eaa\0\u1edc\0\u1f0e\0\226"+
    "\0\226\0\u1f40\0\u1f72\0\u1fa4\0\u1fd6\0\u2008\0\u203a\0\u206c"+
    "\0\u209e\0\u20d0\0\u2102\0\u2134\0\u2166\0\u2198\0\u21ca\0\u21fc"+
    "\0\u222e\0\u2260\0\u2292\0\u22c4\0\u22f6\0\u2328\0\u235a\0\u238c"+
    "\0\u23be\0\u23f0\0\u2422\0\u2454\0\u2486\0\u24b8\0\u24ea\0\u251c"+
    "\0\u254e\0\u2580\0\u25b2\0\u25e4\0\u2616\0\u2648\0\u267a\0\u26ac"+
    "\0\u26de\0\u2710\0\u2742\0\u2774\0\u27a6\0\u27d8\0\u280a\0\u283c"+
    "\0\226\0\u286e\0\u28a0\0\u28d2\0\226\0\u2904\0\u2936\0\u2968"+
    "\0\u299a\0\226\0\u29cc\0\u29fe\0\u2a30\0\u2a62\0\u2a94\0\u2ac6"+
    "\0\u047e\0\u2af8\0\u2b2a\0\u2b5c\0\226\0\u2b8e\0\u2bc0\0\u2bf2"+
    "\0\u2c24\0\u2c56\0\u2c88\0\u2cba\0\u2cec\0\u2d1e\0\u2d50\0\u2d82"+
    "\0\u2db4\0\u2de6\0\u2e18\0\u2e4a\0\u2e7c\0\u2eae\0\226\0\u2ee0"+
    "\0\u2f12\0\226\0\u2f44\0\226\0\u2f76\0\u2fa8\0\u2fda\0\u300c"+
    "\0\u303e\0\u3070\0\226\0\226\0\u30a2\0\226\0\u30d4\0\u3106"+
    "\0\226\0\u3138\0\u316a\0\u319c\0\u31ce\0\u047e\0\u3200\0\u3232"+
    "\0\u3264\0\226\0\u3296\0\226\0\u32c8\0\u32fa\0\226\0\u332c"+
    "\0\226\0\u335e\0\226\0\u3390\0\u33c2\0\u33f4\0\u3426\0\u3458"+
    "\0\u348a\0\226\0\u34bc\0\u34ee\0\226\0\u3520\0\u3552\0\u3584"+
    "\0\u35b6\0\u35e8\0\u361a\0\226\0\226\0\u364c\0\226\0\u367e"+
    "\0\u36b0\0\u36e2\0\u3714\0\u047e\0\u3746\0\u3778\0\u37aa\0\u37dc"+
    "\0\u380e\0\u3840\0\u3872\0\u38a4\0\u38d6\0\u3908\0\226\0\226"+
    "\0\u393a\0\226\0\u396c\0\u399e\0\u39d0\0\u3a02\0\u3a34\0\226"+
    "\0\u3a66\0\u3a98\0\u3aca\0\226\0\u3afc\0\u3b2e\0\u3b60\0\u3b92"+
    "\0\u3bc4\0\u3bf6\0\u3c28\0\u3c5a\0\u3c8c\0\u3cbe\0\226\0\u3cf0"+
    "\0\226\0\226\0\u3d22\0\u3d54\0\226\0\u3d86\0\u3db8\0\u3dea"+
    "\0\u047e\0\u3e1c\0\u3e4e\0\u3e80\0\u3eb2\0\u3ee4\0\226\0\226"+
    "\0\u3f16\0\226\0\u3f48\0\u3f7a\0\226\0\u3fac\0\226\0\226"+
    "\0\u3fde\0\u4010\0\u047e\0\u047e\0\u4042\0\u4074\0\226\0\u40a6"+
    "\0\u40d8\0\226\0\u410a\0\u413c\0\u416e\0\u41a0\0\u41d2\0\u4204"+
    "\0\u047e\0\u4236\0\u4268\0\u429a\0\u42cc\0\226\0\u047e\0\u42fe"+
    "\0\u4330\0\u4362\0\u4394\0\u43c6\0\u43f8\0\u442a\0\u445c\0\u448e"+
    "\0\u44c0\0\u44f2\0\u4524\0\u4556\0\u4588\0\226\0\u45ba\0\u45ec"+
    "\0\u047e\0\u047e";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[426];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\2\5\1\0\2\5\1\6\1\7\1\10\1\4"+
    "\1\11\1\4\1\12\1\13\1\4\1\14\1\4\1\15"+
    "\2\4\1\16\1\17\1\20\2\4\1\21\1\22\2\4"+
    "\1\23\1\24\2\4\1\25\1\26\1\27\2\4\1\30"+
    "\1\31\1\4\1\32\4\4\1\33\1\34\2\4\1\35"+
    "\1\36\1\5\1\35\2\36\1\35\1\37\13\35\1\40"+
    "\2\35\1\41\1\35\1\42\1\35\1\43\3\35\1\44"+
    "\4\35\1\45\1\46\15\35\2\47\1\50\3\47\1\51"+
    "\13\47\1\52\37\47\63\0\2\5\1\0\2\5\63\0"+
    "\1\53\5\0\1\54\5\0\6\54\32\0\1\55\3\0"+
    "\1\55\7\0\1\56\65\0\1\57\53\0\1\60\1\0"+
    "\1\13\45\0\1\61\3\0\1\61\6\0\1\62\1\63"+
    "\6\0\1\64\1\65\1\66\1\67\1\70\4\0\1\71"+
    "\1\72\1\0\1\73\2\0\1\74\1\75\52\0\1\76"+
    "\71\0\1\77\54\0\1\100\63\0\1\101\57\0\1\102"+
    "\54\0\1\103\66\0\1\104\66\0\1\105\43\0\1\106"+
    "\55\0\1\107\10\0\1\110\54\0\1\111\64\0\1\112"+
    "\56\0\1\113\32\0\2\35\1\0\4\35\1\0\53\35"+
    "\1\36\1\5\1\35\2\36\1\35\1\0\52\35\7\0"+
    "\1\114\52\0\2\35\1\0\4\35\1\0\14\35\1\115"+
    "\20\35\1\116\16\35\1\0\4\35\1\0\17\35\1\117"+
    "\34\35\1\0\4\35\1\0\17\35\1\120\34\35\1\0"+
    "\4\35\1\0\30\35\1\121\23\35\1\0\4\35\1\0"+
    "\51\35\1\122\2\35\1\0\4\35\1\0\17\35\1\123"+
    "\34\35\1\0\4\35\1\0\30\35\1\124\21\35\2\47"+
    "\1\0\3\47\1\0\55\47\1\0\3\47\1\0\44\47"+
    "\1\125\6\47\7\0\1\126\67\0\1\127\5\0\6\127"+
    "\32\0\1\130\3\0\1\130\4\0\1\131\2\0\1\132"+
    "\61\0\1\133\45\0\1\61\3\0\1\61\7\0\1\63"+
    "\71\0\1\134\1\135\1\136\5\0\1\137\1\140\1\0"+
    "\1\141\2\0\1\142\1\143\16\0\1\144\3\0\1\144"+
    "\4\0\1\145\2\0\1\146\67\0\1\147\14\0\1\150"+
    "\61\0\1\151\63\0\1\152\54\0\1\153\64\0\1\154"+
    "\54\0\1\155\73\0\1\156\55\0\1\157\47\0\1\160"+
    "\14\0\1\161\40\0\1\162\3\0\1\163\55\0\1\164"+
    "\21\0\1\165\56\0\1\166\63\0\1\167\1\170\43\0"+
    "\1\171\74\0\1\172\56\0\1\173\61\0\1\174\64\0"+
    "\1\175\45\0\1\176\72\0\1\177\73\0\1\200\52\0"+
    "\1\201\52\0\1\202\63\0\1\203\33\0\1\204\52\0"+
    "\2\35\1\0\4\35\1\0\23\35\1\205\30\35\1\0"+
    "\4\35\1\0\34\35\1\206\17\35\1\0\4\35\1\0"+
    "\33\35\1\207\20\35\1\0\4\35\1\0\15\35\1\210"+
    "\36\35\1\0\4\35\1\0\32\35\1\211\21\35\1\0"+
    "\4\35\1\0\25\35\1\212\26\35\1\0\4\35\1\0"+
    "\25\35\1\213\26\35\1\0\4\35\1\0\34\35\1\214"+
    "\15\35\2\47\1\0\3\47\1\0\7\47\1\215\43\47"+
    "\15\0\1\216\5\0\6\216\32\0\1\130\3\0\1\130"+
    "\4\0\1\131\50\0\1\131\3\0\1\131\7\0\1\217"+
    "\45\0\1\130\3\0\1\130\4\0\1\131\2\0\1\130"+
    "\104\0\1\220\63\0\1\221\54\0\1\222\57\0\1\223"+
    "\73\0\1\224\55\0\1\225\47\0\1\226\14\0\1\227"+
    "\40\0\1\230\37\0\1\144\3\0\1\144\4\0\1\145"+
    "\50\0\1\145\3\0\1\145\7\0\1\231\45\0\1\144"+
    "\3\0\1\144\4\0\1\145\2\0\1\144\71\0\1\232"+
    "\76\0\1\233\54\0\1\234\1\0\1\235\62\0\1\236"+
    "\50\0\1\237\71\0\1\240\61\0\1\241\57\0\1\242"+
    "\53\0\1\243\57\0\1\244\7\0\1\245\75\0\1\246"+
    "\34\0\1\247\105\0\1\250\36\0\1\251\63\0\1\252"+
    "\75\0\1\253\62\0\1\254\41\0\1\255\64\0\1\256"+
    "\65\0\1\257\55\0\1\260\72\0\1\261\62\0\1\262"+
    "\63\0\1\263\62\0\1\264\61\0\1\265\52\0\1\266"+
    "\24\0\2\35\1\0\4\35\1\0\17\35\1\267\34\35"+
    "\1\0\4\35\1\0\22\35\1\270\31\35\1\0\4\35"+
    "\1\0\15\35\1\271\13\35\1\272\22\35\1\0\4\35"+
    "\1\0\22\35\1\273\31\35\1\0\4\35\1\0\13\35"+
    "\1\274\40\35\1\0\4\35\1\0\34\35\1\275\17\35"+
    "\1\0\4\35\1\0\17\35\1\276\34\35\1\0\4\35"+
    "\1\0\13\35\1\277\36\35\2\215\1\300\3\215\1\300"+
    "\45\215\1\47\5\215\15\0\1\301\5\0\6\301\32\0"+
    "\1\302\3\0\1\302\4\0\1\303\2\0\1\304\103\0"+
    "\1\305\62\0\1\306\50\0\1\307\71\0\1\310\57\0"+
    "\1\311\53\0\1\312\57\0\1\313\7\0\1\314\75\0"+
    "\1\315\34\0\1\316\36\0\1\317\3\0\1\317\4\0"+
    "\1\320\2\0\1\321\100\0\1\322\53\0\1\323\73\0"+
    "\1\324\65\0\1\325\56\0\1\326\56\0\1\327\67\0"+
    "\1\330\44\0\1\331\76\0\1\332\54\0\1\333\66\0"+
    "\1\334\44\0\1\335\67\0\1\336\61\0\1\337\70\0"+
    "\1\340\51\0\1\341\60\0\1\342\55\0\1\343\67\0"+
    "\1\344\63\0\1\345\74\0\1\346\44\0\1\347\101\0"+
    "\1\350\37\0\1\351\55\0\1\352\72\0\1\353\21\0"+
    "\2\35\1\0\4\35\1\0\32\35\1\354\21\35\1\0"+
    "\4\35\1\0\30\35\1\355\23\35\1\0\4\35\1\0"+
    "\32\35\1\356\21\35\1\0\4\35\1\0\25\35\1\357"+
    "\26\35\1\0\4\35\1\0\13\35\1\360\40\35\1\0"+
    "\4\35\1\0\6\35\1\361\45\35\1\0\4\35\1\0"+
    "\23\35\1\362\30\35\1\0\4\35\1\0\15\35\1\363"+
    "\36\35\1\0\4\35\1\0\25\35\1\364\24\35\54\300"+
    "\1\365\5\300\15\0\1\366\5\0\6\366\32\0\1\302"+
    "\3\0\1\302\4\0\1\303\50\0\1\303\3\0\1\303"+
    "\7\0\1\367\45\0\1\302\3\0\1\302\4\0\1\303"+
    "\2\0\1\302\110\0\1\370\56\0\1\371\56\0\1\372"+
    "\52\0\1\373\76\0\1\374\54\0\1\375\66\0\1\376"+
    "\44\0\1\377\67\0\1\u0100\61\0\1\u0101\25\0\1\317"+
    "\3\0\1\317\4\0\1\320\50\0\1\320\3\0\1\320"+
    "\7\0\1\u0102\45\0\1\317\3\0\1\317\4\0\1\320"+
    "\2\0\1\317\75\0\1\u0103\57\0\1\u0104\74\0\1\u0105"+
    "\46\0\1\u0106\52\0\1\u0107\70\0\1\u0108\37\0\1\u0109"+
    "\75\0\1\u010a\73\0\1\u010b\46\0\1\u010c\74\0\1\u010d"+
    "\53\0\1\u010e\63\0\1\u010f\61\0\1\u0110\37\0\1\u0111"+
    "\122\0\1\u0112\41\0\1\u0113\62\0\1\u0114\72\0\1\u0115"+
    "\50\0\1\u0116\75\0\1\u0117\43\0\1\u0118\103\0\1\u0119"+
    "\12\0\2\35\1\0\4\35\1\0\34\35\1\u011a\17\35"+
    "\1\0\4\35\1\0\32\35\1\u011b\21\35\1\0\4\35"+
    "\1\0\23\35\1\u011c\30\35\1\0\4\35\1\0\17\35"+
    "\1\u011d\34\35\1\0\4\35\1\0\6\35\1\u011e\45\35"+
    "\1\0\4\35\1\0\31\35\1\u011f\22\35\1\0\4\35"+
    "\1\0\15\35\1\u0120\36\35\1\0\2\35\1\u0121\1\35"+
    "\1\0\52\35\15\0\1\u0122\5\0\6\u0122\32\0\1\u0123"+
    "\3\0\1\u0123\3\0\1\u0124\3\0\1\u0125\73\0\1\u0126"+
    "\53\0\1\u0127\67\0\1\u0128\53\0\1\u0129\73\0\1\u012a"+
    "\47\0\1\u012b\73\0\1\u012c\53\0\1\u012d\63\0\1\u012e"+
    "\61\0\1\u012f\33\0\1\u0130\3\0\1\u0130\7\0\1\u0131"+
    "\3\0\1\u0132\102\0\1\u0133\61\0\1\u0134\37\0\1\u0135"+
    "\100\0\1\u0136\61\0\1\u0137\52\0\1\u0138\72\0\1\u0139"+
    "\60\0\1\u013a\65\0\1\u013b\36\0\1\u013c\61\0\1\u013d"+
    "\103\0\1\u013e\45\0\1\u013f\71\0\1\u0140\51\0\1\u0141"+
    "\55\0\1\u0142\36\0\2\35\1\0\4\35\1\0\13\35"+
    "\1\u0143\40\35\1\0\4\35\1\0\6\35\1\u0144\45\35"+
    "\1\0\4\35\1\0\31\35\1\u0145\22\35\1\0\4\35"+
    "\1\0\21\35\1\u0146\32\35\1\0\4\35\1\0\25\35"+
    "\1\u0147\26\35\1\0\4\35\1\0\23\35\1\u0148\30\35"+
    "\1\0\4\35\1\0\16\35\1\u0149\33\35\1\0\1\u0123"+
    "\3\0\1\u0123\3\0\1\u0124\51\0\1\u0123\3\0\1\u0123"+
    "\3\0\1\u0124\3\0\1\u0123\103\0\1\u014a\61\0\1\u014b"+
    "\63\0\1\u014c\60\0\1\u014d\65\0\1\u014e\36\0\1\u014f"+
    "\61\0\1\u0150\41\0\1\u0130\3\0\1\u0130\13\0\1\u0132"+
    "\41\0\1\u0130\3\0\1\u0130\7\0\1\u0130\3\0\1\u0132"+
    "\100\0\1\u0151\33\0\1\u0152\113\0\1\u0153\61\0\1\u0154"+
    "\40\0\1\u0155\73\0\1\u0156\63\0\1\u0157\42\0\1\u0158"+
    "\74\0\1\u0159\72\0\1\u015a\57\0\1\u015b\54\0\1\u015c"+
    "\24\0\2\35\1\0\4\35\1\0\33\35\1\u015d\20\35"+
    "\1\0\4\35\1\0\34\35\1\u015e\17\35\1\0\4\35"+
    "\1\0\13\35\1\u015f\40\35\1\0\4\35\1\0\17\35"+
    "\1\u0160\34\35\1\0\4\35\1\0\50\35\1\u0161\3\35"+
    "\1\0\4\35\1\0\17\35\1\u0162\32\35\44\0\1\u0163"+
    "\61\0\1\u0164\52\0\1\u0165\63\0\1\u0166\43\0\1\u0167"+
    "\105\0\1\u0168\35\0\1\u0169\61\0\1\u016a\76\0\1\u016b"+
    "\52\0\1\u016c\52\0\1\u016d\113\0\1\u016e\32\0\1\u016f"+
    "\71\0\1\u0170\26\0\2\35\1\0\4\35\1\0\6\35"+
    "\1\u0171\45\35\1\0\4\35\1\0\23\35\1\u0172\30\35"+
    "\1\0\4\35\1\0\14\35\1\u0173\37\35\1\0\4\35"+
    "\1\0\33\35\1\u0174\20\35\1\0\4\35\1\0\27\35"+
    "\1\u0175\24\35\1\0\2\35\1\u0176\1\35\1\0\52\35"+
    "\21\0\1\u0177\61\0\1\u0178\67\0\1\u0179\53\0\1\u017a"+
    "\77\0\1\u017b\55\0\1\u017c\46\0\1\u017d\70\0\1\u017e"+
    "\67\0\1\u017f\54\0\1\u0180\31\0\2\35\1\0\4\35"+
    "\1\0\30\35\1\u0181\23\35\1\0\4\35\1\0\25\35"+
    "\1\u0182\26\35\1\0\4\35\1\0\6\35\1\u0183\45\35"+
    "\1\0\4\35\1\0\6\35\1\u0184\45\35\1\0\4\35"+
    "\1\0\31\35\1\u0185\1\35\1\u0186\16\35\21\0\1\u0187"+
    "\66\0\1\u0188\70\0\1\u0189\44\0\1\u018a\41\0\2\35"+
    "\1\0\4\35\1\0\27\35\1\u018b\24\35\1\0\4\35"+
    "\1\0\17\35\1\u018c\34\35\1\0\4\35\1\0\32\35"+
    "\1\u018d\21\35\1\0\4\35\1\0\17\35\1\u018e\32\35"+
    "\5\0\1\u018f\125\0\1\u0190\10\0\2\35\1\0\4\35"+
    "\1\0\6\35\1\u0191\45\35\1\0\4\35\1\0\33\35"+
    "\1\u0192\20\35\1\0\4\35\1\0\17\35\1\u0193\34\35"+
    "\1\0\4\35\1\0\15\35\1\u0194\34\35\25\0\1\u0195"+
    "\54\0\1\u0196\41\0\2\35\1\0\4\35\1\0\6\35"+
    "\1\u0197\45\35\1\0\4\35\1\0\21\35\1\u0198\32\35"+
    "\1\0\4\35\1\0\15\35\1\u0199\34\35\40\0\1\u019a"+
    "\21\0\2\35\1\0\4\35\1\0\35\35\1\u019b\16\35"+
    "\1\0\4\35\1\0\23\35\1\u019c\26\35\35\0\1\u019d"+
    "\24\0\2\35\1\0\4\35\1\0\27\35\1\u019e\24\35"+
    "\1\0\4\35\1\0\30\35\1\u019f\21\35\40\0\1\u01a0"+
    "\21\0\2\35\1\0\4\35\1\0\34\35\1\u01a1\17\35"+
    "\1\0\4\35\1\0\27\35\1\u01a2\22\35\42\0\1\u01a3"+
    "\17\0\2\35\1\0\4\35\1\0\13\35\1\u01a4\40\35"+
    "\1\0\4\35\1\0\17\35\1\u01a5\32\35\20\0\1\u01a6"+
    "\41\0\2\35\1\0\4\35\1\0\33\35\1\u01a7\20\35"+
    "\1\0\4\35\1\0\33\35\1\u01a8\20\35\1\0\4\35"+
    "\1\0\6\35\1\u01a9\45\35\1\0\4\35\1\0\6\35"+
    "\1\u01aa\43\35";

  private static int [] zzUnpacktrans() {
    int [] result = new int[17950];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\1\1\1\11\2\1\1\11\3\1\1\11"+
    "\15\1\2\11\13\1\2\11\1\1\4\0\1\11\35\0"+
    "\11\1\1\11\4\0\1\1\42\0\1\11\1\0\1\11"+
    "\3\0\1\11\11\1\34\0\1\11\5\0\2\11\5\0"+
    "\11\1\41\0\1\11\3\0\1\11\4\0\1\11\1\0"+
    "\11\1\1\11\21\0\1\11\2\0\1\11\1\0\1\11"+
    "\6\0\2\11\1\0\1\11\2\0\1\11\10\1\1\11"+
    "\1\0\1\11\2\0\1\11\1\0\1\11\1\0\1\11"+
    "\6\0\1\11\2\0\1\11\6\0\2\11\1\0\1\11"+
    "\3\0\7\1\5\0\2\11\1\0\1\11\5\0\1\11"+
    "\3\0\1\11\6\1\4\0\1\11\1\0\2\11\2\0"+
    "\1\11\3\0\6\1\2\11\1\0\1\11\2\0\1\11"+
    "\1\0\2\11\6\1\1\11\2\0\1\11\4\1\2\0"+
    "\4\1\1\0\1\11\3\1\1\0\2\1\1\0\2\1"+
    "\1\0\2\1\1\0\2\1\1\11\4\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[426];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */

private List<ErrorLexico> errores = new ArrayList<>();

public List<ErrorLexico> getErrores() {
    return errores;
}

private StringBuilder yyStringBuf = new StringBuilder();
private int stringStartLine = 0;
private int stringStartCol  = 0;

private Symbol symbol(int type) {
    return new Symbol(type, yyline+1, yycolumn+1);
}

private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline+1, yycolumn+1, value);
}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer2(java.io.Reader in) {
      this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case STRING: {
              errores.add(new ErrorLexico(
            "EOF en cadena",
            yyline+1, yycolumn+1,
            "Lexico", "Cadena no cerrada"
        ));
        yybegin(YYINITIAL);
        return null;
            }  // fall though
            case 427: break;
            default:
              {
                return symbol(sym2.EOF);
              }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { errores.add(new ErrorLexico(
            yytext(), yyline+1, yycolumn+1,
            "Lexico", "Caracter no reconocido"
        ));
            }
          // fall through
          case 71: break;
          case 2:
            { 
            }
          // fall through
          case 72: break;
          case 3:
            { stringStartLine = yyline + 1;
        stringStartCol  = yycolumn + 1;
        yyStringBuf.setLength(0);
        yybegin(STRING);
            }
          // fall through
          case 73: break;
          case 4:
            { return symbol(sym2.HASH);
            }
          // fall through
          case 74: break;
          case 5:
            { return symbol(sym2.COMA);
            }
          // fall through
          case 75: break;
          case 6:
            { return symbol(sym2.NUMERO, Double.parseDouble(yytext()));
            }
          // fall through
          case 76: break;
          case 7:
            { return symbol(sym2.GT);
            }
          // fall through
          case 77: break;
          case 8:
            { return symbol(sym2.LLLAVE);
            }
          // fall through
          case 78: break;
          case 9:
            { return symbol(sym2.RLLAVE);
            }
          // fall through
          case 79: break;
          case 10:
            { return symbol(sym2.META_VALOR, yytext().trim());
            }
          // fall through
          case 80: break;
          case 11:
            { yyStringBuf.append(yytext());
            }
          // fall through
          case 81: break;
          case 12:
            { errores.add(new ErrorLexico(
            "Nueva linea en cadena",
            yyline+1, yycolumn+1,
            "Lexico", "Nueva linea no permitida dentro de cadena"
        ));
            }
          // fall through
          case 82: break;
          case 13:
            { String val = yyStringBuf.toString();
        yybegin(YYINITIAL);
        return symbol(sym2.CADENA, val);
            }
          // fall through
          case 83: break;
          case 14:
            { return symbol(sym2.SLASH_GT);
            }
          // fall through
          case 84: break;
          case 15:
            { yybegin(METADATA); return symbol(sym2.TRIPLE_HASH);
            }
          // fall through
          case 85: break;
          case 16:
            { return symbol(sym2.RED);
            }
          // fall through
          case 86: break;
          case 17:
            { return symbol(sym2.SKY);
            }
          // fall through
          case 87: break;
          case 18:
            { yybegin(YYINITIAL); return symbol(sym2.TRIPLE_HASH);
            }
          // fall through
          case 88: break;
          case 19:
            { return symbol(sym2.BLUE);
            }
          // fall through
          case 89: break;
          case 20:
            { return symbol(sym2.LINE);
            }
          // fall through
          case 90: break;
          case 21:
            { return symbol(sym2.MONO);
            }
          // fall through
          case 91: break;
          case 22:
            { return symbol(sym2.BLACK);
            }
          // fall through
          case 92: break;
          case 23:
            { return symbol(sym2.GREEN);
            }
          // fall through
          case 93: break;
          case 24:
            { return symbol(sym2.WHITE);
            }
          // fall through
          case 94: break;
          case 25:
            { return symbol(sym2.META_HORA);
            }
          // fall through
          case 95: break;
          case 26:
            { return symbol(sym2.TAG_DROP_Q);
            }
          // fall through
          case 96: break;
          case 27:
            { return symbol(sym2.TAG_LINE_OPEN);
            }
          // fall through
          case 97: break;
          case 28:
            { return symbol(sym2.TAG_OPEN_Q);
            }
          // fall through
          case 98: break;
          case 29:
            { return symbol(sym2.DOTTED);
            }
          // fall through
          case 99: break;
          case 30:
            { return symbol(sym2.DOUBLE);
            }
          // fall through
          case 100: break;
          case 31:
            { return symbol(sym2.PURPLE);
            }
          // fall through
          case 101: break;
          case 32:
            { return symbol(sym2.YELLOW);
            }
          // fall through
          case 102: break;
          case 33:
            { return symbol(sym2.META_FECHA);
            }
          // fall through
          case 103: break;
          case 34:
            { return symbol(sym2.HEX_COLOR, yytext());
            }
          // fall through
          case 104: break;
          case 35:
            { return symbol(sym2.RGB_COLOR, yytext());
            }
          // fall through
          case 105: break;
          case 36:
            { return symbol(sym2.TAG_DROP_Q_CLOSE);
            }
          // fall through
          case 106: break;
          case 37:
            { return symbol(sym2.TAG_LINE_CLOSE);
            }
          // fall through
          case 107: break;
          case 38:
            { return symbol(sym2.TAG_OPEN_Q_CLOSE);
            }
          // fall through
          case 108: break;
          case 39:
            { return symbol(sym2.HSL_COLOR, yytext());
            }
          // fall through
          case 109: break;
          case 40:
            { return symbol(sym2.TAG_COLOR);
            }
          // fall through
          case 110: break;
          case 41:
            { return symbol(sym2.TAG_STYLE_OPEN);
            }
          // fall through
          case 111: break;
          case 42:
            { return symbol(sym2.TAG_TABLE_OPEN);
            }
          // fall through
          case 112: break;
          case 43:
            { return symbol(sym2.CURSIVE);
            }
          // fall through
          case 113: break;
          case 44:
            { return symbol(sym2.META_AUTHOR);
            }
          // fall through
          case 114: break;
          case 45:
            { return symbol(sym2.TAG_STYLE_CLOSE);
            }
          // fall through
          case 115: break;
          case 46:
            { return symbol(sym2.TAG_TABLE_CLOSE);
            }
          // fall through
          case 116: break;
          case 47:
            { return symbol(sym2.TAG_BORDER);
            }
          // fall through
          case 117: break;
          case 48:
            { return symbol(sym2.TAG_SELECT_Q);
            }
          // fall through
          case 118: break;
          case 49:
            { return symbol(sym2.VERTICAL);
            }
          // fall through
          case 119: break;
          case 50:
            { return symbol(sym2.TAG_SELECT_Q_CLOSE);
            }
          // fall through
          case 120: break;
          case 51:
            { return symbol(sym2.TAG_CONTENT_OPEN);
            }
          // fall through
          case 121: break;
          case 52:
            { return symbol(sym2.TAG_ELEMENT_OPEN);
            }
          // fall through
          case 122: break;
          case 53:
            { return symbol(sym2.TAG_SECTION_OPEN);
            }
          // fall through
          case 123: break;
          case 54:
            { return symbol(sym2.META_ABIERTAS);
            }
          // fall through
          case 124: break;
          case 55:
            { return symbol(sym2.TAG_CONTENT_CLOSE);
            }
          // fall through
          case 125: break;
          case 56:
            { return symbol(sym2.TAG_ELEMENT_CLOSE);
            }
          // fall through
          case 126: break;
          case 57:
            { return symbol(sym2.TAG_SECTION_CLOSE);
            }
          // fall through
          case 127: break;
          case 58:
            { return symbol(sym2.TAG_MULTIPLE_Q);
            }
          // fall through
          case 128: break;
          case 59:
            { return symbol(sym2.HORIZONTAL);
            }
          // fall through
          case 129: break;
          case 60:
            { return symbol(sym2.SANS_SERIF);
            }
          // fall through
          case 130: break;
          case 61:
            { return symbol(sym2.META_MULTIPLES);
            }
          // fall through
          case 131: break;
          case 62:
            { return symbol(sym2.META_SELECCION);
            }
          // fall through
          case 132: break;
          case 63:
            { return symbol(sym2.TAG_MULTIPLE_Q_CLOSE);
            }
          // fall through
          case 133: break;
          case 64:
            { return symbol(sym2.TAG_TEXT_SIZE);
            }
          // fall through
          case 134: break;
          case 65:
            { return symbol(sym2.META_DESC);
            }
          // fall through
          case 135: break;
          case 66:
            { return symbol(sym2.TAG_FONT);
            }
          // fall through
          case 136: break;
          case 67:
            { return symbol(sym2.META_DESPLEGABLES);
            }
          // fall through
          case 137: break;
          case 68:
            { return symbol(sym2.TAG_BG_COLOR);
            }
          // fall through
          case 138: break;
          case 69:
            { return symbol(sym2.META_PREGUNTAS);
            }
          // fall through
          case 139: break;
          case 70:
            { return symbol(sym2.META_SECCIONES);
            }
          // fall through
          case 140: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
